-- Intentionally empty compatibility migration.
--
-- This hand-written migration originally created classification_logs and
-- voice_usage, then attempted to add columns it had just created. It also
-- duplicated the generated 0005_flippant_eternity migration. Keeping the
-- journal entry as a no-op preserves already-deployed migration ordering while
-- allowing a clean database to be built deterministically by 0005.
