-- Intentionally empty compatibility migration.
--
-- Every table, column and index previously declared here is created by the
-- generated 0005_flippant_eternity migration. Keeping this timestamped entry
-- as a no-op avoids duplicate-column/table failures on clean installations
-- without replaying or mutating data on databases that already applied it.
