/**
 * Egyptian stores, chains and apps by name, filed under the taxonomy (converted from the old
 * `egypt_merchants_rag.json`, with names and everyday words removed by hand: «شهري», «رايح», «لله»).
 * Unlike the hand-checked registry in `merchants.ts`, a hit here is not trusted by construction:
 * it is its own evidence kind (`merchant_catalog`), priced from real corrections, and is read only
 * when no purpose word in the sentence answered first.
 */
export interface CatalogMerchant {
  merchant: string;
  category: string;
  subCategory: string;
  keywords: string[];
}

export const MERCHANT_CATALOG: readonly CatalogMerchant[] = [
  { merchant: "WE", category: "فواتير", subCategory: "تليفون", keywords: ["المصرية للاتصالات", "Telecom Egypt", "تي داتا"] },
  { merchant: "Vodafone", category: "فواتير", subCategory: "تليفون", keywords: ["ڤودافون", "فوادفون"] },
  { merchant: "Etisalat", category: "فواتير", subCategory: "تليفون", keywords: ["اتصلات"] },
  { merchant: "Orange", category: "فواتير", subCategory: "تليفون", keywords: ["موبينيل", "اورانج", "Mobinil"] },
  { merchant: "NOOR", category: "فواتير", subCategory: "إنترنت", keywords: ["نور للانترنت", "Noor ADSL"] },
  { merchant: "inDrive", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["In driver"] },
  { merchant: "Swvl", category: "مواصلات", subCategory: "أتوبيس", keywords: ["سوفل"] },
  { merchant: "GoBus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["حجز جوباص", "جوباص", "Go Bus", "تذكرة جوباص", "جو باص"] },
  { merchant: "Cairo Metro", category: "مواصلات", subCategory: "مترو", keywords: ["تذكرة المترو", "مترو القاهرة", "اشتراك المترو"] },
  { merchant: "Buseet", category: "مواصلات", subCategory: "أتوبيس", keywords: ["رحلة بسيط", "Buseet"] },
  { merchant: "Super Jet", category: "مواصلات", subCategory: "أتوبيس", keywords: ["اتوبيس سوبر جيت", "سوبرجيت", "Super Jet", "سوبر جيت"] },
  { merchant: "Blue Bus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["تذكرة بلو باص", "Blue Bus", "بلو باص", "بلوباص"] },
  { merchant: "East Delta", category: "مواصلات", subCategory: "أتوبيس", keywords: ["شرق الدلتا", "الشرق للدلتا"] },
  { merchant: "EgyBus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["إيجي باص", "EgyBus"] },
  { merchant: "Talabat", category: "أكل وشرب", subCategory: "دليفري", keywords: ["Otlob"] },
  { merchant: "InstaShop", category: "أكل وشرب", subCategory: "بقالة", keywords: ["انستا شوب", "انستاشوب"] },
  { merchant: "Breadfast", category: "أكل وشرب", subCategory: "بقالة", keywords: ["تطبيق بريدفاست", "بريد فاست", "بريد فست"] },
  { merchant: "Carrefour", category: "أكل وشرب", subCategory: "بقالة", keywords: ["كرفور"] },
  { merchant: "Spinneys", category: "أكل وشرب", subCategory: "بقالة", keywords: ["سبينس"] },
  { merchant: "Seoudi", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ماركت سعودي"] },
  { merchant: "Kazyon", category: "أكل وشرب", subCategory: "بقالة", keywords: ["سوبر ماركت كازيون", "كزيون"] },
  { merchant: "Awlad Ragab", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Ragab Sons"] },
  { merchant: "Hyper One", category: "أكل وشرب", subCategory: "بقالة", keywords: ["هايبروان", "هايبر الشيخ زايد"] },
  { merchant: "Fathalla", category: "أكل وشرب", subCategory: "بقالة", keywords: ["اسواق فتح الله"] },
  { merchant: "Zahran", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ماركت زهران"] },
  { merchant: "Gourmet", category: "أكل وشرب", subCategory: "بقالة", keywords: ["جورميه", "غورميه"] },
  { merchant: "Abu Ashara", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ابو عشرة"] },
  { merchant: "Lulu Hypermarket", category: "أكل وشرب", subCategory: "بقالة", keywords: ["لولو هايبر", "Lulu Hypermarket"] },
  { merchant: "Metro Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ماركت مترو"] },
  { merchant: "Kheir Zaman", category: "أكل وشرب", subCategory: "بقالة", keywords: ["خيرزمان"] },
  { merchant: "El Hawary", category: "أكل وشرب", subCategory: "بقالة", keywords: ["الهواري"] },
  { merchant: "Mahmoud Elfar", category: "أكل وشرب", subCategory: "بقالة", keywords: ["سوبرماركت الفار", "محمود الفار"] },
  { merchant: "B.TECH", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["تقسيط بي تك", "B TECH"] },
  { merchant: "Raneen", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["عروض رنين"] },
  { merchant: "Aman", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["تقسيط امان"] },
  { merchant: "ValU", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["ڤاليو", "تقسيط فاليو", "قسط فاليو", "ابلكيشن فاليو"] },
  { merchant: "Sympl", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["Sympl", "قسط سيمبل", "سيمبل", "تقسيط سيمبل", "سمبل"] },
  { merchant: "Shahry", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["تقسيط شهري", "قسط شهري"] },
  { merchant: "Amazon Egypt", category: "تسوق", subCategory: "عام", keywords: ["امازون مصر", "AMAZON.EG", "سوق دوت كوم"] },
  { merchant: "Raya Shop", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["تقسيط راية", "Raya Shop", "راية شوب"] },
  { merchant: "2B", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["تو بي"] },
  { merchant: "El Araby Group", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["تورنيدو", "توشيبا", "مجموعة العربي", "Toshiba"] },
  { merchant: "Fresh", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["اجهزة فريش", "Fresh electric"] },
  { merchant: "Unionaire", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["يونيون اير", "Unionaire"] },
  { merchant: "Premium Card", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["Premium Card", "تقسيط بريميوم كارد", "بريميم كارد", "بريميوم كارد"] },
  { merchant: "Contact", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["قسط كونتكت", "كونتكت كار", "كونتكت للتقسيط"] },
  { merchant: "Souhoola", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["قسط سهولة", "تقسيط سهولة", "ابلكيشن سهولة"] },
  { merchant: "Forsa", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["قسط فرصة", "ابلكيشن فرصة", "تقسيط فرصة"] },
  { merchant: "KFC", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["دجاج كنتاكي"] },
  { merchant: "Buffalo Burger", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["بافلوا", "Buffalo Burger", "بافلو برجر"] },
  { merchant: "Bazooka", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["بزوكا", "Bazooka Fried Chicken", "بازوكا"] },
  { merchant: "Spectra", category: "أكل وشرب", subCategory: "مطعم", keywords: ["سبكترا"] },
  { merchant: "Cilantro", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["سلانترو"] },
  { merchant: "Costa Coffee", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["كافيه كوستا"] },
  { merchant: "Starbucks", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["استاربكس"] },
  { merchant: "TBS", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["تي بي اس", "The Bakery Shop"] },
  { merchant: "Papa John's", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["بابا جونز"] },
  { merchant: "Domino's Pizza", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["دومينوز بيتزا"] },
  { merchant: "Pronto Pizza", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["برونتو", "برونتو بيتزا"] },
  { merchant: "Cook Door", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Cook Door", "كوكدور", "كوك دور"] },
  { merchant: "Mo'men", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["سندوتشات مؤمن"] },
  { merchant: "Prego", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["سندوتشات بريجو", "Prego", "بريجو"] },
  { merchant: "Koshary Abou Tarek", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري ابو طارق"] },
  { merchant: "Sayed Hanafy", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري سيد حنفي", "سيد حنفى"] },
  { merchant: "El Dawar", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فطير الدوار", "فطاطري الدوار"] },
  { merchant: "Willy's Kitchen", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Willys Kitchen", "ويليز", "ويليز كيتشن"] },
  { merchant: "Zack's", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Zack's", "زاكس", "زاكس فرايد تشيكن"] },
  { merchant: "Heart Attack", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Heart Attack Restaurant", "هارت اتاك"] },
  { merchant: "Macarona Reda", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مكرونة رضا"] },
  { merchant: "Sobhy Kaber", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مشويات صبحي كابر"] },
  { merchant: "El Prince", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبدة البرنس", "كبارى البرنس", "برنس امبابة"] },
  { merchant: "Qasr El Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["قصر الكبابجي", "الكبابجي"] },
  { merchant: "Abou Shakra", category: "أكل وشرب", subCategory: "مطعم", keywords: ["ابو شقره", "Abou Shakra"] },
  { merchant: "Beano's", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["بينوز", "بينوز كافيه"] },
  { merchant: "Espresso Lab", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["اسبريسو لاب", "اسبريسولاب"] },
  { merchant: "Paul", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["مخبز بول"] },
  { merchant: "Second Cup", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["سكند كوب", "سكند كاب"] },
  { merchant: "Cinnabon", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["سينابون"] },
  { merchant: "Dunkin' Donuts", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["دانكن", "دانكن دونتس"] },
  { merchant: "Krispy Kreme", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["كرسبي كريم", "كريسبي كريم"] },
  { merchant: "Nola", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["نولا كب كيك", "نولا"] },
  { merchant: "Salé Sucré", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Sale Sucre", "ساليه سوكريه"] },
  { merchant: "La Poire", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["حلواني لابوار", "لا بوار", "La Poire", "لابوار"] },
  { merchant: "El Abd Patisserie", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["بسكوت العبد", "El Abd", "حلواني العبد"] },
  { merchant: "Tseppas", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["تسيباس", "Tseppas"] },
  { merchant: "Etoile", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["حلواني ايتوال", "ايتوال"] },
  { merchant: "Mandarine Koueider", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["ماندرين قويدر", "Koueider", "قويدر"] },
  { merchant: "Twinkies", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["توينكيز", "تونكيز"] },
  { merchant: "Monginis", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Monginis", "مونجيني", "تورته مونجيني"] },
  { merchant: "Vezeeta", category: "صحة", subCategory: "دكتور", keywords: ["فيزيتا", "حجز دكتور فيزيتا", "ڤيزيتا", "Vezeeta"] },
  { merchant: "Yashfee", category: "صحة", subCategory: "صيدلية", keywords: ["يشفي", "صيدلية يشفي", "Yashfee"] },
  { merchant: "El Ezaby Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["El Ezaby"] },
  { merchant: "Seif Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["Seif Pharmacies", "صيدليات سيف"] },
  { merchant: "19011 Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["19011", "صيدلية 19011", "صيدليات 19011"] },
  { merchant: "Roshdy Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["صيدليات رشدي"] },
  { merchant: "Elezz Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["صيدلية العز", "صيدليات العز"] },
  { merchant: "Chefaa", category: "صحة", subCategory: "صيدلية", keywords: ["تطبيق شفاء", "Chefaa"] },
  { merchant: "Dawaya", category: "صحة", subCategory: "صيدلية", keywords: ["دوايا", "Dawaya"] },
  { merchant: "Dawi Clinics", category: "صحة", subCategory: "دكتور", keywords: ["عيادات داوي"] },
  { merchant: "Andalusia Hospitals", category: "صحة", subCategory: "مستشفى", keywords: ["مستشفيات اندلسية", "اندلسية", "Andalusia"] },
  { merchant: "Cleopatra Hospitals", category: "صحة", subCategory: "مستشفى", keywords: ["Cleopatra Hospital", "مستشفى كليوباترا"] },
  { merchant: "Magdi Yacoub Heart Foundation", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["مستشفى مجدي يعقوب", "مؤسسة مجدى يعقوب"] },
  { merchant: "Baheya Foundation", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["Baheya", "مؤسسة بهية", "مستشفى بهية"] },
  { merchant: "57357 Hospital", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["مستشفى 57357", "مستشفى سرطان الاطفال", "57357"] },
  { merchant: "Orman Association", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["جمعية الاورمان", "الاورمان", "Orman"] },
  { merchant: "Resala Association", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["جمعية رسالة"] },
  { merchant: "Misr El Kheir", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["Misr El Kheir", "مؤسسة مصر الخير", "مصر الخير"] },
  { merchant: "Food Bank", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["بنك الطعام", "بنك الطعام المصري"] },
  { merchant: "Netflix", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["نتفليكس"] },
  { merchant: "WatchIT", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["واتشيت"] },
  { merchant: "Shahid", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["شاهد نت", "شاهد في اي بي"] },
  { merchant: "OSN+", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["اواس ان", "او اس ان"] },
  { merchant: "Spotify", category: "اشتراكات", subCategory: "موسيقى", keywords: ["اسبوتيفاي"] },
  { merchant: "Todd", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["منصة تود"] },
  { merchant: "beIN Sports", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["بين سبورت", "بي ان سبورت"] },
  { merchant: "Vox Cinemas", category: "ترفيه", subCategory: "سينما", keywords: ["ڤوكس", "فوكس سينما", "سينما فوكس"] },
  { merchant: "Renaissance Cinemas", category: "ترفيه", subCategory: "سينما", keywords: ["رينيسانس", "سينما رينيسانس", "Renaissance"] },
  { merchant: "Galaxy Cinema", category: "ترفيه", subCategory: "سينما", keywords: ["سينما جلاكسي", "Galaxy Cinema"] },
  { merchant: "Plaza Cinema", category: "ترفيه", subCategory: "سينما", keywords: ["سينما بلازا", "Plaza Cinema"] },
  { merchant: "Dream Park", category: "ترفيه", subCategory: "خروجة", keywords: ["ملاهي دريم بارك", "Dream Park", "دريم بارك"] },
  { merchant: "Zed Park", category: "ترفيه", subCategory: "خروجة", keywords: ["ملاهي زيد", "Zed Park", "زيد بارك", "زد بارك"] },
  { merchant: "Magic Planet", category: "ترفيه", subCategory: "خروجة", keywords: ["ماجيك بلانيت", "ماجيك بلانت"] },
  { merchant: "Ski Egypt", category: "ترفيه", subCategory: "خروجة", keywords: ["سكي ايجيبت", "سكي مصر", "Ski Egypt"] },
  { merchant: "Zara", category: "تسوق", subCategory: "ملابس", keywords: ["زرا"] },
  { merchant: "LC Waikiki", category: "تسوق", subCategory: "ملابس", keywords: ["ال سي وايكيكي"] },
  { merchant: "Defacto", category: "تسوق", subCategory: "ملابس", keywords: ["دي فاكتو"] },
  { merchant: "Town Team", category: "تسوق", subCategory: "ملابس", keywords: ["تاون تيم", "Town Team"] },
  { merchant: "Ravin", category: "تسوق", subCategory: "ملابس", keywords: ["رافين"] },
  { merchant: "Max Fashion", category: "تسوق", subCategory: "ملابس", keywords: ["ماكس فاشون"] },
  { merchant: "Splash", category: "تسوق", subCategory: "ملابس", keywords: ["سبلاش"] },
  { merchant: "Nike", category: "تسوق", subCategory: "ملابس", keywords: ["نايك"] },
  { merchant: "Activ", category: "تسوق", subCategory: "ملابس", keywords: ["أبو علاء اكتيف"] },
  { merchant: "Kickers", category: "تسوق", subCategory: "ملابس", keywords: ["كيكرز"] },
  { merchant: "Aldo", category: "تسوق", subCategory: "ملابس", keywords: ["الدو"] },
  { merchant: "Bata", category: "تسوق", subCategory: "ملابس", keywords: ["احذية باتا", "باتا"] },
  { merchant: "EEHC", category: "فواتير", subCategory: "كهرباء", keywords: ["شركة الكهرباء"] },
  { merchant: "Egypt Gas", category: "فواتير", subCategory: "غاز", keywords: ["بتروتريد", "Petrotrade", "شركة الغاز", "غاز مصر"] },
  { merchant: "HCWW", category: "فواتير", subCategory: "مياه", keywords: ["شركة المياه"] },
  { merchant: "Traffic", category: "خدمات حكومية", subCategory: "مخالفة مرور", keywords: ["مخالفات المرور"] },
  { merchant: "IKEA", category: "سكن", subCategory: "أثاث", keywords: ["ايكيا"] },
  { merchant: "In&Out", category: "سكن", subCategory: "أثاث", keywords: ["إن أند أوت"] },
  { merchant: "Hub Furniture", category: "سكن", subCategory: "أثاث", keywords: ["Hub Furniture", "هاب للاثاث", "هاب فرنيتشر"] },
  { merchant: "Kemitt", category: "سكن", subCategory: "أثاث", keywords: ["Kemitt", "كيميت"] },
  { merchant: "Homzmart", category: "سكن", subCategory: "أثاث", keywords: ["Homzmart", "هومزمارت"] },
  { merchant: "Ariika", category: "سكن", subCategory: "أثاث", keywords: ["بين باج", "اريكا", "Ariika"] },
  { merchant: "Kabbani Furniture", category: "سكن", subCategory: "أثاث", keywords: ["قباني", "قباني للاثاث", "Kabbani Furniture"] },
  { merchant: "General Transport", category: "مواصلات", subCategory: "تاكسي", keywords: ["مكروباص", "تكتك"] },
  { merchant: "General Coffee", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["مقهى"] },
  { merchant: "Gym", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["سمارت جيم", "جولدز جيم"] },
  { merchant: "Dejavu", category: "تسوق", subCategory: "ملابس", keywords: ["ديجافو", "احذية ديجافو"] },
  { merchant: "Pixi", category: "تسوق", subCategory: "ملابس", keywords: ["بيكسي", "بكسي"] },
  { merchant: "Or", category: "تسوق", subCategory: "ملابس", keywords: ["محلات اور"] },
  { merchant: "Dalin", category: "تسوق", subCategory: "ملابس", keywords: ["دالين"] },
  { merchant: "Cottonil", category: "تسوق", subCategory: "ملابس", keywords: ["Cottonil", "قطنيل", "قطونيل"] },
  { merchant: "Embrator", category: "تسوق", subCategory: "ملابس", keywords: ["Embrator"] },
  { merchant: "Mazaya", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["مزايا للعطور"] },
  { merchant: "Faces", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["فيسيز"] },
  { merchant: "Bath & Body Works", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["باث اند بودى ووركس", "باث اند بودي"] },
  { merchant: "The Body Shop", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["ذا بودي شوب", "بودي شوب"] },
  { merchant: "Hedeya", category: "أطفال", subCategory: "هدوم ولعب", keywords: ["محلات هدية"] },
  { merchant: "Mothercare", category: "أطفال", subCategory: "هدوم ولعب", keywords: ["مذر كير", "مذركير"] },
  { merchant: "Toy World", category: "أطفال", subCategory: "هدوم ولعب", keywords: ["توي ورلد", "توي وورلد"] },
  { merchant: "Baraka", category: "صحة", subCategory: "نظارات", keywords: ["بركة للنظارات", "نظارات"] },
  { merchant: "C&Co", category: "صحة", subCategory: "نظارات", keywords: ["سي اند كو"] },
  { merchant: "Magrabi", category: "صحة", subCategory: "نظارات", keywords: ["مغربي للنظارات"] },
  { merchant: "Amin Pet Shop", category: "حيوانات أليفة", subCategory: "مستلزمات", keywords: ["امين بت شوب", "دراي فود"] },
  { merchant: "Pets Egypt", category: "حيوانات أليفة", subCategory: "مستلزمات", keywords: ["بتس ايجيبت"] },
  { merchant: "Ghabbour Auto", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["صيانة غبور", "جي بي اوتو", "GB Auto", "غبور"] },
  { merchant: "Mansour Auto", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["صيانة منصور", "Mansour Automotive", "منصور شيفروليه"] },
  { merchant: "Nacita", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["نصيتا", "ناسيتا"] },
  { merchant: "Fit & Fix", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["فيت و فيكس", "فيت اند فيكس", "Fit & Fix", "كاوتش فيت اند فيكس"] },
  { merchant: "AlMaqarr", category: "عمل", subCategory: "مساحة عمل", keywords: ["وورك سبيس"] },
  { merchant: "Abu Auf", category: "أكل وشرب", subCategory: "سناكس", keywords: ["ابو عوف", "مكسرات ابو عوف", "Abu Auf", "قهوة ابو عوف"] },
  { merchant: "El Mahdes", category: "أكل وشرب", subCategory: "سناكس", keywords: ["مقلة المهندس"] },
  { merchant: "Tradeline", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["تريدلاين", "Apple reseller", "تريد لاين", "Tradeline"] },
  { merchant: "Dream 2000", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["Dream 2000", "دريم الفين", "دريم 2000"] },
  { merchant: "El Safy", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["الصافي ستورز", "El Safy"] },
  { merchant: "EgyptAir", category: "مواصلات", subCategory: "طيران", keywords: ["EGYPTAIR", "تذكرة مصر للطيران", "تذاكر طيران", "مكتب مصر للطيران", "مصر للطيران"] },
  { merchant: "Air Arabia", category: "مواصلات", subCategory: "طيران", keywords: ["العربية للطيران", "طيران العربية"] },
  { merchant: "Travco", category: "ترفيه", subCategory: "سفر", keywords: ["Travco", "رحلات ترافكو", "ترافكو للسياحة", "ترافكو"] },
  { merchant: "Koshary Hend", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري هند"] },
  { merchant: "Koshary Zooba", category: "أكل وشرب", subCategory: "مطعم", keywords: ["زوبى", "زوبة"] },
  { merchant: "Koshary El Omda", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري العمدة"] },
  { merchant: "Koshary Hekaya", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشرى حكاية"] },
  { merchant: "Koshary Karama", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري كرامة"] },
  { merchant: "Koshary Goha", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري جحا"] },
  { merchant: "Koshary El Domyati", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري الدمياطي", "الدمياطي"] },
  { merchant: "Koshary Tom and Basal", category: "أكل وشرب", subCategory: "مطعم", keywords: ["توم اند بصل", "توم وبصل", "طوم وبصل"] },
  { merchant: "Koshary Rigo", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري ريجو", "ريجو"] },
  { merchant: "Koshary El Thawra", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري الثورة"] },
  { merchant: "Koshary Abou Ramy", category: "أكل وشرب", subCategory: "مطعم", keywords: ["ابو رامي", "كشري ابو رامي"] },
  { merchant: "Koshary Hamada", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشرى حماده"] },
  { merchant: "Koshary El Agamy", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري العجمي"] },
  { merchant: "Koshary El Safwa", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري الصفوة"] },
  { merchant: "Koshary Shaker", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري شاكر"] },
  { merchant: "Koshary El Zaeem", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري الزعيم"] },
  { merchant: "Koshary Asmak", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كشري اسماك"] },
  { merchant: "Karam El Sham", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كرم الشام شاورما", "شاورما كرم الشام", "كرم الشام"] },
  { merchant: "Abou Haidar", category: "أكل وشرب", subCategory: "مطعم", keywords: ["أبو حيدر", "شاورما ابو حيدر"] },
  { merchant: "Abu Anas El Syrian", category: "أكل وشرب", subCategory: "مطعم", keywords: ["أبو أنس السوري", "ابو انس"] },
  { merchant: "Semsema", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شاورما سمسمة"] },
  { merchant: "Shawarma El Reem", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شاورما الريم"] },
  { merchant: "Shawarma Shaker", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شاورما شاكر"] },
  { merchant: "Abu Mazen El Syrian", category: "أكل وشرب", subCategory: "مطعم", keywords: ["أبو مازن السوري", "ابو مازن", "شاورما ابو مازن"] },
  { merchant: "Caizo", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كايزو", "سندوتشات كايزو"] },
  { merchant: "Semo Shawarma", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شاورما سيمو"] },
  { merchant: "Shawarma El Emprator", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شاورما الامبراطور"] },
  { merchant: "El Menoufy El Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كباب المنوفي", "المنوفى الكبابجي"] },
  { merchant: "El Refaey Kabab", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كباب الرفاعي"] },
  { merchant: "Hosny El Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["حسني الكبابجي"] },
  { merchant: "Hawaoshi El Rabea", category: "أكل وشرب", subCategory: "مطعم", keywords: ["حواوشى الربع", "حواوشى الربيع"] },
  { merchant: "Wahba El Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبدة وهبة"] },
  { merchant: "Kebda El Fallah", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبده الفلاح"] },
  { merchant: "El Haty", category: "أكل وشرب", subCategory: "مطعم", keywords: ["الحاتى", "كبابجى الحاتى"] },
  { merchant: "El Ezba", category: "أكل وشرب", subCategory: "مطعم", keywords: ["قرية العزبة"] },
  { merchant: "Balbaa Alexandria", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مشويات بلبع", "بلبع", "بلبع الاسكندرية"] },
  { merchant: "Zephyr Sea Food", category: "أكل وشرب", subCategory: "مطعم", keywords: ["اسماك زفير", "سمك زفير"] },
  { merchant: "Hala'et El Asmak", category: "أكل وشرب", subCategory: "مطعم", keywords: ["حلقة السمك"] },
  { merchant: "Aroos El Bahr", category: "أكل وشرب", subCategory: "مطعم", keywords: ["عروس البحر", "سمك عروس البحر"] },
  { merchant: "El Domyati Foul", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فول الدمياطي"] },
  { merchant: "El Tabey El Domyati", category: "أكل وشرب", subCategory: "مطعم", keywords: ["التابعى الدمياطى"] },
  { merchant: "Gad Restaurant", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مطعم جاد"] },
  { merchant: "Al Shabrawy", category: "أكل وشرب", subCategory: "مطعم", keywords: ["شبراوى"] },
  { merchant: "Fattatry El Hoda", category: "أكل وشرب", subCategory: "مطعم", keywords: ["الهدى فطير", "فطاطري الهدى", "فطيرة الهدى"] },
  { merchant: "Fattatry El Hosny", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فطيرة الحسني", "فطاطرى الحسنى"] },
  { merchant: "Fattatry El Nile", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فطاطري النيل", "فطيرة النيل"] },
  { merchant: "Fattatry Master", category: "أكل وشرب", subCategory: "مطعم", keywords: ["ماستر فطير", "فطاطري ماستر"] },
  { merchant: "Dar El Amar", category: "أكل وشرب", subCategory: "مطعم", keywords: ["دار القمر", "مطعم دار القمر"] },
  { merchant: "El Garoub", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فطير الجروب"] },
  { merchant: "Awlad Taqi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["اولاد تقي"] },
  { merchant: "Street Foul Cart", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فطار وعشاء", "عربية الفول", "فول الشارع", "فطار وعشا", "عربية فول وطعمية"] },
  { merchant: "Baladi Coffee Shop", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["قهوه بلدي", "القهوة البلدي", "شاي بلدي", "مشاريب القهوة"] },
  { merchant: "Tuk-Tuk Driver", category: "مواصلات", subCategory: "توكتوك", keywords: ["توك توك", "أجرة توكتوك"] },
  { merchant: "Microbus Rider", category: "مواصلات", subCategory: "ميكروباص", keywords: ["اجرة ميكروباص", "اجرة المشروع"] },
  { merchant: "Local Baker", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["عيش بلدي", "الطابونة", "مخبز بلدي", "فرن بلدي", "عيش فينو", "فرن عيش"] },
  { merchant: "Baladi Butcher", category: "أكل وشرب", subCategory: "لحوم ودواجن", keywords: ["جزار بلدي", "لحمة بلدي", "كيلو لحمة"] },
  { merchant: "Baladi Fishmonger", category: "أكل وشرب", subCategory: "سي فود", keywords: ["محل سمك", "سمك مشوي", "فسخانى", "سمك مقلي", "سماك"] },
  { merchant: "Shisha / Tobacco Spot", category: "تدخين", subCategory: "سجائر", keywords: ["سجاير فرط", "معسل قص"] },
  { merchant: "Local Herbist", category: "أكل وشرب", subCategory: "بقالة", keywords: ["عطارة", "توابل", "عطار", "العطار"] },
  { merchant: "Local Dairy Shop", category: "أكل وشرب", subCategory: "بقالة", keywords: ["كيلو لبن", "محل لبان", "جبنة قديمة", "زبادي بلدي"] },
  { merchant: "Baladi Roastery", category: "أكل وشرب", subCategory: "سناكس", keywords: ["مقله", "محمصات", "لب وسوداني", "مقلة لب", "لب سوبر"] },
  { merchant: "Chicken Vendor", category: "أكل وشرب", subCategory: "لحوم ودواجن", keywords: ["فرارجي", "محل فراخ", "تنظيف فراخ"] },
  { merchant: "Local Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["صيدلية الشارع", "أجزخانة", "اجزاخانة", "دكتور صيدلي"] },
  { merchant: "Public Bath / Hamam", category: "عناية شخصية", subCategory: "حلاق وكوافير", keywords: ["حمام بلدى", "حمام المغربي"] },
  { merchant: "Street Beverage Cart", category: "أكل وشرب", subCategory: "مشروبات", keywords: ["خروب", "عربية عصير قصب", "سوبيا", "تمر هندي", "عصير فريش", "عصير قصب"] },
  { merchant: "Liver Sandwiches Cart", category: "أكل وشرب", subCategory: "مطعم", keywords: ["سندوتش كبدة", "كبدة كلاب", "كبدة الشارع"] },
  { merchant: "Street Sweet Potato Cart", category: "أكل وشرب", subCategory: "مطعم", keywords: ["بطاطا مشوية", "عربية بطاطا", "بطاطا بالبشاميل", "بطاطا"] },
  { merchant: "Street Grilled Corn Cart", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كوز درة", "درة مشوي", "عربية درة"] },
  { merchant: "Local Sweets Shop", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["بسبوسة وهريسة", "هريسة", "شرقي وغربي", "حلويات شرقية"] },
  { merchant: "Local Stationery / Bookshop", category: "تعليم", subCategory: "كتب", keywords: ["مكتبة ادوات مدرسية", "كشكول وقلم", "الفجالة", "مكتبة الفجالة"] },
  { merchant: "Perfume Mixer", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["تركيب عطور", "محل تركيب برفانات", "برفان تركيب", "زيت عطري"] },
  { merchant: "Street Charity / Donation Box", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["جمعية خيرية", "صدقة جارية", "تبرع للمسجد", "شنطة رمضان"] },
  { merchant: "Traditional Midwife / Healer", category: "صحة", subCategory: "عام", keywords: ["شيخ معالج", "علاج طبيعي شعبي", "حجامة"] },
  { merchant: "Traditional Gym", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["جيم شعبي", "صالة حديد", "جيم الحارة"] },
  { merchant: "Water Cart", category: "أكل وشرب", subCategory: "مشروبات", keywords: ["شحن كرت مياه", "كولر مياه", "مبرد مياه", "شربات"] },
  { merchant: "Traditional Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["مقهى الفيشاوي", "الفيشاوى", "قهوة الفيشاوي"] },
  { merchant: "Traditional Alexandria Grill", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبابجى الكنج", "كبابجي الكينج", "مشويات بلدي"] },
  { merchant: "El Malky", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["رز بلبن المالكي", "حلواني المالكي"] },
  { merchant: "Azza Ice Cream", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["جيلاتي عزه"] },
  { merchant: "Saber Patisserie", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["رز بلبن صابر", "حلواني صابر"] },
  { merchant: "Abou Ashraf Seafood", category: "أكل وشرب", subCategory: "مطعم", keywords: ["ابو اشرف", "سمك ابو اشرف", "اسماك ابو اشرف"] },
  { merchant: "Sea Gull Restaurant", category: "أكل وشرب", subCategory: "مطعم", keywords: ["سي جول المكس", "مطعم سي جول", "سي جول"] },
  { merchant: "El Safra Alexandria", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مطعم الصفرة"] },
  { merchant: "Samakmak Alexandria", category: "أكل وشرب", subCategory: "مطعم", keywords: ["سمكمك", "سمكمك الانفوشي", "اسماك سمكمك"] },
  { merchant: "Kadoura Seafood", category: "أكل وشرب", subCategory: "مطعم", keywords: ["قدوره", "اسماك قدورة"] },
  { merchant: "Brown Nose Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["براون نوز كافيه", "Brown Nose", "براون نوز"] },
  { merchant: "3am Mobarez Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["قهوة عم مبارز", "عم مبارز"] },
  { merchant: "Retro Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["ريترو كافيه"] },
  { merchant: "El Fishawy Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["كافيه الفيشاوي"] },
  { merchant: "WE (Telecom Egypt)", category: "فواتير", subCategory: "تليفون", keywords: ["ماي وي", "WE internet", "فاتورة الارضي", "شحن رصيد وي"] },
  { merchant: "Vodafone Egypt", category: "فواتير", subCategory: "تليفون", keywords: ["فودافون ADSL", "كارت فكة فودافون", "فودافون فلتر", "باقة فودافون", "شحن رصيد فودافون"] },
  { merchant: "Etisalat Egypt", category: "فواتير", subCategory: "تليفون", keywords: ["اتصالات ADSL", "شحن اتصالات", "ميكسات اتصالات", "اتصالات VDSL", "باقة اتصالات"] },
  { merchant: "Orange Egypt", category: "فواتير", subCategory: "تليفون", keywords: ["باقة اورنج", "اورنج dsl", "شحن اورنج", "كارت شحن اورنج"] },
  { merchant: "Noor ADSL", category: "فواتير", subCategory: "إنترنت", keywords: ["Noor Internet", "شركة نور"] },
  { merchant: "EEHC (Electricity)", category: "فواتير", subCategory: "كهرباء", keywords: ["عداد الكهرباء", "الشركة القابضة لكهرباء مصر", "EEHC", "شحن كارت الكهرباء"] },
  { merchant: "Egypt Gas (Petrotrade)", category: "فواتير", subCategory: "غاز", keywords: ["تاون جاس", "ثروة بروداكشن", "Town Gas"] },
  { merchant: "HCWW (Water)", category: "فواتير", subCategory: "مياه", keywords: ["HCWW", "عداد المياه", "شركة المياه والصرف الصحى"] },
  { merchant: "Traffic Department", category: "خدمات حكومية", subCategory: "مخالفة مرور", keywords: ["ترخيص السيارة", "فحص السيارة", "بوابة مرور مصر", "نيابة المرور"] },
  { merchant: "Real Estate Tax Authority", category: "خدمات حكومية", subCategory: "ضرائب", keywords: ["مصلحة الضرائب العقارية", "الضرائب العقارية", "الضرائب المصرية", "فاتورة الضرائب"] },
  { merchant: "Egyptian Customs", category: "خدمات حكومية", subCategory: "عام", keywords: ["الجمارك المصرية", "رسوم جمركية", "جمارك المطار", "مصلحة الجمارك"] },
  { merchant: "ElSewedy Electric Bills", category: "فواتير", subCategory: "كهرباء", keywords: ["فاتورة السويدي", "السويدي للكابلات", "السويدى اليكتريك"] },
  { merchant: "Madinet Masr Maintenance", category: "سكن", subCategory: "صيانة", keywords: ["صيانة سراي", "مدينة نصر للاسكان", "وديعة الصيانة", "صيانة تاج سيتي"] },
  { merchant: "TMG Maintenance", category: "سكن", subCategory: "صيانة", keywords: ["صيانة الرحاب", "صيانة مدينتي", "مجموعة طلعت مصطفى", "وديعة صيانة طلعت مصطفى"] },
  { merchant: "MCIT Fees", category: "خدمات حكومية", subCategory: "ضرائب", keywords: ["رسوم الترخيص", "وزارة الاتصالات", "مكلفات الاتصالات"] },
  { merchant: "Uber Egypt", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["Uber Trip", "اوبر ايجيبت"] },
  { merchant: "Careem Egypt", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["رحلة كريم", "توصيلة كريم"] },
  { merchant: "inDrive Egypt", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["تطبيق اندرايف"] },
  { merchant: "DiDi Egypt", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["رحلة ديدي", "تطبيق ديدي"] },
  { merchant: "Swvl Egypt", category: "مواصلات", subCategory: "أتوبيس", keywords: ["رحلة سويفل", "اتوبيس سويفل"] },
  { merchant: "East Delta Bus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["اتوبيس شرق الدلتا"] },
  { merchant: "West Delta Bus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["غرب الدلتا", "اتوبيس غرب الدلتا"] },
  { merchant: "Middle Delta Bus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["وسط الدلتا", "اتوبيس وسط الدلتا"] },
  { merchant: "Upper Egypt Bus", category: "مواصلات", subCategory: "أتوبيس", keywords: ["اتوبيس الوجه القبلي", "الوجه القبلي للنقل", "اتوبيس الصعيد"] },
  { merchant: "Nile Air", category: "مواصلات", subCategory: "طيران", keywords: ["Nile Air", "تذكرة النيل للطيران", "النيل للطيران"] },
  { merchant: "Air Arabia Egypt", category: "مواصلات", subCategory: "طيران", keywords: ["Air Arabia"] },
  { merchant: "FlyEgypt", category: "مواصلات", subCategory: "طيران", keywords: ["طيران فلاي ايجيبت", "FlyEgypt", "فلاي ايجيبت"] },
  { merchant: "Nesma Airlines", category: "مواصلات", subCategory: "طيران", keywords: ["نسما للطيران", "طيران نسما", "Nesma Airlines"] },
  { merchant: "Cairo Aviation", category: "مواصلات", subCategory: "طيران", keywords: ["القاهرة للطيران", "Cairo Aviation", "طيران القاهرة"] },
  { merchant: "Air Cairo", category: "مواصلات", subCategory: "طيران", keywords: ["إير كايرو", "Air Cairo"] },
  { merchant: "LRT Transit", category: "مواصلات", subCategory: "عام", keywords: ["تذكرة LRT", "القطار الكهربائي الخفيف", "القطار الكهربائي"] },
  { merchant: "Cairo Monorail", category: "مواصلات", subCategory: "عام", keywords: ["المونوريل", "مونوريل العاصمة", "مونوريل اكتوبر"] },
  { merchant: "ENR (Egyptian Railways)", category: "مواصلات", subCategory: "قطر", keywords: ["تذكرة القطار", "قطار النوم", "سكك حديد مصر", "الهيئة القومية لسكك حديد مصر"] },
  { merchant: "Cairo Airport Shuttle", category: "مواصلات", subCategory: "عام", keywords: ["اتوبيس مطار القاهرة", "شاتل باص المطار", "تاكسي مطار القاهرة"] },
  { merchant: "Raye7", category: "مواصلات", subCategory: "أوبر/كريم", keywords: ["تطبيق رايح"] },
  { merchant: "Mobil Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["Mobil Station", "بنزينة موبيل", "تفويلة موبيل"] },
  { merchant: "Shell Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["بنزينة شيل", "Shell Station", "تفويلة شيل"] },
  { merchant: "Total Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["Total Station", "تفويلة توتال", "بنزينة توتال"] },
  { merchant: "Chillout Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["Chillout", "تفويلة تشيل اوت", "بنزينة تشيل اوت", "تشيل اوت"] },
  { merchant: "Wataniya Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["Wataniya Station", "تفويلة وطنية"] },
  { merchant: "Emarat Misr Gas", category: "مواصلات", subCategory: "بنزين", keywords: ["Emarat Misr", "بنزينة امارات مصر"] },
  { merchant: "Taqa Gas Station", category: "مواصلات", subCategory: "بنزين", keywords: ["Taqa Petroleum", "تفويلة طاقة", "بنزينة طاقة"] },
  { merchant: "Misr Petroleum", category: "مواصلات", subCategory: "بنزين", keywords: ["تفويلة مصر للبترول", "مصر للبترول", "بنزينة مصر للبترول"] },
  { merchant: "Coop Petroleum", category: "مواصلات", subCategory: "بنزين", keywords: ["الجمعية التعاونية للبترول", "بنزينة الجمعية", "Coop Station", "التعاون للبترول"] },
  { merchant: "Carrefour Egypt", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ماي كلوب كارفور"] },
  { merchant: "BIM Egypt", category: "أكل وشرب", subCategory: "بقالة", keywords: ["ماركت بيم"] },
  { merchant: "Oscar Grand Stores", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Oscar Market"] },
  { merchant: "Fathalla Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Fathalla"] },
  { merchant: "Gourmet Egypt", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Gourmet Egypt"] },
  { merchant: "Abu Ashara Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Abu Ashara"] },
  { merchant: "El Hawary Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["سوبرماركت الهواري"] },
  { merchant: "Gomla Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Gomla Market", "جملة ماركت", "فتحي الله جملة ماركت"] },
  { merchant: "Royal House", category: "أكل وشرب", subCategory: "بقالة", keywords: ["رويال هاوس", "Royal House"] },
  { merchant: "Alfa Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Alfa Market", "الفا ماركت"] },
  { merchant: "Rabbit Market", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Rabbit Market", "Rabbit App"] },
  { merchant: "InstaShop Egypt", category: "أكل وشرب", subCategory: "بقالة", keywords: ["InstaShop"] },
  { merchant: "Talabat Mart", category: "أكل وشرب", subCategory: "بقالة", keywords: ["Talabat Mart", "طلبات مارت", "tMart"] },
  { merchant: "Noon Daily", category: "أكل وشرب", subCategory: "بقالة", keywords: ["بقالة نون", "نون ديلي", "Noon Daily"] },
  { merchant: "Talabat Egypt", category: "أكل وشرب", subCategory: "دليفري", keywords: ["اوردر طلبات"] },
  { merchant: "Elmenus", category: "أكل وشرب", subCategory: "دليفري", keywords: ["elmenus", "تطبيق المنيوز", "المنيوس", "المنيوز"] },
  { merchant: "Mrsool Egypt", category: "أكل وشرب", subCategory: "دليفري", keywords: ["تطبيق مرسول", "مرسول", "mrsool", "مرسول مصر"] },
  { merchant: "Burger King Egypt", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["برجر كينغ"] },
  { merchant: "Hardee's Egypt", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Hardees", "مطعم هارديز"] },
  { merchant: "Papa John's Egypt", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["بابا جونز بيتزا", "Papa Johns"] },
  { merchant: "Kansas Fried Chicken", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Kansas Fried Chicken", "كانساس", "كانزاس"] },
  { merchant: "Chicken Tikka", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Tikka", "تيكا", "تشيكن تيكا"] },
  { merchant: "Texas Chicken", category: "أكل وشرب", subCategory: "وجبات سريعة", keywords: ["Texas Chicken", "تكساس فرايد تشيكن", "تكساس تشيكن"] },
  { merchant: "Gad", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فول جاد"] },
  { merchant: "El Shabrawy", category: "أكل وشرب", subCategory: "مطعم", keywords: ["فول الشبراوي"] },
  { merchant: "El Menoufey Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبابجى المنوفى"] },
  { merchant: "El Basha Kababgi", category: "أكل وشرب", subCategory: "مطعم", keywords: ["كبابجي الباشا", "الباشا الكبابجي"] },
  { merchant: "Anas El Demeshky", category: "أكل وشرب", subCategory: "مطعم", keywords: ["انس الدمشقي"] },
  { merchant: "Ibn El Sham", category: "أكل وشرب", subCategory: "مطعم", keywords: ["ابن الشام", "مطعم ابن الشام"] },
  { merchant: "Aroos El Demeshq", category: "أكل وشرب", subCategory: "مطعم", keywords: ["عروس الدمشق", "شاورما عروس الدمشق"] },
  { merchant: "Taza Restaurant", category: "أكل وشرب", subCategory: "مطعم", keywords: ["مطعم تازا", "Taza", "تازا"] },
  { merchant: "Zooba", category: "أكل وشرب", subCategory: "مطعم", keywords: ["Zooba", "زوبا", "مطعم زوبا"] },
  { merchant: "Nola Cupcakes", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Nola"] },
  { merchant: "Coppermelt", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Coppermelt", "كوبر ميلت"] },
  { merchant: "Tortina", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Tortina", "تورتينا"] },
  { merchant: "Twinkies Bakery", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Twinkies"] },
  { merchant: "Costa Coffee Egypt", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["Costa Coffee"] },
  { merchant: "Beano's Cafe", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["Beano's"] },
  { merchant: "Espresso Lab Egypt", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["Espresso Lab"] },
  { merchant: "TBS (The Bakery Shop)", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["TBS"] },
  { merchant: "B.Laban", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["ب-لبن", "قشطوزة", "ب لبن", "B.Laban", "بلبن"] },
  { merchant: "Cinnabon Egypt", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["سينابون رول", "Cinnabon"] },
  { merchant: "Dunkin' Donuts Egypt", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Dunkin Donuts"] },
  { merchant: "Krispy Kreme Egypt", category: "أكل وشرب", subCategory: "مخبوزات", keywords: ["Krispy Kreme"] },
  { merchant: "Caribou Coffee Egypt", category: "أكل وشرب", subCategory: "قهوة وكافيه", keywords: ["كاريبو كوفي", "Caribou Coffee"] },
  { merchant: "Jumia Egypt", category: "تسوق", subCategory: "عام", keywords: ["جوميا باي", "جوميا مصر"] },
  { merchant: "Noon Egypt", category: "تسوق", subCategory: "عام", keywords: ["نون مصر", "اكواد نون"] },
  { merchant: "2B Egypt", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["2B Egypt", "2B computer"] },
  { merchant: "Elghazawy", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["الغزاوى", "محلات الغزاوي", "Elghazawy"] },
  { merchant: "Sharaf DG Egypt", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["شرف دي جي", "Sharaf DG"] },
  { merchant: "Ravin Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Ravin"] },
  { merchant: "Max Fashion Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Max Fashion"] },
  { merchant: "Splash Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Splash"] },
  { merchant: "Pixi Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Pixi"] },
  { merchant: "Or Shop", category: "تسوق", subCategory: "ملابس", keywords: ["Or shop"] },
  { merchant: "Dice Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Dice underwear"] },
  { merchant: "Mobaco Cottons", category: "تسوق", subCategory: "ملابس", keywords: ["موباكو", "Mobaco"] },
  { merchant: "Beymen Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["بيمن", "Beymen"] },
  { merchant: "American Eagle Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["امريكان ايجل", "American Eagle"] },
  { merchant: "Pull & Bear Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["بول اند بير", "Pull & Bear"] },
  { merchant: "Bershka Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Bershka", "بيرشكا"] },
  { merchant: "Stradivarius Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Stradivarius", "ستراديفاريوس"] },
  { merchant: "Marks & Spencer Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Marks & Spencer", "ماركس اند سبنسر"] },
  { merchant: "Timberland Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Timberland", "تمبرلاند"] },
  { merchant: "Clarks Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["Clarks", "كلاركس"] },
  { merchant: "Crocs Egypt", category: "تسوق", subCategory: "ملابس", keywords: ["كروكس", "Crocs"] },
  { merchant: "Fortune Cosmetics", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["Fortune Cosmetics"] },
  { merchant: "Bath & Body Works Egypt", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["Bath & Body Works"] },
  { merchant: "The Body Shop Egypt", category: "عناية شخصية", subCategory: "مستحضرات وعناية", keywords: ["The Body Shop"] },
  { merchant: "IKEA Egypt", category: "سكن", subCategory: "أثاث", keywords: ["IKEA"] },
  { merchant: "El Sewedy Electrometer", category: "تسوق", subCategory: "أجهزة إلكترونية", keywords: ["عداد السويدي"] },
  { merchant: "Mothercare Egypt", category: "أطفال", subCategory: "هدوم ولعب", keywords: ["Mothercare"] },
  { merchant: "Toy World Egypt", category: "أطفال", subCategory: "هدوم ولعب", keywords: ["Toy World"] },
  { merchant: "Baraka Optics", category: "صحة", subCategory: "نظارات", keywords: ["نظارات بركة"] },
  { merchant: "C&Co Optics", category: "صحة", subCategory: "نظارات", keywords: ["C&Co"] },
  { merchant: "Shahid VIP", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["Shahid VIP", "شاهد VIP"] },
  { merchant: "beIN Sports Egypt", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["beIN Sports"] },
  { merchant: "Disney+ Egypt", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["ديزني بلس", "Disney+", "ديزني+"] },
  { merchant: "Apple TV+", category: "اشتراكات", subCategory: "منصات مشاهدة", keywords: ["Apple TV", "ابل تي في"] },
  { merchant: "Steam Games", category: "ترفيه", subCategory: "ألعاب", keywords: ["Steam Games"] },
  { merchant: "PlayStation Network (PSN)", category: "ترفيه", subCategory: "ألعاب", keywords: ["playstation network", "PlayStation Store"] },
  { merchant: "Xbox Live", category: "ترفيه", subCategory: "ألعاب", keywords: ["Microsoft Xbox", "اكس بوكس", "xbox live"] },
  { merchant: "Epic Games", category: "ترفيه", subCategory: "ألعاب", keywords: ["إيبك جيمز", "Epic Store", "epic games"] },
  { merchant: "Nintendo eShop", category: "ترفيه", subCategory: "ألعاب", keywords: ["نينتندو", "nintendo eshop"] },
  { merchant: "Vox Cinemas Egypt", category: "ترفيه", subCategory: "سينما", keywords: ["Vox Cinemas"] },
  { merchant: "Sun City Cinema", category: "ترفيه", subCategory: "سينما", keywords: ["Sun City Cinema", "سينما صن سيتى"] },
  { merchant: "Magic Planet Egypt", category: "ترفيه", subCategory: "خروجة", keywords: ["Magic Planet"] },
  { merchant: "Al-Ahly Club", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["اشتراك نادي الاهلي", "نادي الاهلي", "الاهلي الجزيرة"] },
  { merchant: "Zamalek Club", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["اشتراك نادي الزمالك", "الزمالك ميت عقبة", "نادي الزمالك"] },
  { merchant: "Gezira Sporting Club", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["نادي الجزيرة", "نادى الجزيرة الرياضى", "Gezira Club"] },
  { merchant: "Shooting Club", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["نادي الصيد", "نادي الصيد بالدقي", "Shooting Club"] },
  { merchant: "Wadi Degla Club", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["Wadi Degla", "وادي دجلة", "نادى وادى دجلة"] },
  { merchant: "Misr Pharmacies", category: "صحة", subCategory: "صيدلية", keywords: ["صيدلية مصر", "صيدليات مصر"] },
  { merchant: "Abu Ali Pharmacy", category: "صحة", subCategory: "صيدلية", keywords: ["صيدلية ابو علي"] },
  { merchant: "Dar Al Fouad Hospital", category: "صحة", subCategory: "مستشفى", keywords: ["دار الفؤاد", "Dar Al Fouad", "مستشفى دار الفؤاد"] },
  { merchant: "Al Salam International", category: "صحة", subCategory: "مستشفى", keywords: ["السلام الدولي", "مستشفى السلام الدولي", "Al Salam Hospital"] },
  { merchant: "Saudi German Hospital", category: "صحة", subCategory: "مستشفى", keywords: ["SGH Egypt", "السعودي الالماني", "المستشفى السعودي الالماني"] },
  { merchant: "Prime Clinics", category: "صحة", subCategory: "دكتور", keywords: ["Prime Clinics", "برايم كلينكس"] },
  { merchant: "Alfa Labs", category: "صحة", subCategory: "تحاليل", keywords: ["الفا للاشعة والتحاليل", "Alfa Labs", "معامل الفا"] },
  { merchant: "Al Borg Laboratories", category: "صحة", subCategory: "تحاليل", keywords: ["معمل البرج", "Al Borg Lab", "البرج للتحاليل"] },
  { merchant: "Al Mokhtabar", category: "صحة", subCategory: "تحاليل", keywords: ["معمل المختبر", "المختبر للتحاليل", "Al Mokhtabar"] },
  { merchant: "Cairo Lab", category: "صحة", subCategory: "تحاليل", keywords: ["Cairo Lab", "كايرو لاب"] },
  { merchant: "Egyptian Food Bank", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["Egyptian Food Bank"] },
  { merchant: "Mersal Foundation", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["مؤسسة مرسال"] },
  { merchant: "Ahl Masr Foundation", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["اهل مصر", "Ahl Masr", "مؤسسة اهل مصر"] },
  { merchant: "Egyptian Clothing Bank", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["بنك الكساء المصري", "Clothing Bank", "بنك الكساء"] },
  { merchant: "Tahya Misr Fund", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["Tahya Misr", "صندوق تحيا مصر", "تحيا مصر"] },
  { merchant: "Beit Al-Zakat", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["بيت الزكاة المصري", "بيت الزكاة والصدقات المصرى", "بيت الزكاة والصدقات"] },
  { merchant: "500500 Hospital", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["مستشفى ٥٠٠٥٠٠", "500500", "مستشفى الاورام الجديد ٥٠٠٥٠٠"] },
  { merchant: "Egyptian Cure Bank", category: "هدايا وصدقات", subCategory: "صدقة/تبرع", keywords: ["بنك الشفاء المصري", "بنك الشفاء", "Cure Bank"] },
  { merchant: "AlMaqarr Coworking", category: "عمل", subCategory: "مساحة عمل", keywords: ["مساحة عمل المقر"] },
  { merchant: "Makanak Coworking", category: "عمل", subCategory: "مساحة عمل", keywords: ["مكاتب مكانك"] },
  { merchant: "Nacita Auto Care", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["Nacita"] },
  { merchant: "Ezz Elarab", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["صيانة عز العرب", "عز العرب", "Ezz Elarab", "عزالعرب"] },
  { merchant: "Abou Ghaly Motors", category: "مواصلات", subCategory: "صيانة عربية", keywords: ["ابو غالى", "Abou Ghaly Motors", "ابو غالي موتورز"] },
  { merchant: "GitHub", category: "اشتراكات", subCategory: "برمجيات", keywords: ["جيت هاب كوبايلوت", "github", "جيت هاب", "github copilot"] },
  { merchant: "OpenAI", category: "اشتراكات", subCategory: "برمجيات", keywords: ["openai billing"] },
  { merchant: "Google One / Storage", category: "اشتراكات", subCategory: "برمجيات", keywords: ["جوجل درايف", "google storage", "google one", "جوجل ون"] },
  { merchant: "Google Workspace", category: "اشتراكات", subCategory: "برمجيات", keywords: ["google workspace", "GOOGLE GSUITE", "gsuite", "جوجل ورك سبيس"] },
  { merchant: "Google Cloud Platform", category: "عمل", subCategory: "استضافة", keywords: ["جوجل كلاود"] },
  { merchant: "Amazon Web Services (AWS)", category: "عمل", subCategory: "استضافة", keywords: ["اي دبليو اس", "AWS BILLING", "amazon web services"] },
  { merchant: "Microsoft Azure", category: "عمل", subCategory: "استضافة", keywords: ["مايكروسوفت ازور"] },
  { merchant: "Microsoft 365", category: "اشتراكات", subCategory: "برمجيات", keywords: ["مايكروسوفت ٣٦٥", "office 365", "msofficestore"] },
  { merchant: "Vercel Cloud", category: "عمل", subCategory: "استضافة", keywords: ["فيرسيل", "vercel"] },
  { merchant: "Netlify", category: "عمل", subCategory: "استضافة", keywords: ["نتليفاي", "netlify"] },
  { merchant: "DigitalOcean", category: "عمل", subCategory: "استضافة", keywords: ["digitalocean", "ديجيتال اوشن"] },
  { merchant: "Hetzner Online", category: "عمل", subCategory: "استضافة", keywords: ["Hetzner Online", "هتزنر", "hetzner"] },
  { merchant: "Hostinger", category: "عمل", subCategory: "استضافة", keywords: ["hostinger", "هوستنجر"] },
  { merchant: "GoDaddy", category: "عمل", subCategory: "استضافة", keywords: ["جو دادي", "godaddy"] },
  { merchant: "Namecheap", category: "عمل", subCategory: "استضافة", keywords: ["namecheap", "نيم شيب"] },
  { merchant: "Adobe Creative Cloud", category: "اشتراكات", subCategory: "برمجيات", keywords: ["adobe", "creative cloud", "ادوبي"] },
  { merchant: "Canva", category: "اشتراكات", subCategory: "برمجيات", keywords: ["كانفا", "canva"] },
  { merchant: "Figma", category: "اشتراكات", subCategory: "برمجيات", keywords: ["فيجما", "figma"] },
  { merchant: "Notion Labs", category: "اشتراكات", subCategory: "برمجيات", keywords: ["notion", "نوشن"] },
  { merchant: "Slack Technologies", category: "اشتراكات", subCategory: "برمجيات", keywords: ["سلاك", "slack"] },
  { merchant: "Apple Developer", category: "اشتراكات", subCategory: "برمجيات", keywords: ["ابل ديفيلوبر", "apple developer"] },
  { merchant: "Google Play Console", category: "اشتراكات", subCategory: "برمجيات", keywords: ["جوجل بلاي كونسول", "google play console"] },
  { merchant: "Cloudflare", category: "اشتراكات", subCategory: "برمجيات", keywords: ["كلاود فلير", "cloudflare"] },
  { merchant: "Shopify", category: "اشتراكات", subCategory: "برمجيات", keywords: ["shopify", "شوبيفاي"] },
  { merchant: "Midjourney AI", category: "اشتراكات", subCategory: "برمجيات", keywords: ["ميدجورني", "midjourney"] },
  { merchant: "LinkedIn Premium", category: "اشتراكات", subCategory: "برمجيات", keywords: ["linkedin premium", "لينكد ان بريميوم"] },
  { merchant: "Mailchimp", category: "اشتراكات", subCategory: "برمجيات", keywords: ["mailchimp", "ميل شيمب"] },
  { merchant: "SendGrid", category: "اشتراكات", subCategory: "برمجيات", keywords: ["sendgrid", "سيند جريد"] },
  { merchant: "Heroku", category: "عمل", subCategory: "استضافة", keywords: ["heroku", "هيروكو"] },
  { merchant: "Udacity", category: "تعليم", subCategory: "كورسات", keywords: ["يوداسيتي", "udacity"] },
  { merchant: "British Council Egypt", category: "تعليم", subCategory: "كورسات", keywords: ["المجلس البريطاني", "كورس انجليزي بريتش كاونسل", "british council"] },
  { merchant: "AMIDEAST Egypt", category: "تعليم", subCategory: "كورسات", keywords: ["اميديست مصر", "amideast", "اميديست"] },
  { merchant: "Berlitz Egypt", category: "تعليم", subCategory: "كورسات", keywords: ["berlitz", "بيرلتز", "مراكز بيرلتز"] },
  { merchant: "American University in Cairo (AUC)", category: "تعليم", subCategory: "كورسات", keywords: ["مصاريف AUC", "الجامعة الامريكية", "AUC", "الجامعة الامريكية بالقاهرة"] },
  { merchant: "German University in Cairo (GUC)", category: "تعليم", subCategory: "كورسات", keywords: ["GUC", "الجامعه الالمانيه", "الجامعة الالمانية بالقاهرة", "مصاريف GUC"] },
  { merchant: "British University in Egypt (BUE)", category: "تعليم", subCategory: "كورسات", keywords: ["الجامعة البريطانية", "مصاريف BUE", "BUE"] },
  { merchant: "Arab Academy (AASTMT)", category: "تعليم", subCategory: "كورسات", keywords: ["الاكاديميه البحريه", "AAST", "مصاريف الاكاديمية", "AASTMT"] },
  { merchant: "Cairo University", category: "تعليم", subCategory: "كورسات", keywords: ["جامعه القاهره", "مصاريف جامعة القاهرة"] },
  { merchant: "Ain Shams University", category: "تعليم", subCategory: "كورسات", keywords: ["جامعة عين شمس", "مصاريف جامعة عين شمس"] },
  { merchant: "Helwan University", category: "تعليم", subCategory: "كورسات", keywords: ["جامعه حلوان", "مصاريف جامعة حلوان"] },
  { merchant: "Alex University", category: "تعليم", subCategory: "كورسات", keywords: ["مصاريف جامعة الاسكندرية", "جامعه الاسكندريه"] },
  { merchant: "Gold's Gym Egypt", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["اشتراك جولدز جيم", "golds gym"] },
  { merchant: "Smart Gym", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["smart gym", "اشتراك سمارت جيم"] },
  { merchant: "H2O Gym", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["h2o gym", "اشتراك h2o", "اتش تو او جيم"] },
  { merchant: "Hers Gym", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["اشتراك هيرز", "هيرز جيم", "hers gym"] },
  { merchant: "UFC Gym Egypt", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["يو اف سي جيم", "ufc gym", "اشتراك ufc"] },
  { merchant: "BeFit Egypt", category: "ترفيه", subCategory: "رياضة وجيم", keywords: ["befit", "بي فيت", "اشتراك بي فيت"] },
  { merchant: "Booking.com Egypt", category: "ترفيه", subCategory: "سفر", keywords: ["بوكينج", "حجز بوكينج"] },
  { merchant: "Airbnb Egypt", category: "ترفيه", subCategory: "سفر", keywords: ["اير بي ان بي", "airbnb", "حجز اير بي ان بي"] },
  { merchant: "Expedia Egypt", category: "ترفيه", subCategory: "سفر", keywords: ["اكسبيديا", "expedia", "حجز اكسبيديا"] },
  { merchant: "Aman Installments", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["قسط امان", "كارت امان"] },
  { merchant: "getGo", category: "أقساط وفوايد", subCategory: "أقساط", keywords: ["جيت جو", "قسط جيت جو", "تقسيط جيت جو", "getgo"] },
];
