/**
 * Words and short phrases that name a subcategory, and so a category. Read by the rule
 * engine's subcategory layers (`subcat_trigram`, `subcat_bigram`, `subcat_unigram`) and by
 * `refineSubCategory`. Part of the one lexicon (`api/lib/lexicon/index.ts`); every entry is
 * checked against the taxonomy by `api/lib/lexicon/lexicon.integrity.test.ts`.
 */
export const SUB_CATEGORY_MAP: Record<
  string,
  { category: string; subCategory: string }
> = {
  // Food subcategories
  كنتاكي: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  ماكدونالدز: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  هارديز: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  "برجر كينج": { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  "بيتزا هت": { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  شاورما: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  سندوتشات: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  كشري: { category: "أكل وشرب", subCategory: "مطعم" },
  مطعم: { category: "أكل وشرب", subCategory: "مطعم" },
  اكل: { category: "أكل وشرب", subCategory: "عام" },
  أكل: { category: "أكل وشرب", subCategory: "عام" },
  اكلت: { category: "أكل وشرب", subCategory: "مطعم" },
  أكلت: { category: "أكل وشرب", subCategory: "مطعم" },
  غدا: { category: "أكل وشرب", subCategory: "مطعم" },
  غداء: { category: "أكل وشرب", subCategory: "مطعم" },
  عشا: { category: "أكل وشرب", subCategory: "مطعم" },
  عشاء: { category: "أكل وشرب", subCategory: "مطعم" },
  فطار: { category: "أكل وشرب", subCategory: "مطعم" },
  إفطار: { category: "أكل وشرب", subCategory: "مطعم" },
  دليفري: { category: "أكل وشرب", subCategory: "دليفري" },
  "تيك اواي": { category: "أكل وشرب", subCategory: "دليفري" },
  قهوه: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  قهوة: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  قهوجي: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  قهو: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  نسكافيه: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  كافيه: { category: "أكل وشرب", subCategory: "قهوة وكافيه" },
  بقاله: { category: "أكل وشرب", subCategory: "بقالة" },
  بقال: { category: "أكل وشرب", subCategory: "بقالة" },
  سمك: { category: "أكل وشرب", subCategory: "سي فود" },
  جمبري: { category: "أكل وشرب", subCategory: "سي فود" },
  فشار: { category: "أكل وشرب", subCategory: "سناكس" },
  سواق: { category: "مواصلات", subCategory: "تاكسي" },
  سائق: { category: "مواصلات", subCategory: "تاكسي" },
  فراخ: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  لحمه: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  عجل: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  خروف: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  خرفان: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  جزار: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  ذبيحه: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  اضحيه: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  كندوز: { category: "أكل وشرب", subCategory: "لحوم ودواجن" },
  فرن: { category: "أكل وشرب", subCategory: "مخبوزات" },
  مخبز: { category: "أكل وشرب", subCategory: "مخبوزات" },
  عيش: { category: "أكل وشرب", subCategory: "مخبوزات" },
  فول: { category: "أكل وشرب", subCategory: "مطعم" },
  طعميه: { category: "أكل وشرب", subCategory: "مطعم" },
  طعمية: { category: "أكل وشرب", subCategory: "مطعم" },
  كبده: { category: "أكل وشرب", subCategory: "مطعم" },
  كبدة: { category: "أكل وشرب", subCategory: "مطعم" },
  حواوشي: { category: "أكل وشرب", subCategory: "مطعم" },
  كريب: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  عصير: { category: "أكل وشرب", subCategory: "مشروبات" },
  قصب: { category: "أكل وشرب", subCategory: "مشروبات" },
  بيتزا: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  سوشي: { category: "أكل وشرب", subCategory: "سي فود" },
  برجر: { category: "أكل وشرب", subCategory: "وجبات سريعة" },
  كشك: { category: "أكل وشرب", subCategory: "سناكس" },
  // Transport subcategories
  اوبر: { category: "مواصلات", subCategory: "أوبر/كريم" },
  كريم: { category: "مواصلات", subCategory: "أوبر/كريم" },
  مترو: { category: "مواصلات", subCategory: "مترو" },
  اتوبيس: { category: "مواصلات", subCategory: "أتوبيس" },
  باص: { category: "مواصلات", subCategory: "أتوبيس" },
  تكسي: { category: "مواصلات", subCategory: "تاكسي" },
  تاكسي: { category: "مواصلات", subCategory: "تاكسي" },
  بنزين: { category: "مواصلات", subCategory: "بنزين" },
  بنزينه: { category: "مواصلات", subCategory: "بنزين" },
  بنزينة: { category: "مواصلات", subCategory: "بنزين" },
  تفويله: { category: "مواصلات", subCategory: "بنزين" },
  ركنه: { category: "مواصلات", subCategory: "ركنة" },
  جراج: { category: "مواصلات", subCategory: "ركنة" },
  توكتوك: { category: "مواصلات", subCategory: "توكتوك" },
  "صيانه عربيه": { category: "مواصلات", subCategory: "صيانة عربية" },
  عربيه: { category: "مواصلات", subCategory: "صيانة عربية" },
  عربية: { category: "مواصلات", subCategory: "صيانة عربية" },
  ميكروباص: { category: "مواصلات", subCategory: "أتوبيس" },
  سويفل: { category: "مواصلات", subCategory: "أتوبيس" },
  "ان درايف": { category: "مواصلات", subCategory: "أوبر/كريم" },
  اندرايف: { category: "مواصلات", subCategory: "أوبر/كريم" },
  ديدي: { category: "مواصلات", subCategory: "أوبر/كريم" },
  تذكره: { category: "مواصلات", subCategory: "مترو" },
  تذكرة: { category: "مواصلات", subCategory: "مترو" },
  تيكت: { category: "مواصلات", subCategory: "مترو" },
  // "مشروع" removed — means "project/business" in Egyptian Arabic, NOT a bus.
  // Was causing "دفعت في المشروع 5000" → مواصلات/أتوبيس (critical misclassification).
  // Bug #10 fix: "قطر" means the country Qatar, not a train.
  // Use "قطار" (train) instead as the keyword.
  قطار: { category: "مواصلات", subCategory: "قطر" },
  // Bills subcategories
  كهربا: { category: "فواتير", subCategory: "كهرباء" },
  كهرباء: { category: "فواتير", subCategory: "كهرباء" },
  نور: { category: "فواتير", subCategory: "كهرباء" },
  ميه: { category: "فواتير", subCategory: "مياه" },
  مياه: { category: "فواتير", subCategory: "مياه" },
  غاز: { category: "فواتير", subCategory: "غاز" },
  نت: { category: "فواتير", subCategory: "إنترنت" },
  راوتر: { category: "فواتير", subCategory: "إنترنت" },
  شحن: { category: "فواتير", subCategory: "شحن رصيد" },
  رصيد: { category: "فواتير", subCategory: "شحن رصيد" },
  قسط: { category: "أقساط وفوايد", subCategory: "أقساط" },
  اقساط: { category: "أقساط وفوايد", subCategory: "أقساط" },
  تامين: { category: "فواتير", subCategory: "تأمين" },
  ضرايب: { category: "خدمات حكومية", subCategory: "ضرائب" },
  باقه: { category: "فواتير", subCategory: "إنترنت" },
  باقة: { category: "فواتير", subCategory: "إنترنت" },
  // Home subcategories
  سكن: { category: "سكن", subCategory: "عام" },
  ايجار: { category: "سكن", subCategory: "إيجار" },
  الايجار: { category: "سكن", subCategory: "إيجار" },
  إيجار: { category: "سكن", subCategory: "إيجار" },
  تشطيب: { category: "سكن", subCategory: "صيانة" },
  مقاول: { category: "سكن", subCategory: "صيانة" },
  صيانة: { category: "سكن", subCategory: "صيانة" },
  سباك: { category: "سكن", subCategory: "صيانة" },
  كهربائي: { category: "سكن", subCategory: "صيانة" },
  نقاش: { category: "سكن", subCategory: "صيانة" },
  نجار: { category: "سكن", subCategory: "صيانة" },
  شغاله: { category: "سكن", subCategory: "نظافة" },
  منظفات: { category: "سكن", subCategory: "منظفات" },
  غساله: { category: "سكن", subCategory: "أجهزة منزلية" },
  تلاجه: { category: "سكن", subCategory: "أجهزة منزلية" },
  بواب: { category: "سكن", subCategory: "صيانة" },
  زبال: { category: "سكن", subCategory: "صيانة" },
  // Shopping subcategories
  هدوم: { category: "تسوق", subCategory: "ملابس" },
  لبس: { category: "تسوق", subCategory: "ملابس" },
  تيشيرت: { category: "تسوق", subCategory: "ملابس" },
  بنطلون: { category: "تسوق", subCategory: "ملابس" },
  كاب: { category: "تسوق", subCategory: "ملابس" },
  قميص: { category: "تسوق", subCategory: "ملابس" },
  جاكيت: { category: "تسوق", subCategory: "ملابس" },
  فستان: { category: "تسوق", subCategory: "ملابس" },
  شراب: { category: "تسوق", subCategory: "ملابس" },
  بلوفر: { category: "تسوق", subCategory: "ملابس" },
  "سويت شيرت": { category: "تسوق", subCategory: "ملابس" },
  شوز: { category: "تسوق", subCategory: "أحذية" },
  صندل: { category: "تسوق", subCategory: "أحذية" },
  شبشب: { category: "تسوق", subCategory: "أحذية" },
  "هاف بوت": { category: "تسوق", subCategory: "أحذية" },
  بوت: { category: "تسوق", subCategory: "أحذية" },
  // Bug #9 fix: "موبايل" alone is ambiguous — can be shopping OR recharge.
  // Removed from SUB_CATEGORY_MAP; handled contextually in the classification loop instead.
  // موبايل: { category: "تسوق", subCategory: "أجهزة إلكترونية" }, ← DELETED
  "تليفون جديد": { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  "موبايل جديد": { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  "موبايل مستعمل": { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  "لاب توب": { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  ايفون: { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  شاحن: { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  سلك: { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  سماعه: { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  سماعة: { category: "تسوق", subCategory: "أجهزة إلكترونية" },
  كفر: { category: "تسوق", subCategory: "إكسسوارات" },
  جراب: { category: "تسوق", subCategory: "إكسسوارات" },
  كوتشي: { category: "تسوق", subCategory: "أحذية" },
  جزمه: { category: "تسوق", subCategory: "أحذية" },
  شوبينج: { category: "تسوق", subCategory: "عام" },
  حلاق: { category: "عناية شخصية", subCategory: "حلاق وكوافير" },
  كوافير: { category: "عناية شخصية", subCategory: "حلاق وكوافير" },
  مغسله: { category: "عناية شخصية", subCategory: "عام" },
  مغسلة: { category: "عناية شخصية", subCategory: "عام" },
  // Bug #8 fix: كارفور removed from SUB_CATEGORY_MAP (dead code — MERCHANT_REGISTRY at L251
  // always runs first and overrides this. Having two conflicting entries is misleading).
  // كارفور: { category: "تسوق", subCategory: "سوبر ماركت" }, ← DELETED
  سوبرماركت: { category: "أكل وشرب", subCategory: "بقالة" },
  "سوبر ماركت": { category: "أكل وشرب", subCategory: "بقالة" },
  // Health subcategories
  دكتور: { category: "صحة", subCategory: "دكتور" },
  كشف: { category: "صحة", subCategory: "دكتور" },
  صيدليه: { category: "صحة", subCategory: "صيدلية" },
  صيدلية: { category: "صحة", subCategory: "صيدلية" },
  دوا: { category: "صحة", subCategory: "صيدلية" },
  // stt-corrections rewrites "دوا" and "علاج" to "أدوية", which normalizes to "ادويه" —
  // a form no dictionary listed, so a correction was turning a word the system knew
  // into one it did not. Every surface form is now covered directly.
  دواء: { category: "صحة", subCategory: "صيدلية" },
  ادويه: { category: "صحة", subCategory: "صيدلية" },
  ادوية: { category: "صحة", subCategory: "صيدلية" },
  أدوية: { category: "صحة", subCategory: "صيدلية" },
  تحاليل: { category: "صحة", subCategory: "تحاليل" },
  تحليل: { category: "صحة", subCategory: "تحاليل" },
  مستشفى: { category: "صحة", subCategory: "مستشفى" },
  اسنان: { category: "صحة", subCategory: "أسنان" },
  علاج: { category: "صحة", subCategory: "صيدلية" },
  روشته: { category: "صحة", subCategory: "صيدلية" },
  // Education subcategories
  مدرسه: { category: "تعليم", subCategory: "مدرسة" },
  جامعه: { category: "تعليم", subCategory: "جامعة" },
  كورس: { category: "تعليم", subCategory: "كورسات" },
  درس: { category: "تعليم", subCategory: "دروس خصوصية" },
  دروس: { category: "تعليم", subCategory: "دروس خصوصية" },
  // Entertainment subcategories
  سينما: { category: "ترفيه", subCategory: "سينما" },
  جيم: { category: "ترفيه", subCategory: "رياضة وجيم" },
  نادي: { category: "ترفيه", subCategory: "رياضة وجيم" },
  كوره: { category: "ترفيه", subCategory: "رياضة وجيم" },
  كورة: { category: "ترفيه", subCategory: "رياضة وجيم" },
  ماتش: { category: "ترفيه", subCategory: "رياضة وجيم" },
  ملعب: { category: "ترفيه", subCategory: "رياضة وجيم" },
  سفر: { category: "ترفيه", subCategory: "سفر" },
  مصيف: { category: "ترفيه", subCategory: "سفر" },
  خروجه: { category: "ترفيه", subCategory: "خروجة" },
  عزمت: { category: "ترفيه", subCategory: "خروجة" },
  فرتكت: { category: "ترفيه", subCategory: "عام" },
  طيرت: { category: "ترفيه", subCategory: "عام" },
  // "رميت" removed from استثمار — in Egyptian Arabic "رميت" means "I spent/lost",
  // NOT investment. Was causing "رميت 50 على القهوة" → استثمار/توفير (critical bug).
  الجمعية: { category: "تحويل", subCategory: "ادخار" },
  جمعية: { category: "تحويل", subCategory: "ادخار" },
  جمعيه: { category: "تحويل", subCategory: "ادخار" },
  الجمعيه: { category: "تحويل", subCategory: "ادخار" },
  بادل: { category: "ترفيه", subCategory: "رياضة وجيم" },
  خماسي: { category: "ترفيه", subCategory: "رياضة وجيم" },
  تراك: { category: "ترفيه", subCategory: "رياضة وجيم" },
  بلياردو: { category: "ترفيه", subCategory: "ألعاب" },
  بلايستيشن: { category: "ترفيه", subCategory: "ألعاب" },
  // Subscriptions
  نتفلكس: { category: "اشتراكات", subCategory: "منصات مشاهدة" },
  سبوتيفاي: { category: "اشتراكات", subCategory: "موسيقى" },
  شاهد: { category: "اشتراكات", subCategory: "منصات مشاهدة" },
  "واتش ات": { category: "اشتراكات", subCategory: "منصات مشاهدة" },
  يوتيوب: { category: "اشتراكات", subCategory: "عام" },
  برايم: { category: "اشتراكات", subCategory: "منصات مشاهدة" },
  انغامي: { category: "اشتراكات", subCategory: "موسيقى" },
  // Gifts
  هديه: { category: "هدايا وصدقات", subCategory: "عام" },
  صدقه: { category: "هدايا وصدقات", subCategory: "صدقة/تبرع" },
  زكاه: { category: "هدايا وصدقات", subCategory: "زكاة" },
  عيديه: { category: "هدايا وصدقات", subCategory: "عيدية" },
  // Investment
  ذهب: { category: "استثمار", subCategory: "ذهب" },
  دهب: { category: "استثمار", subCategory: "ذهب" },
  اسهم: { category: "استثمار", subCategory: "أسهم" },
  شهاده: { category: "استثمار", subCategory: "شهادات" },
  // Egyptian slang
  // "شلت" alone removed — ambiguous: "شلت فلوس"=withdrawal, "شلت دهب"=gold purchase.
  // Only specific phrases "شلت دهب"/"شلت ذهب" remain mapped to investment/gold.
  "شلت دهب": { category: "استثمار", subCategory: "ذهب" },
  "شلت ذهب": { category: "استثمار", subCategory: "ذهب" },
  // Income subcategories
  مرتب: { category: "مرتب", subCategory: "مرتب أساسي" },
  بونص: { category: "مرتب", subCategory: "مكافأة/بونص" },
  مكافاه: { category: "مرتب", subCategory: "مكافأة/بونص" },
  قبض: { category: "مرتب", subCategory: "مرتب أساسي" },
  سلفه: { category: "تحويل", subCategory: "دين/سلفة" },
  سلفة: { category: "تحويل", subCategory: "دين/سلفة" },
  سلف: { category: "تحويل", subCategory: "دين/سلفة" },
  عموله: { category: "عمل حر", subCategory: "عمولة" },
  سبوبه: { category: "عمل حر", subCategory: "سبوبة" },
  سجاير: { category: "تدخين", subCategory: "سجائر" },
  سجائر: { category: "تدخين", subCategory: "سجائر" },
  سجاره: { category: "تدخين", subCategory: "سجائر" },
  فيب: { category: "تدخين", subCategory: "فيب/ليكود" },
  vape: { category: "تدخين", subCategory: "فيب/ليكود" },
  ليكود: { category: "تدخين", subCategory: "فيب/ليكود" },
  liquid: { category: "تدخين", subCategory: "فيب/ليكود" },
  شيشه: { category: "تدخين", subCategory: "شيشة/معسل" },
  شيشة: { category: "تدخين", subCategory: "شيشة/معسل" },
  معسل: { category: "تدخين", subCategory: "شيشة/معسل" },

  بامبرز: { category: "أطفال", subCategory: "بامبرز ولبن أطفال" },
  حفاظات: { category: "أطفال", subCategory: "بامبرز ولبن أطفال" },
  لبن: { category: "أكل وشرب", subCategory: "بقالة" },
  مناديل: { category: "سكن", subCategory: "منظفات" },
  مسحوق: { category: "سكن", subCategory: "منظفات" },
  مكواه: { category: "تسوق", subCategory: "ملابس" },
  مكواة: { category: "تسوق", subCategory: "ملابس" },
  "دراي كلين": { category: "تسوق", subCategory: "ملابس" },
  مكوجي: { category: "تسوق", subCategory: "ملابس" },
  لبان: { category: "أكل وشرب", subCategory: "سناكس" },
  شيبسي: { category: "أكل وشرب", subCategory: "سناكس" },
  بيبسي: { category: "أكل وشرب", subCategory: "سناكس" },
  بيبسى: { category: "أكل وشرب", subCategory: "سناكس" },
  كولا: { category: "أكل وشرب", subCategory: "سناكس" },
  كانز: { category: "أكل وشرب", subCategory: "سناكس" },
  اوريو: { category: "أكل وشرب", subCategory: "سناكس" },
  هوهوز: { category: "أكل وشرب", subCategory: "سناكس" },
  دونت: { category: "أكل وشرب", subCategory: "سناكس" },
  بسكوت: { category: "أكل وشرب", subCategory: "سناكس" },
  بسكويت: { category: "أكل وشرب", subCategory: "سناكس" },
  
  // Contextual Patterns (Smart Brain)
  // Vendor / Action Modifiers
  "عربيه كبده": { category: "أكل وشرب", subCategory: "مطعم" },
  "عربية كبدة": { category: "أكل وشرب", subCategory: "مطعم" },
  "عربيه فول": { category: "أكل وشرب", subCategory: "مطعم" },
  "عربية فول": { category: "أكل وشرب", subCategory: "مطعم" },
  "بتاع اللبن": { category: "أكل وشرب", subCategory: "بقالة" },
  "بتاع الخضار": { category: "أكل وشرب", subCategory: "بقالة" },
  "بتاع الانابيب": { category: "فواتير", subCategory: "غاز" },
  "غسيل عربيه": { category: "مواصلات", subCategory: "صيانة عربية" },
  "غسيل عربية": { category: "مواصلات", subCategory: "صيانة عربية" },
  "فول سوداني": { category: "أكل وشرب", subCategory: "سناكس" },
  "ورق عنب": { category: "أكل وشرب", subCategory: "بقالة" },
  "بن قهوه": { category: "أكل وشرب", subCategory: "بقالة" },
  "بن قهوة": { category: "أكل وشرب", subCategory: "بقالة" },
  "قهوه تركي": { category: "أكل وشرب", subCategory: "بقالة" },
  "قهوة تركي": { category: "أكل وشرب", subCategory: "بقالة" },
  "حجز كوره": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز كورة": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز الكوره": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز الكورة": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز الكره": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز الكرة": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز ملعب": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز الملعب": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز خماسي": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "حجز دكتور": { category: "صحة", subCategory: "دكتور" },
  "حجز كشف": { category: "صحة", subCategory: "دكتور" },
  "لعبت كوره": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "لعبت كورة": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "لعبت كره": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "لعبت كرة": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "لعبت فوتبول": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "لعبت بلياردو": { category: "ترفيه", subCategory: "ألعاب" },
  "لعبت بلايستيشن": { category: "ترفيه", subCategory: "ألعاب" },
  "اشتراك نت": { category: "فواتير", subCategory: "إنترنت" },
  "تجديد باقه": { category: "فواتير", subCategory: "إنترنت" },
  "تجديد باقة": { category: "فواتير", subCategory: "إنترنت" },
  "اشتراك جيم": { category: "ترفيه", subCategory: "رياضة وجيم" },
  "شحن رصيد": { category: "فواتير", subCategory: "شحن رصيد" },
  "شحن الرصيد": { category: "فواتير", subCategory: "شحن رصيد" },
  "شحنت رصيد": { category: "فواتير", subCategory: "شحن رصيد" },
  "دفعت شحن رصيد": { category: "فواتير", subCategory: "شحن رصيد" },
  // Digital/Fintech Services
  كلينق: { category: "اشتراكات", subCategory: "برمجيات" },
  فيزا: { category: "تحويل", subCategory: "تحويل بنكي" },
  استعلام: { category: "تحويل", subCategory: "سحب ATM" },
  تويست: { category: "أكل وشرب", subCategory: "سناكس" },
  // Note: بلايستيشن, كورة, كوره already defined earlier in this map (lines ~223-234)
  "بلاي ستيشن": { category: "ترفيه", subCategory: "ألعاب" },
  ريدبول: { category: "أكل وشرب", subCategory: "مشروبات" },
  "ريد بول": { category: "أكل وشرب", subCategory: "مشروبات" },
  فكيت: { category: "تحويل", subCategory: "تحويل كاش" },
  فك: { category: "تحويل", subCategory: "تحويل كاش" },
  فكه: { category: "تحويل", subCategory: "تحويل كاش" },
  كاش: { category: "تحويل", subCategory: "تحويل كاش" },
  // Government services
  "جواز سفر": { category: "خدمات حكومية", subCategory: "جواز سفر" },
  جواز: { category: "خدمات حكومية", subCategory: "جواز سفر" },
  "رقم قومي": { category: "خدمات حكومية", subCategory: "بطاقة رقم قومي" },
  "بطاقة رقم قومي": { category: "خدمات حكومية", subCategory: "بطاقة رقم قومي" },
  "مخالفة مرور": { category: "خدمات حكومية", subCategory: "مخالفة مرور" },
  مخالفه: { category: "خدمات حكومية", subCategory: "مخالفة مرور" },
  مخالفة: { category: "خدمات حكومية", subCategory: "مخالفة مرور" },
  "تجديد رخصة": { category: "خدمات حكومية", subCategory: "رخصة" },
  رخصه: { category: "خدمات حكومية", subCategory: "رخصة" },
  رخصة: { category: "خدمات حكومية", subCategory: "رخصة" },
  توثيق: { category: "خدمات حكومية", subCategory: "توثيق" },
  // Missing Egyptian food words
  كنافه: { category: "أكل وشرب", subCategory: "سناكس" },
  كنافة: { category: "أكل وشرب", subCategory: "سناكس" },
  ملوخيه: { category: "أكل وشرب", subCategory: "مطعم" },
  ملوخية: { category: "أكل وشرب", subCategory: "مطعم" },
  فته: { category: "أكل وشرب", subCategory: "مطعم" },
  فتة: { category: "أكل وشرب", subCategory: "مطعم" },
  "فول مدمس": { category: "أكل وشرب", subCategory: "مطعم" },
  شعريه: { category: "أكل وشرب", subCategory: "بقالة" },
  شعرية: { category: "أكل وشرب", subCategory: "بقالة" },
  بوفيه: { category: "أكل وشرب", subCategory: "مطعم" },
  // Missing transport/car words
  ونش: { category: "مواصلات", subCategory: "صيانة عربية" },
  ميكانيكي: { category: "مواصلات", subCategory: "صيانة عربية" },
  كاوتش: { category: "مواصلات", subCategory: "صيانة عربية" },
  "غسلت العربية": { category: "مواصلات", subCategory: "صيانة عربية" },
  "غسيل العربية": { category: "مواصلات", subCategory: "صيانة عربية" },
  // Missing health words
  تطعيم: { category: "صحة", subCategory: "دكتور" },
  طوارئ: { category: "صحة", subCategory: "مستشفى" },
  اسعاف: { category: "صحة", subCategory: "مستشفى" },
  "علاج طبيعي": { category: "صحة", subCategory: "دكتور" },
  بيطري: { category: "حيوانات أليفة", subCategory: "طبيب بيطري" },
  // General missing words
  مول: { category: "تسوق", subCategory: "عام" },
  جزمجي: { category: "تسوق", subCategory: "أحذية" },
  ترزي: { category: "تسوق", subCategory: "ملابس" },
  خياط: { category: "تسوق", subCategory: "ملابس" },
  "مكنة الصراف": { category: "تحويل", subCategory: "سحب ATM" },
  "ماكينة الصراف": { category: "تحويل", subCategory: "سحب ATM" },
  atm: { category: "تحويل", subCategory: "سحب ATM" },
  // Context-aware: "اشتريت شقة" = investment, "إيجار شقة" = home
  "اشتريت شقة": { category: "استثمار", subCategory: "عقارات" },
  "اشتريت شقه": { category: "استثمار", subCategory: "عقارات" },
  "شقة تمليك": { category: "استثمار", subCategory: "عقارات" },
  "شقه تمليك": { category: "استثمار", subCategory: "عقارات" },
};
