/**
 * The LikeC4 model of the code, generated from the atlas graph into docs/architecture/generated/.
 *
 * The hand-written files one folder up declare the element kinds (spec.c4), the people and
 * containers around the code (context.c4), the views (views.c4) and the key flows (flows/).
 * Everything inside the containers comes from here, so the map changes when the code does.
 *
 * The output format is fixed on purpose — one declaration or relationship per line, sorted,
 * addressed by fully qualified names — because tests/knowledge/flows.test.ts reads these files
 * without LikeC4 to prove that every hand-drawn flow step exists in the code.
 */
import type { AtlasGraph } from "../graph";
import type { ClusterRule, ExternalSystem } from "../extract/modules";
import { byKey, compareStrings, uniqSorted } from "../lib/util";

export const ARCH_GENERATED_DIR = "docs/architecture/generated";

const BANNER = [
  "// GENERATED by `npm run atlas` from the source code. Do not edit: the next run overwrites this file.",
  "// The hand-written model sits one folder up: spec.c4, context.c4, views.c4 and flows/.",
].join("\n");

export const ROOT = "smartspend";

/** Containers declared by hand in docs/architecture/context.c4; the generator only fills them. */
export const CONTAINERS = {
  web: `${ROOT}.web`,
  pages: `${ROOT}.web.pages`,
  webModules: `${ROOT}.web.modules`,
  api: `${ROOT}.api`,
  trpc: `${ROOT}.api.trpc`,
  http: `${ROOT}.api.http`,
  ws: `${ROOT}.api.ws`,
  scheduler: `${ROOT}.api.scheduler`,
  apiModules: `${ROOT}.api.modules`,
  shared: `${ROOT}.shared`,
  mysql: `${ROOT}.mysql`,
} as const;

/** The externals.json system that is the database container itself rather than a separate store. */
const DATABASE_SYSTEM_ID = "mysql";

/** Same exclusions as the markdown atlas: every data module touches these, so edges to them are noise. */
const INFRA_FILES = new Set(["api/middleware.ts", "api/queries/connection.ts", "db/schema.ts"]);

/**
 * Words LikeC4 (1.59) rejects as element ids, found by validating one element per candidate word.
 * An id that collides gets a trailing underscore.
 */
const RESERVED_IDS = new Set([
  "and", "autoLayout", "border", "color", "description", "dynamic", "exclude", "extend", "from",
  "global", "head", "icon", "import", "include", "is", "it", "kind", "line", "link", "metadata",
  "multiple", "navigateTo", "not", "notes", "opacity", "or", "predicate", "rank", "shape", "size",
  "specification", "style", "summary", "tag", "tail", "technology", "this", "title", "view", "views",
  "where", "with",
]);

export function safeId(raw: string): string {
  let id = raw.replace(/[^A-Za-z0-9_-]+/g, "_").replace(/^_+|_+$/g, "");
  if (!id) id = "unnamed";
  if (!/^[A-Za-z_]/.test(id)) id = `_${id}`;
  return RESERVED_IDS.has(id) ? `${id}_` : id;
}

function viewId(raw: string): string {
  return raw.replace(/[^A-Za-z0-9_]+/g, "_");
}

function quote(value: string): string {
  return `'${value.replace(/\r?\n/g, " ").replace(/\\/g, "/").replace(/'/g, "’")}'`;
}

interface ElementSpec {
  id: string;
  kind: string;
  title: string;
  tags?: string[];
  technology?: string;
  description?: string;
  metadata?: Array<[string, string]>;
  children?: ElementSpec[];
}

function metadataOf(entries: Array<[string, string]>): Array<[string, string]> {
  return entries.filter(([, value]) => value.length > 0);
}

function renderElement(element: ElementSpec, indent: string): string[] {
  const inner = `${indent}  `;
  const body: string[] = [];
  if (element.tags && element.tags.length > 0) body.push(`${inner}${element.tags.map((tag) => `#${tag}`).join(" ")}`);
  if (element.technology) body.push(`${inner}technology ${quote(element.technology)}`);
  if (element.description) body.push(`${inner}description ${quote(element.description)}`);
  if (element.metadata && element.metadata.length > 0) {
    body.push(`${inner}metadata {`);
    for (const [key, value] of element.metadata) body.push(`${inner}  ${key} ${quote(value)}`);
    body.push(`${inner}}`);
  }
  for (const child of element.children ?? []) body.push(...renderElement(child, inner));
  const head = `${indent}${element.id} = ${element.kind} ${quote(element.title)}`;
  return body.length === 0 ? [head] : [`${head} {`, ...body, `${indent}}`];
}

function sortElements(elements: ElementSpec[]): ElementSpec[] {
  return [...elements].sort(byKey((element) => element.id));
}

function extendBlock(parent: string, children: ElementSpec[]): string | null {
  if (children.length === 0) return null;
  return [`  extend ${parent} {`, ...sortElements(children).flatMap((child) => renderElement(child, "    ")), "  }"].join(
    "\n",
  );
}

function modelFile(blocks: Array<string | null>): string {
  const body = blocks.filter((block): block is string => Boolean(block));
  return `${BANNER}\n\nmodel {\n${body.join("\n\n")}\n}\n`;
}

/** Web clusters live in the web container, shared contracts in their own area, the rest in the API. */
function clusterContainer(rule: ClusterRule): string {
  if (rule.paths.every((glob) => glob.startsWith("src/"))) return CONTAINERS.webModules;
  if (rule.paths.every((glob) => glob.startsWith("contracts/"))) return CONTAINERS.shared;
  return CONTAINERS.apiModules;
}

function systemAddress(system: ExternalSystem): string {
  if (system.kind !== "datastore") return safeId(system.id);
  return system.id === DATABASE_SYSTEM_ID ? CONTAINERS.mysql : `${ROOT}.${safeId(system.id)}`;
}

function procedureLocalId(routerKey: string, procedurePath: string): string {
  const local = procedurePath.startsWith(`${routerKey}.`) ? procedurePath.slice(routerKey.length + 1) : procedurePath;
  return safeId(local);
}

/** `POST /api/sms/ingest` → `post_sms_ingest`. */
function endpointId(method: string, routePath: string): string {
  const cleaned = routePath.replace(/^\/(?:api\/)?/, "").replace(/\*/g, "all");
  return safeId(`${method.toLowerCase()}_${cleaned}`);
}

function socketId(pathPrefix: string): string {
  return safeId(pathPrefix.replace(/^\/api\//, "").replace(/^\//, ""));
}

type RelationKind = "calls" | "reads" | "writes" | "uses" | "imports";

export function renderLikeC4(graph: AtlasGraph): Map<string, string> {
  const { api, database, entrypoints, frontend, modules, clusters, externals } = graph;

  const tags = new Set<string>();
  const tag = (value: string): string => {
    const name = safeId(value);
    tags.add(name);
    return name;
  };

  // ── Addresses ────────────────────────────────────────────────────────────────
  const clusterFqn = new Map(clusters.map((rule) => [rule.id, `${clusterContainer(rule)}.${safeId(rule.id)}`]));
  const clusterOfFile = new Map(modules.map((module) => [module.file, module.cluster]));
  const clusterOf = (file: string): string | undefined => {
    if (INFRA_FILES.has(file)) return undefined;
    const id = clusterOfFile.get(file);
    return id ? clusterFqn.get(id) : undefined;
  };
  const tableFqn = new Map(database.tables.map((table) => [table.name, `${CONTAINERS.mysql}.${safeId(table.name)}`]));
  const systemFqn = new Map(externals.systems.map((system) => [system.id, systemAddress(system)]));
  const routerFqn = new Map(api.routers.map((router) => [router.key, `${CONTAINERS.trpc}.${safeId(router.key)}`]));
  const procedureFqn = new Map<string, string>();
  for (const router of api.routers) {
    for (const procedure of router.procedures) {
      procedureFqn.set(procedure.path, `${routerFqn.get(router.key)}.${procedureLocalId(router.key, procedure.path)}`);
    }
  }
  const shellFqn = `${CONTAINERS.web}.shell`;
  const pageFqn = (name: string) => `${CONTAINERS.pages}.${safeId(name)}`;
  const calledProcedures = new Set(
    frontend.calls.filter((call) => call.procedure).map((call) => `${call.router}.${call.procedure}`),
  );

  // ── Elements ─────────────────────────────────────────────────────────────────
  const topLevelSystems: ElementSpec[] = [];
  const stores: ElementSpec[] = [];
  for (const system of externals.systems) {
    if (system.kind === "datastore" && system.id === DATABASE_SYSTEM_ID) continue;
    const element: ElementSpec = {
      id: safeId(system.id),
      kind: system.kind === "datastore" ? "store" : "external",
      title: system.title,
      technology: system.kind,
      metadata: metadataOf([
        ["packages", (system.packages ?? []).join(", ")],
        ["hosts", (system.hosts ?? []).join(", ")],
      ]),
    };
    (system.kind === "datastore" ? stores : topLevelSystems).push(element);
  }

  const tables: ElementSpec[] = database.tables.map((table) => ({
    id: safeId(table.name),
    kind: "table",
    title: table.name,
    tags: [
      tag(table.tableClass ? `class${table.tableClass}` : "unclassified"),
      ...(table.dualUserOwnership ? [tag("dualOwner")] : []),
    ],
    description: `${table.columns.length} columns, ${table.indexes.length} indexes${
      table.tableClass ? `, storage class ${table.tableClass}` : ", no storage class"
    }.`,
    metadata: metadataOf([
      ["export", table.exportName],
      ["storageClass", table.tableClass ?? ""],
    ]),
  }));

  const routers: ElementSpec[] = api.routers.map((router) => ({
    id: safeId(router.key),
    kind: "router",
    title: router.key,
    description: `${router.file} — ${router.procedures.length} procedures.`,
    metadata: metadataOf([["file", router.file]]),
    children: router.procedures.map((procedure) => {
      const called = calledProcedures.has(procedure.path);
      return {
        id: procedureLocalId(router.key, procedure.path),
        kind: "procedure",
        title: procedure.path,
        tags: [
          tag(procedure.kind),
          tag(procedure.builder.replace(/Procedure$/, "")),
          ...(called ? [] : [tag("uncalled")]),
        ],
        technology: procedure.builder,
        description: `${procedure.kind} · ${procedure.builder}${called ? "" : " · no caller in src/"}`,
        metadata: metadataOf([
          ["file", procedure.file],
          ["builder", procedure.builder],
          ["procedureKind", procedure.kind],
        ]),
      };
    }),
  }));

  const endpointIds = new Map<(typeof entrypoints.routes)[number], string>();
  const usedEndpointIds = new Set<string>();
  const endpoints: ElementSpec[] = entrypoints.routes.map((route) => {
    let id = endpointId(route.method, route.path);
    for (let suffix = 2; usedEndpointIds.has(id); suffix++) id = `${endpointId(route.method, route.path)}_${suffix}`;
    usedEndpointIds.add(id);
    endpointIds.set(route, id);
    return {
      id,
      kind: "endpoint",
      title: `${route.method} ${route.path}`,
      tags: [tag(route.kind)],
      description: `Declared in ${route.file}.`,
      metadata: metadataOf([
        ["file", route.file],
        ["method", route.method],
        ["path", route.path],
      ]),
    };
  });

  const socketsByPrefix = new Map<string, typeof entrypoints.websockets>();
  for (const socket of entrypoints.websockets) {
    socketsByPrefix.set(socket.pathPrefix, [...(socketsByPrefix.get(socket.pathPrefix) ?? []), socket]);
  }
  const sockets: ElementSpec[] = [...socketsByPrefix.entries()].map(([prefix, entries]) => ({
    id: socketId(prefix),
    kind: "endpoint",
    title: `WS ${prefix}`,
    tags: [tag("websocket")],
    description: `Upgrade handled by ${entries[0].handler}.`,
    metadata: metadataOf([
      ["handlerFile", entries[0].handlerFile ?? ""],
      ["wiredIn", uniqSorted(entries.map((entry) => entry.file)).join(", ")],
    ]),
  }));

  const jobs: ElementSpec[] = entrypoints.jobs.map((job) => ({
    id: safeId(job.name),
    kind: "job",
    title: job.name,
    technology: job.schedule === "once at boot" ? "once at boot" : `cron ${job.schedule}`,
    description: `Scheduled in ${job.file}.`,
    metadata: metadataOf([
      ["schedule", job.schedule],
      ["file", job.file],
    ]),
  }));

  const routesByComponent = new Map<string, string[]>();
  for (const route of frontend.routes) {
    if (route.component) routesByComponent.set(route.component, [...(routesByComponent.get(route.component) ?? []), route.path]);
  }
  const pages: ElementSpec[] = frontend.pages.map((page) => ({
    id: safeId(page.name),
    kind: "page",
    title: page.name,
    description: page.file,
    metadata: metadataOf([
      ["file", page.file],
      ["routes", uniqSorted(routesByComponent.get(page.name) ?? []).join(", ")],
    ]),
  }));
  const shell: ElementSpec = {
    id: "shell",
    kind: "page",
    title: "App shell",
    description: `${frontend.shell.file} and everything it renders around the pages.`,
    metadata: metadataOf([["file", frontend.shell.file]]),
  };

  const membersPerCluster = new Map<string, number>();
  for (const module of modules) membersPerCluster.set(module.cluster, (membersPerCluster.get(module.cluster) ?? 0) + 1);
  const clustersByContainer = new Map<string, ElementSpec[]>();
  for (const rule of clusters) {
    const container = clusterContainer(rule);
    clustersByContainer.set(container, [
      ...(clustersByContainer.get(container) ?? []),
      {
        id: safeId(rule.id),
        kind: "module",
        title: rule.title,
        description: rule.description,
        metadata: metadataOf([
          ["files", String(membersPerCluster.get(rule.id) ?? 0)],
          ["paths", rule.paths.join(", ")],
        ]),
      },
    ]);
  }

  // ── Relationships ────────────────────────────────────────────────────────────
  const relations = new Set<string>();
  const relate = (source: string | undefined, kind: RelationKind, target: string | undefined) => {
    if (!source || !target || source === target) return;
    // LikeC4 does not draw an element's relationship with its own ancestor or descendant.
    if (target.startsWith(`${source}.`) || source.startsWith(`${target}.`)) return;
    relations.add(`  ${source} -[${kind}]-> ${target}`);
  };

  const pageCalls: Array<[string, typeof frontend.calls]> = [
    [shellFqn, frontend.shell.calls],
    ...frontend.pages.map((page): [string, typeof frontend.calls] => [pageFqn(page.name), page.calls]),
  ];
  for (const [source, calls] of pageCalls) {
    for (const call of calls) {
      relate(source, "calls", call.procedure ? procedureFqn.get(`${call.router}.${call.procedure}`) : routerFqn.get(call.router));
    }
  }

  for (const router of api.routers) {
    for (const procedure of router.procedures) {
      const source = procedureFqn.get(procedure.path);
      for (const table of procedure.read) relate(source, "reads", tableFqn.get(table));
      for (const table of procedure.write) relate(source, "writes", tableFqn.get(table));
      for (const file of procedure.uses) relate(source, "uses", clusterOf(file));
    }
  }

  for (const route of entrypoints.routes) {
    const source = `${CONTAINERS.http}.${endpointIds.get(route)}`;
    if (route.kind === "trpc") relate(source, "calls", CONTAINERS.trpc);
    for (const table of route.read) relate(source, "reads", tableFqn.get(table));
    for (const table of route.write) relate(source, "writes", tableFqn.get(table));
    for (const file of route.uses) relate(source, "uses", clusterOf(file));
  }

  for (const [prefix, entries] of socketsByPrefix) {
    const source = `${CONTAINERS.ws}.${socketId(prefix)}`;
    for (const entry of entries) if (entry.handlerFile) relate(source, "uses", clusterOf(entry.handlerFile));
  }

  for (const job of entrypoints.jobs) {
    const source = `${CONTAINERS.scheduler}.${safeId(job.name)}`;
    for (const table of job.read) relate(source, "reads", tableFqn.get(table));
    for (const table of job.write) relate(source, "writes", tableFqn.get(table));
    for (const file of job.uses) relate(source, "uses", clusterOf(file));
  }

  for (const module of modules) {
    const source = clusterFqn.get(module.cluster);
    for (const file of module.imports) relate(source, "imports", clusterOf(file));
    for (const table of module.read) relate(source, "reads", tableFqn.get(table));
    for (const table of module.write) relate(source, "writes", tableFqn.get(table));
    for (const system of module.externals) relate(source, "uses", systemFqn.get(system));
  }

  // ── Views ────────────────────────────────────────────────────────────────────
  const views: string[] = [
    ...[...api.routers].sort(byKey((router) => router.key)).map((router) =>
      [
        `  view router_${viewId(router.key)} of ${routerFqn.get(router.key)} {`,
        `    title ${quote(`tRPC router · ${router.key}`)}`,
        "    include *",
        "  }",
      ].join("\n"),
    ),
    ...[...clusters].sort(byKey((rule) => rule.id)).map((rule) =>
      [
        `  view module_${viewId(rule.id)} of ${clusterFqn.get(rule.id)} {`,
        `    title ${quote(`Module · ${rule.title}`)}`,
        "    include *",
        "  }",
      ].join("\n"),
    ),
  ];

  // ── Files ────────────────────────────────────────────────────────────────────
  const moduleBlocks = [CONTAINERS.apiModules, CONTAINERS.shared, CONTAINERS.webModules].map((container) =>
    extendBlock(container, clustersByContainer.get(container) ?? []),
  );
  const systemsBlock = sortElements(topLevelSystems)
    .flatMap((element) => renderElement(element, "  "))
    .join("\n");

  return new Map([
    [
      `${ARCH_GENERATED_DIR}/api.c4`,
      modelFile([
        extendBlock(CONTAINERS.trpc, routers.map((router) => ({ ...router, children: sortElements(router.children ?? []) }))),
        extendBlock(CONTAINERS.http, endpoints),
        extendBlock(CONTAINERS.ws, sockets),
        extendBlock(CONTAINERS.scheduler, jobs),
      ]),
    ],
    [`${ARCH_GENERATED_DIR}/database.c4`, modelFile([extendBlock(CONTAINERS.mysql, tables)])],
    [`${ARCH_GENERATED_DIR}/modules.c4`, modelFile(moduleBlocks)],
    [
      `${ARCH_GENERATED_DIR}/relationships.c4`,
      `${BANNER}\n\nmodel {\n${[...relations].sort(compareStrings).join("\n")}\n}\n`,
    ],
    [
      `${ARCH_GENERATED_DIR}/specification.c4`,
      `${BANNER}\n\nspecification {\n${uniqSorted(tags)
        .map((name) => `  tag ${name}`)
        .join("\n")}\n}\n`,
    ],
    [`${ARCH_GENERATED_DIR}/systems.c4`, modelFile([systemsBlock || null, extendBlock(ROOT, stores)])],
    [`${ARCH_GENERATED_DIR}/views.c4`, `${BANNER}\n\nviews {\n${views.join("\n\n")}\n}\n`],
    [`${ARCH_GENERATED_DIR}/web.c4`, modelFile([extendBlock(CONTAINERS.web, [shell]), extendBlock(CONTAINERS.pages, pages)])],
  ]);
}
