import type { AtlasGraph } from "../graph";
import { byKey, code, codeList, compareStrings, mdTable, uniqSorted } from "../lib/util";

export const ATLAS_DIR = "docs/atlas";

const GENERATED_BANNER =
  "<!-- GENERATED by `npm run atlas` from the source code. Do not edit: the next run overwrites this file. -->";
const INFRA_FILES = new Set(["api/middleware.ts", "api/queries/connection.ts", "db/schema.ts"]);

function page(title: string, intro: string, sections: string[]): string {
  const body = [`${GENERATED_BANNER}\n\n# ${title}\n\n${intro}`, ...sections]
    .map((part) => part.trim())
    .filter(Boolean)
    .join("\n\n");
  return `${body}\n`;
}

function section(title: string, ...parts: string[]): string {
  return [`## ${title}`, ...parts.map((part) => part.trim()).filter(Boolean)].join("\n\n");
}

function subsection(title: string, ...parts: string[]): string {
  return [`### ${title}`, ...parts.map((part) => part.trim()).filter(Boolean)].join("\n\n");
}

function withoutInfra(files: readonly string[]): string[] {
  return files.filter((file) => !INFRA_FILES.has(file));
}

function formatWindow(ms: number | null): string {
  if (ms === null) return "?";
  if (ms % 60_000 === 0) return `${ms / 60_000} min`;
  return `${ms / 1000} s`;
}

function groupSets(entries: Array<[string, string]>): Map<string, string[]> {
  const map = new Map<string, Set<string>>();
  for (const [key, value] of entries) {
    if (!map.has(key)) map.set(key, new Set());
    map.get(key)!.add(value);
  }
  return new Map([...map.entries()].map(([key, values]) => [key, uniqSorted(values)]));
}

function renderApi(graph: AtlasGraph): string {
  const { api, frontend } = graph;
  const callers = groupSets(
    frontend.calls
      .filter((call) => call.procedure)
      .map((call) => [`${call.router}.${call.procedure}`, call.file] as [string, string]),
  );

  const builders = mdTable(
    ["Builder", "Built on", "Signed-in check", "Rate limit", "Roles compared", "Plans compared"],
    api.builders.map((builder) => [
      code(builder.name),
      builder.extends ? code(builder.extends) : code("t.procedure"),
      builder.requiresUser ? "yes" : builder.extends ? "inherited" : "no",
      builder.rateLimits.length === 0
        ? "—"
        : builder.rateLimits
            .map((limit) => `${limit.max ?? "?"} per ${formatWindow(limit.windowMs)} (${code(limit.limiter)})`)
            .join("; "),
      builder.roles.join(", ") || "—",
      builder.plans.join(", ") || "—",
    ]),
  );

  const overview = mdTable(
    ["Router", "File", "Procedures", "Queries", "Mutations", "Builders used"],
    api.routers.map((router) => [
      code(router.key),
      code(router.file),
      String(router.procedures.length),
      String(router.procedures.filter((p) => p.kind === "query").length),
      String(router.procedures.filter((p) => p.kind === "mutation").length),
      uniqSorted(router.procedures.map((p) => p.builder)).map(code).join(", "),
    ]),
  );

  const routerSections = api.routers.map((router) =>
    subsection(
      `${code(router.key)} — ${code(router.file)}`,
      mdTable(
        ["Procedure", "Kind", "Builder", "Input", "Reads", "Writes", "Depends on", "Called from src/"],
        router.procedures.map((procedure) => [
          code(procedure.path),
          procedure.kind,
          code(procedure.builder),
          procedure.hasInput ? "yes" : "no",
          codeList(procedure.read),
          codeList(procedure.write),
          codeList(withoutInfra(procedure.uses)),
          codeList(callers.get(procedure.path) ?? []),
        ]),
      ),
    ),
  );

  const uncalled = api.routers
    .flatMap((router) => router.procedures)
    .filter((procedure) => !callers.has(procedure.path))
    .map((procedure) => procedure.path);

  return page(
    "API (tRPC)",
    `Root router: ${code(api.rootFile)}. Procedure builders: ${code(api.middlewareFile)}. The HTTP mount point is listed in [entrypoints.md](entrypoints.md).`,
    [
      section("Procedure builders", builders),
      section("Routers", overview),
      section("Procedures by router", ...routerSections),
      section(
        "Procedures with no caller in src/",
        "These are not referenced by the web app. Some may be called by other clients (Android app, iOS shortcuts) or server-side through `createCaller`; the rest are candidates for removal.",
        codeList(uncalled),
      ),
    ],
  );
}

function renderDatabase(graph: AtlasGraph): string {
  const { database, modules } = graph;
  const readers = groupSets(modules.flatMap((m) => m.read.map((table) => [table, m.file] as [string, string])));
  const writers = groupSets(modules.flatMap((m) => m.write.map((table) => [table, m.file] as [string, string])));
  const relationsByTable = new Map<string, string[]>();
  for (const relation of database.relations) {
    const list = relationsByTable.get(relation.table) ?? [];
    list.push(`${relation.name} → ${relation.target}`);
    relationsByTable.set(relation.table, list);
  }
  const foreignKeys = database.tables.reduce((total, table) => total + table.foreignKeys, 0);

  const classRows = database.classes.map((definition) => [
    code(definition.id),
    definition.name,
    definition.lifetime,
    definition.storageRule,
    String(database.tables.filter((table) => table.tableClass === definition.id).length),
  ]);

  const tableRow = (table: (typeof database.tables)[number]) => [
    code(table.name),
    code(table.exportName),
    String(table.columns.length),
    String(table.indexes.length),
    table.dualUserOwnership ? "`user_id` + `user_type`" : "—",
    codeList(relationsByTable.get(table.name) ?? []),
    codeList(readers.get(table.name) ?? []),
    codeList(writers.get(table.name) ?? []),
  ];
  const tableHeaders = ["Table", "Export", "Columns", "Indexes", "Owner pair", "Relations", "Read by", "Written by"];

  const classSections = database.classes.map((definition) =>
    subsection(
      `Class ${definition.id} — ${definition.name}`,
      definition.description,
      mdTable(tableHeaders, database.tables.filter((t) => t.tableClass === definition.id).map(tableRow)),
    ),
  );
  const unclassified = database.tables.filter((table) => !table.tableClass);
  if (unclassified.length > 0) {
    classSections.push(subsection("Unclassified", mdTable(tableHeaders, unclassified.map(tableRow))));
  }

  const withRelations = new Set(database.relations.map((relation) => relation.table));
  const noRelations = database.tables.filter((t) => !withRelations.has(t.name)).map((t) => t.name);
  const untouched = database.tables.filter((t) => !readers.has(t.name) && !writers.has(t.name)).map((t) => t.name);
  const writeOnly = database.tables.filter((t) => writers.has(t.name) && !readers.has(t.name)).map((t) => t.name);
  const readOnly = database.tables.filter((t) => readers.has(t.name) && !writers.has(t.name)).map((t) => t.name);

  return page(
    "Database",
    [
      `Sources: ${code("db/schema.ts")} (tables), ${code("db/relations.ts")} (relations), ${code("db/table-classes.ts")} (storage classes).`,
      `Foreign-key constraints declared in the schema: **${foreignKeys}**. Every relationship below is application-level only.`,
      `"Read by" and "Written by" list runtime files whose code reads or writes the table through Drizzle calls or SQL text the generator can see.`,
    ].join("\n\n"),
    [
      section("Storage classes", mdTable(["Class", "Name", "Lifetime", "Storage rule", "Tables"], classRows)),
      section("Tables by storage class", ...classSections),
      section(
        "Relations",
        mdTable(
          ["Table", "Relation", "Kind", "Target", "Fields"],
          database.relations.map((relation) => [
            code(relation.table),
            code(relation.name),
            relation.kind,
            code(relation.target),
            codeList(relation.fields),
          ]),
        ),
      ),
      section(
        "Checks",
        mdTable(
          ["Check", "Tables"],
          [
            ["No relations in db/relations.ts", codeList(noRelations)],
            ["Not read or written by any runtime file", codeList(untouched)],
            ["Written but never read by runtime code", codeList(writeOnly)],
            ["Read but never written by runtime code", codeList(readOnly)],
          ],
        ),
      ),
    ],
  );
}

function renderEntrypoints(graph: AtlasGraph): string {
  const { entrypoints } = graph;
  const middleware = mdTable(
    ["#", "Path", "Handler"],
    entrypoints.middleware.map((entry, index) => [String(index + 1), code(entry.path), code(entry.handler)]),
  );
  const routes = mdTable(
    ["Method", "Path", "Kind", "Declared in", "Depends on"],
    entrypoints.routes.map((route) => [
      route.method,
      code(route.path),
      route.kind,
      code(route.file),
      codeList(withoutInfra(route.uses)),
    ]),
  );
  const websockets = mdTable(
    ["Path prefix", "Handler", "Handler file", "Wired in"],
    entrypoints.websockets.map((socket) => [
      code(socket.pathPrefix),
      code(socket.handler),
      socket.handlerFile ? code(socket.handlerFile) : "—",
      code(socket.file),
    ]),
  );
  const moduleByFile = new Map(graph.modules.map((module) => [module.file, module]));
  const jobModules = (uses: string[]) => uses.filter((file) => file.startsWith("api/jobs/"));
  const jobs = mdTable(
    ["Job", "Schedule", "Depends on", "Reads", "Writes"],
    entrypoints.jobs.map((job) => [
      code(job.name),
      job.schedule === "once at boot" ? job.schedule : code(job.schedule),
      codeList(withoutInfra(job.uses)),
      codeList(uniqSorted([...job.read, ...jobModules(job.uses).flatMap((file) => moduleByFile.get(file)?.read ?? [])])),
      codeList(uniqSorted([...job.write, ...jobModules(job.uses).flatMap((file) => moduleByFile.get(file)?.write ?? [])])),
    ]),
  );
  const switches =
    entrypoints.switches.length === 0
      ? ""
      : `${code(entrypoints.appFile)} checks these environment switches before starting background work: ${codeList(entrypoints.switches)}. See [env.md](env.md).`;

  return page(
    "Entry points",
    `How traffic and time enter the backend. Everything below is read from ${code(entrypoints.appFile)} and the sub-apps it mounts.`,
    [
      section("Middleware (registration order)", middleware),
      section("HTTP routes", routes),
      section("WebSocket upgrades", websockets),
      section(
        "Scheduled jobs",
        switches,
        `Reads and writes cover the job body in ${code(entrypoints.appFile)} plus the ${code("api/jobs/")} module it calls.`,
        jobs,
      ),
    ],
  );
}

function renderFrontend(graph: AtlasGraph): string {
  const { frontend } = graph;
  const routes = mdTable(
    ["Path", "Access", "Page", "Page file", "Redirects to"],
    frontend.routes.map((route) => [
      code(route.path),
      route.access,
      route.component ? code(route.component) : "—",
      route.pageFile ? code(route.pageFile) : "—",
      route.redirect ? code(route.redirect) : "—",
    ]),
  );

  const renderPage = (name: string, file: string, files: string[], calls: typeof frontend.calls) => {
    const byProcedure = new Map<string, { methods: Set<string>; files: Set<string> }>();
    for (const call of calls) {
      const key = call.procedure ? `${call.router}.${call.procedure}` : `${call.router}.*`;
      const entry = byProcedure.get(key) ?? { methods: new Set<string>(), files: new Set<string>() };
      entry.methods.add(call.method);
      entry.files.add(call.file);
      byProcedure.set(key, entry);
    }
    const rows = [...byProcedure.entries()]
      .sort((a, b) => compareStrings(a[0], b[0]))
      .map(([procedure, entry]) => [code(procedure), uniqSorted(entry.methods).join(", "), codeList(uniqSorted(entry.files))]);
    return subsection(
      `${code(name)} — ${code(file)}`,
      `${files.length} files in its import closure (not counting ${code("src/components/ui/")}).`,
      mdTable(["Procedure", "Calls", "Files"], rows),
    );
  };

  return page(
    "Frontend",
    `Browser routes come from ${code(frontend.appFile)}. For each page, the generator follows imports under ${code("src/")} and lists every tRPC hook and cache call it finds.`,
    [
      section("Browser routes", routes),
      section("App shell (rendered around every page)", renderPage(frontend.shell.name, frontend.shell.file, frontend.shell.files, frontend.shell.calls)),
      section("Pages", ...frontend.pages.map((p) => renderPage(p.name, p.file, p.files, p.calls))),
    ],
  );
}

function renderModules(graph: AtlasGraph): string {
  const { modules, clusters, externals } = graph;
  const clusterOf = new Map(modules.map((m) => [m.file, m.cluster]));
  const known = [...clusters.map((c) => c.id), ...(modules.some((m) => m.cluster === "unclustered") ? ["unclustered"] : [])];

  const dependsOn = new Map<string, Set<string>>();
  const usedBy = new Map<string, Set<string>>();
  for (const id of known) {
    dependsOn.set(id, new Set());
    usedBy.set(id, new Set());
  }
  for (const module of modules) {
    for (const target of module.imports) {
      const targetCluster = clusterOf.get(target);
      if (!targetCluster || targetCluster === module.cluster) continue;
      dependsOn.get(module.cluster)!.add(targetCluster);
      usedBy.get(targetCluster)!.add(module.cluster);
    }
  }

  const clusterRows = known.map((id) => {
    const rule = clusters.find((c) => c.id === id);
    const members = modules.filter((m) => m.cluster === id);
    return [
      code(id),
      rule?.title ?? "Files no rule matches",
      String(members.length),
      codeList(uniqSorted(dependsOn.get(id) ?? [])),
      codeList(uniqSorted(usedBy.get(id) ?? [])),
      codeList(uniqSorted(members.flatMap((m) => m.externals))),
    ];
  });

  const systemRows = [...externals.systems].sort(byKey((s) => s.id)).map((system) => {
    const users = modules.filter((m) => m.externals.includes(system.id));
    return [
      code(system.id),
      system.title,
      system.kind,
      codeList(uniqSorted(users.map((m) => m.cluster))),
      codeList(users.map((m) => m.file)),
    ];
  });

  const clusterSections = known.map((id) => {
    const rule = clusters.find((c) => c.id === id);
    const members = modules.filter((m) => m.cluster === id);
    return subsection(
      `${code(id)} — ${rule?.title ?? "Files no rule matches"}`,
      rule?.description ?? "Add these files to a cluster in docs/architecture/clusters.json.",
      mdTable(
        ["File", "Imports from clusters", "External systems referenced", "Reads", "Writes"],
        members.map((m) => [
          code(m.file),
          codeList(uniqSorted(m.imports.map((f) => clusterOf.get(f)).filter((c): c is string => Boolean(c) && c !== id))),
          codeList(m.externals),
          codeList(m.read),
          codeList(m.write),
        ]),
      ),
    );
  });

  return page(
    "Modules",
    `Runtime source files (tests, ${code("api/qa/")} and ${code("api/scripts/")} excluded), grouped by the hand-maintained rules in ${code("docs/architecture/clusters.json")}. External systems are classified in ${code("docs/architecture/externals.json")}: a file references a system when it imports the system's SDK, contains its host in a string literal (a configuration preset counts), or is mapped to it explicitly. Type-only imports are not counted as dependencies.`,
    [
      section("Clusters", mdTable(["Cluster", "Title", "Files", "Depends on", "Used by", "External systems referenced"], clusterRows)),
      section("External systems", mdTable(["System", "Title", "Kind", "Clusters", "Files"], systemRows)),
      section("Files by cluster", ...clusterSections),
    ],
  );
}

function renderEnv(graph: AtlasGraph): string {
  const { env } = graph;
  const declared = env.server.filter((v) => v.declared);
  const undeclared = env.server.filter((v) => !v.declared);
  return page(
    "Environment variables",
    `The server validates its environment once, at boot, in ${code(env.schemaFile)}. A variable marked "required" without a default crashes the process when it is missing.`,
    [
      section(
        `Validated in ${code(env.schemaFile)}`,
        mdTable(
          ["Variable", "Required", "Default", "Read by"],
          declared.map((v) => [code(v.name), v.required ? "yes" : "no", v.defaultValue === null ? "—" : code(v.defaultValue), codeList(v.usedBy)]),
        ),
      ),
      section(
        "Read directly from process.env (not validated)",
        mdTable(["Variable", "Read by"], undeclared.map((v) => [code(v.name), codeList(v.usedBy)])),
      ),
      section(
        "Declared but never read outside the schema",
        codeList(declared.filter((v) => v.usedBy.length === 0).map((v) => v.name)),
      ),
      section("Frontend (Vite)", mdTable(["Variable", "Read by"], env.frontend.map((v) => [code(v.name), codeList(v.usedBy)]))),
    ],
  );
}

function renderReadme(graph: AtlasGraph): string {
  const { database, api, entrypoints, frontend, modules, env } = graph;
  const procedures = api.routers.flatMap((router) => router.procedures);
  const usedSystems = uniqSorted(modules.flatMap((m) => m.externals));
  const summary = mdTable(
    ["Fact", "Count"],
    [
      ["Tables", String(database.tables.length)],
      ["Tables with relations", String(new Set(database.relations.map((r) => r.table)).size)],
      ["Foreign-key constraints", String(database.tables.reduce((total, t) => total + t.foreignKeys, 0))],
      ["tRPC routers", String(api.routers.length)],
      ["tRPC procedures", String(procedures.length)],
      ["— queries", String(procedures.filter((p) => p.kind === "query").length)],
      ["— mutations", String(procedures.filter((p) => p.kind === "mutation").length)],
      ["Procedure builders", String(api.builders.length)],
      ["HTTP routes (outside tRPC)", String(entrypoints.routes.filter((r) => r.kind !== "trpc").length)],
      ["WebSocket upgrade prefixes", String(entrypoints.websockets.length)],
      ["Scheduled jobs", String(entrypoints.jobs.length)],
      ["Browser routes", String(frontend.routes.length)],
      ["Lazy-loaded pages", String(frontend.pages.length)],
      ["Runtime source files", String(modules.length)],
      ["Clusters", String(graph.clusters.length)],
      ["External systems in use", String(usedSystems.length)],
      ["Validated server env vars", String(env.server.filter((v) => v.declared).length)],
    ],
  );
  const files = mdTable(
    ["File", "Answers"],
    [
      ["[api.md](api.md)", "Which procedures exist, who may call them, which tables they touch, which web files call them"],
      ["[database.md](database.md)", "Tables, storage classes, relations, and which files read or write each table"],
      ["[entrypoints.md](entrypoints.md)", "Middleware order, HTTP routes, webhooks, SSE, WebSocket upgrades, scheduled jobs"],
      ["[frontend.md](frontend.md)", "Browser routes, route guards, and the procedures each page uses"],
      ["[modules.md](modules.md)", "Code clusters, dependencies between them, external systems"],
      ["[env.md](env.md)", "Environment variables: validated, unvalidated, unused"],
    ],
  );
  const warnings =
    graph.warnings.length === 0
      ? "None."
      : graph.warnings.map((warning) => `- ${warning}`).join("\n");

  return page(
    "Atlas",
    [
      "Facts about SmartSpend extracted from the source code by `scripts/atlas`. Nothing here is written by hand.",
      "- Regenerate after changing code: `npm run atlas`.",
      "- `npm run atlas:check` (part of `npm run check`) fails when any file here no longer matches the code.",
      "- On a merge conflict inside this folder, do not resolve it by hand: take either side and run `npm run atlas`.",
    ].join("\n"),
    [
      section("Files", files),
      section("Summary", summary),
      section(
        "Generator warnings",
        "Gaps the generator found between the code and the hand-maintained maps in `docs/architecture/`, or code patterns it cannot read.",
        warnings,
      ),
    ],
  );
}

export function renderAtlas(graph: AtlasGraph): Map<string, string> {
  return new Map([
    [`${ATLAS_DIR}/README.md`, renderReadme(graph)],
    [`${ATLAS_DIR}/api.md`, renderApi(graph)],
    [`${ATLAS_DIR}/database.md`, renderDatabase(graph)],
    [`${ATLAS_DIR}/entrypoints.md`, renderEntrypoints(graph)],
    [`${ATLAS_DIR}/env.md`, renderEnv(graph)],
    [`${ATLAS_DIR}/frontend.md`, renderFrontend(graph)],
    [`${ATLAS_DIR}/modules.md`, renderModules(graph)],
  ]);
}
