/**
 * `docs/atlas/systems/state.md` and `state.ar.md`: where the project stands, generated from the explanations.
 *
 * Every system page already carries the two things a reader needs to decide what to do next — how recently it
 * was checked against the code, and the issues it names — but they sit in thirteen files, so nobody sees the
 * whole. These pages gather them: one table of systems, then every known issue grouped by system, in English
 * for agents and in Egyptian Arabic for the owner.
 *
 * Nothing here is written by hand and nothing comes from git history, so the pages are a pure function of the
 * repository and stay true through the same hooks that keep the rest of the atlas true.
 */
import fs from "node:fs";
import path from "node:path";
import type { AtlasGraph } from "../graph";
import { REPO_ROOT, mdTable } from "../lib/util";
import { fingerprint, narrativePath, plainPath, readLedger, readText } from "../../knowledge/systems-docs";

const BANNER =
  "<!-- GENERATED by `npm run atlas` from the system pages and docs/systems/verified.json. Do not edit: the next run overwrites this file. -->";

/** Headings that introduce the issues an explanation lists, in each language. */
const ISSUES_HEADING = { en: "## Known issues", ar: "## حاجات مهم تعرفها" };
const TESTS_HEADING = "## Tests";

/**
 * The lines of one `## ` section, without its heading.
 *
 * Matched on the start of the heading, because a page may widen it — "Tests and benchmarks" is still the
 * tests section, and an exact match would silently report that a well-tested system has no tests.
 */
function section(text: string, heading: string): string[] {
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((line) => line.trim().startsWith(heading));
  if (start === -1) return [];
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((line) => line.startsWith("## "));
  return end === -1 ? rest : rest.slice(0, end);
}

/**
 * The numbered items of a section, each one folded back into a single line.
 *
 * A known issue is written across as many lines as it needs; a list that keeps those line breaks would render
 * as a different list here, so continuation lines are joined back to the item they belong to.
 */
function numberedItems(lines: string[]): string[] {
  const items: string[] = [];
  for (const line of lines) {
    const start = /^\s*\d+\.\s+(.*)$/.exec(line);
    if (start) {
      items.push(start[1].trim());
      continue;
    }
    if (items.length > 0 && line.trim() && /^\s/.test(line)) {
      items[items.length - 1] += ` ${line.trim()}`;
    }
  }
  return items;
}

/** Test files an explanation names, which the documentation rules already hold to files that exist. */
function testsNamed(text: string): string[] {
  const body = section(text, TESTS_HEADING).join(" ");
  return [...new Set([...body.matchAll(/`([^`]+\.test\.tsx?)`/g)].map((match) => match[1]))];
}

interface SystemState {
  id: string;
  title: string;
  titleAr: string;
  checked: string;
  arabicChecked: string;
  arabicInLine: boolean;
  tests: string[];
  issues: string[];
  issuesAr: string[];
}

function collect(graph: AtlasGraph): SystemState[] {
  const ledger = (() => {
    try {
      return readLedger(REPO_ROOT);
    } catch {
      return { systems: {} };
    }
  })();

  return graph.systems.systems.map((system) => {
    const english = readText(REPO_ROOT, narrativePath(system.id)) ?? "";
    const arabic = readText(REPO_ROOT, plainPath(system.id)) ?? "";
    const entry = ledger.systems[system.id];
    return {
      id: system.id,
      title: system.title,
      titleAr: system.titleAr,
      checked: entry?.checked ?? "",
      arabicChecked: entry?.arabicChecked ?? "",
      arabicInLine: Boolean(english) && entry?.arabic === fingerprint(english),
      tests: testsNamed(english),
      issues: numberedItems(section(english, ISSUES_HEADING.en)),
      issuesAr: numberedItems(section(arabic, ISSUES_HEADING.ar)),
    };
  });
}

function renderEnglish(states: SystemState[]): string {
  const total = states.reduce((sum, state) => sum + state.issues.length, 0);
  const untested = states.filter((state) => state.tests.length === 0);

  const backlog = states
    .filter((state) => state.issues.length > 0)
    .map((state) =>
      [
        `### ${state.title} — [docs/systems/${state.id}.md](../../systems/${state.id}.md)`,
        ...state.issues.map((issue, index) => `${index + 1}. ${issue}`),
      ].join("\n"),
    );

  return `${[
    BANNER,
    "# Project state",
    [
      "What each part of the product is worth looking at now, gathered from the explanations themselves: how recently each one was checked against the code, whether its Arabic page is in line, the tests it names, and every issue it lists.",
      "An issue below was located in the code when the page was written, and the page is re-checked whenever that code changes — but check it again in the code before you act on it.",
    ].join("\n\n"),
    ["## Systems", mdTable(
      ["System", "Explanation checked", "Arabic page", "Tests it names", "Known issues"],
      states.map((state) => [
        `[${state.title}](${state.id}.md)<br/>${state.titleAr}`,
        state.checked || "not recorded",
        state.arabicInLine ? state.arabicChecked || "in line" : "behind the English page",
        state.tests.length === 0 ? "**none**" : String(state.tests.length),
        state.issues.length === 0 ? "none listed" : String(state.issues.length),
      ]),
    )].join("\n\n"),
    [
      "## Where the risk is",
      untested.length === 0
        ? "Every system's explanation names at least one test."
        : `These systems' explanations name no test at all, so nothing fails when they break: ${untested
            .map((state) => `[${state.title}](${state.id}.md)`)
            .join(", ")}.`,
    ].join("\n\n"),
    [
      `## What is waiting (${total} issue(s))`,
      "Every known issue the explanations list, system by system. Fixing one means correcting its page in the same change, which `npm run agent:finish` will ask for.",
      ...backlog,
    ].join("\n\n"),
  ].join("\n\n")}\n`;
}

function renderArabic(states: SystemState[]): string {
  const total = states.reduce((sum, state) => sum + state.issuesAr.length, 0);
  const untested = states.filter((state) => state.tests.length === 0);

  const backlog = states
    .filter((state) => state.issuesAr.length > 0)
    .map((state) =>
      [
        `### ${state.titleAr} — [الصفحة بالعربي](../../ar/systems/${state.id}.md)`,
        ...state.issuesAr.map((issue, index) => `${index + 1}. ${issue}`),
      ].join("\n"),
    );

  return `${[
    BANNER,
    "# حالة المشروع",
    [
      "الصفحة دي بتتولّد لوحدها من صفحات الأنظمة، وبتقولك في مكان واحد: كل نظام اتراجع شرحه إمتى، والصفحة العربي بتاعته متأخرة ولا لأ، وعنده كام اختبار، وإيه المشاكل المعروفة فيه.",
      "المشاكل المكتوبة تحت كلها اتلقت في الكود وقت كتابة الصفحة، وأي تعديل في نفس الكود بيخلي الشرح يتراجع تاني. دي قايمة الشغل اللي قدامك.",
    ].join("\n\n"),
    ["## الأنظمة", mdTable(
      ["النظام", "آخر مراجعة للشرح", "الصفحة العربي", "اختبارات مذكورة", "مشاكل معروفة"],
      states.map((state) => [
        `[${state.titleAr}](../../ar/systems/${state.id}.md)`,
        state.checked || "مش متسجل",
        state.arabicInLine ? state.arabicChecked || "متطابقة" : "متأخرة عن الإنجليزي",
        state.tests.length === 0 ? "**ولا واحد**" : String(state.tests.length),
        state.issuesAr.length === 0 ? "مفيش" : String(state.issuesAr.length),
      ]),
    )].join("\n\n"),
    [
      "## فين الخطر",
      untested.length === 0
        ? "كل الأنظمة عندها اختبارات مذكورة في شرحها."
        : `الأنظمة دي مالهاش أي اختبار، يعني لو باظت محدش هيعرف غير لما المستخدم يشتكي: ${untested
            .map((state) => `[${state.titleAr}](../../ar/systems/${state.id}.md)`)
            .join("، ")}.`,
    ].join("\n\n"),
    [
      `## اللي مستني شغل (${total} حاجة)`,
      "كل المشاكل المعروفة مجمّعة من صفحات الأنظمة. لو عايز تطلب إصلاح واحدة، قول للـagent: «اقرا صفحة النظام الفلاني وصلّح المشكلة رقم كذا».",
      ...backlog,
    ].join("\n\n"),
  ].join("\n\n")}\n`;
}

/** The two state pages, keyed by the file they belong in. */
export function renderState(graph: AtlasGraph, dir: string): Map<string, string> {
  const states = collect(graph);
  return new Map([
    [`${dir}/state.md`, renderEnglish(states)],
    [`${dir}/state.ar.md`, renderArabic(states)],
  ]);
}

/** Reads a page straight from disk; used by the tests that check the parsers. */
export function readPage(file: string): string {
  return fs.readFileSync(path.join(REPO_ROOT, file), "utf8");
}

export const __testing = { section, numberedItems, testsNamed };
