/**
 * One facts page per system in docs/architecture/systems.json, plus an index, written to docs/atlas/systems/.
 *
 * A page draws what the system is made of (screens, API, routes and jobs, code modules, tables, outside
 * systems and the other systems it depends on) and the journeys drawn for it in docs/architecture/flows,
 * then lists the same facts in tables. Mermaid diagrams render on GitHub, so anyone can read them without
 * tools. The explanation in prose sits beside these pages: docs/systems/<id>.md for engineers and agents,
 * docs/ar/systems/<id>.md for everyone else.
 */
import fs from "node:fs";
import path from "node:path";
import type { AtlasGraph } from "../graph";
import { REST_OF_FILE, routeKey, type SystemFacts } from "../extract/systems";
import { REPO_ROOT, code, codeList, compareStrings, mdTable, uniqSorted } from "../lib/util";
import { parseArchitectureModel } from "../../knowledge/flows-rules";
import { endpointId, safeId, socketId } from "./likec4";
import { renderState } from "./state";

export const SYSTEMS_DIR = "docs/atlas/systems";

const BANNER =
  "<!-- GENERATED by `npm run atlas` from the source code and docs/architecture/systems.json. Do not edit: the next run overwrites this file. -->";

/**
 * When each explanation was last recorded as checked, from docs/systems/verified.json.
 *
 * Read here rather than computed, so the index answers "how recent is this page?" without anyone maintaining
 * a second list. A system with no record yet says so plainly instead of pretending.
 */
function lastChecked(): Map<string, { english: string; arabic: string }> {
  const out = new Map<string, { english: string; arabic: string }>();
  try {
    const raw = fs.readFileSync(path.join(REPO_ROOT, "docs/systems/verified.json"), "utf8");
    const systems = (JSON.parse(raw) as { systems?: Record<string, { checked?: string; arabicChecked?: string }> }).systems ?? {};
    for (const [id, entry] of Object.entries(systems)) {
      out.set(id, { english: entry.checked ?? "", arabic: entry.arabicChecked ?? "" });
    }
  } catch {
    // No record yet, or a file left mid-merge: the column says "not recorded".
  }
  return out;
}

/** Files nearly every request passes through; drawing them would connect every system to every other. */
const SHARED_FILES = new Set(["api/middleware.ts", "api/queries/connection.ts", "db/schema.ts"]);
/** Every system runs on these two, so the overview leaves out their arrows. */
const FOUNDATION = new Set(["platform", "web-app"]);
/** Above this many tables a system only reads, its diagram shows one summary node instead. */
const MAX_READ_TABLES_DRAWN = 8;

interface PageLike {
  name: string;
  file: string;
  calls: AtlasGraph["frontend"]["calls"];
}

interface Flow {
  id: string;
  file: string;
  title: string;
  description: string;
  steps: Array<{ source: string; target: string; reverse: boolean; label: string }>;
}

const quote = (text: string) => `"${text.replace(/"/g, "#quot;").replace(/\r?\n/g, " ")}"`;
const nodeId = (prefix: string, raw: string) => `${prefix}_${raw.replace(/[^A-Za-z0-9]/g, "_")}`;
const mermaid = (lines: string[]) => ["```mermaid", ...lines, "```"].join("\n");
const sequenceText = (text: string) => text.replace(/[;#]/g, ",").replace(/\r?\n/g, " ");

function section(title: string, ...parts: string[]): string {
  return [`## ${title}`, ...parts.map((part) => part.trim()).filter(Boolean)].join("\n\n");
}

function pagesOf(graph: AtlasGraph): PageLike[] {
  return [graph.frontend.shell, ...graph.frontend.pages].map((page) => ({ name: page.name, file: page.file, calls: page.calls }));
}

function screenTitle(graph: AtlasGraph, page: string): string {
  return page === graph.frontend.shell.name ? "App shell" : `${page} screen`;
}

// ── Flows ──────────────────────────────────────────────────────────────────────

const NAME = String.raw`[A-Za-z_][\w-]*(?:\.[A-Za-z_][\w-]*)*`;
const STEP_LINE = new RegExp(String.raw`^\s*(${NAME})\s+(->|<-)\s+(${NAME})(?:\s+'((?:[^'\\]|\\.)*)')?`);

function readFlows(): Flow[] {
  const dir = path.join(REPO_ROOT, "docs", "architecture", "flows");
  if (!fs.existsSync(dir)) return [];
  const flows: Flow[] = [];
  for (const name of fs.readdirSync(dir).filter((file) => file.endsWith(".c4")).sort(compareStrings)) {
    let current: Flow | null = null;
    for (const raw of fs.readFileSync(path.join(dir, name), "utf8").replace(/\r\n/g, "\n").split("\n")) {
      const view = /^\s*dynamic\s+view\s+([\w-]+)/.exec(raw);
      if (view) {
        current = { id: view[1], file: `docs/architecture/flows/${name}`, title: "", description: "", steps: [] };
        flows.push(current);
        continue;
      }
      if (!current) continue;
      const title = /^\s*title\s+'((?:[^'\\]|\\.)*)'/.exec(raw);
      if (title) {
        current.title = title[1];
        continue;
      }
      const description = /^\s*description\s+'((?:[^'\\]|\\.)*)'/.exec(raw);
      if (description) {
        current.description = description[1];
        continue;
      }
      const step = STEP_LINE.exec(raw);
      if (step) current.steps.push({ source: step[1], target: step[3], reverse: step[2] === "<-", label: step[4] ?? "" });
    }
  }
  return flows;
}

/** A readable name for a model element used in a flow. */
function participantLabeler(graph: AtlasGraph): (name: string) => string {
  const contextFile = "docs/architecture/context.c4";
  const contextPath = path.join(REPO_ROOT, contextFile);
  const contextTitles = fs.existsSync(contextPath)
    ? new Map(
        [...parseArchitectureModel([{ file: contextFile, text: fs.readFileSync(contextPath, "utf8") }]).elements.values()].map(
          (element) => [element.name, element.title],
        ),
      )
    : new Map<string, string>();
  const clusterTitle = new Map(graph.clusters.map((cluster) => [safeId(cluster.id), cluster.title]));
  const routeTitle = new Map(graph.entrypoints.routes.map((route) => [endpointId(route.method, route.path), routeKey(route)]));
  const socketTitle = new Map(graph.entrypoints.websockets.map((socket) => [socketId(socket.pathPrefix), socket.pathPrefix]));
  const externalTitle = new Map(graph.externals.systems.map((system) => [safeId(system.id), system.title]));

  return (name) => {
    const parts = name.split(".");
    if (name.startsWith("smartspend.web.pages.")) return `${parts[3]} screen`;
    if (name === "smartspend.web.shell") return "App shell";
    if (name.startsWith("smartspend.api.trpc.")) return parts.slice(3).join(".");
    if (/^smartspend\.(api|web)\.modules\./.test(name)) return clusterTitle.get(parts[3]) ?? parts[3];
    if (name.startsWith("smartspend.mysql.")) return `${parts[2]} table`;
    if (name.startsWith("smartspend.api.http.")) return routeTitle.get(parts[3]) ?? parts[3];
    if (name.startsWith("smartspend.api.ws.")) return `WebSocket ${socketTitle.get(parts[3]) ?? parts[3]}`;
    if (name.startsWith("smartspend.api.scheduler.")) return `Job ${parts[3]}`;
    return contextTitles.get(name) ?? externalTitle.get(parts[parts.length - 1]) ?? parts[parts.length - 1];
  };
}

function flowDiagram(flow: Flow, labelOf: (name: string) => string): string {
  const participants = new Map<string, string>();
  const idOf = (name: string) => {
    if (!participants.has(name)) participants.set(name, `p${participants.size + 1}`);
    return participants.get(name)!;
  };
  const messages = flow.steps.map((step) => {
    // A reverse step `a <- b` is b's reply to a.
    const from = idOf(step.reverse ? step.target : step.source);
    const to = idOf(step.reverse ? step.source : step.target);
    return `  ${from}${step.reverse ? "-->>" : "->>"}${to}: ${sequenceText(step.label || "...")}`;
  });
  return mermaid([
    "sequenceDiagram",
    ...[...participants].map(([name, id]) => `  participant ${id} as ${sequenceText(labelOf(name))}`),
    ...messages,
  ]);
}

// ── Ownership and dependencies ─────────────────────────────────────────────────

function systemDependencies(graph: AtlasGraph): Map<string, Set<string>> {
  const owner = graph.systems.owner;
  const dependencies = new Map(graph.systems.systems.map((system) => [system.id, new Set<string>()]));
  const add = (from: string | undefined, to: string | undefined) => {
    if (from && to && from !== to) dependencies.get(from)?.add(to);
  };
  const useFile = (from: string | undefined, file: string) => {
    if (!SHARED_FILES.has(file)) add(from, owner.file.get(file));
  };
  for (const module of graph.modules) for (const file of module.imports) useFile(owner.file.get(module.file), file);
  for (const router of graph.api.routers) {
    for (const procedure of router.procedures) for (const file of procedure.uses) useFile(owner.procedure.get(procedure.path), file);
  }
  for (const route of graph.entrypoints.routes) for (const file of route.uses) useFile(owner.route.get(routeKey(route)), file);
  for (const job of graph.entrypoints.jobs) for (const file of job.uses) useFile(owner.job.get(job.name), file);
  for (const socket of graph.entrypoints.websockets) {
    if (socket.handlerFile) useFile(owner.websocket.get(socket.pathPrefix), socket.handlerFile);
  }
  for (const page of pagesOf(graph)) {
    for (const call of page.calls) {
      if (call.procedure) add(owner.page.get(page.name), owner.procedure.get(`${call.router}.${call.procedure}`));
    }
  }
  return dependencies;
}

// ── One system ─────────────────────────────────────────────────────────────────

function systemDiagram(graph: AtlasGraph, system: SystemFacts): string {
  const owner = graph.systems.owner;
  const clusterOfFile = new Map(graph.modules.map((module) => [module.file, module.cluster]));
  const clusterTitle = new Map(graph.clusters.map((cluster) => [cluster.id, cluster.title]));
  const systemTitle = new Map(graph.systems.systems.map((entry) => [entry.id, entry.title]));
  const externalTitle = new Map(graph.externals.systems.map((entry) => [entry.id, entry.title]));

  const groups = {
    screens: new Map<string, string>(),
    api: new Map<string, string>(),
    modules: new Map<string, string>(),
    tables: new Map<string, string>(),
  };
  const outside = new Map<string, string>();
  const edges = new Set<string>();
  const link = (from: string, arrow: string, to: string) => {
    if (from !== to) edges.add(`  ${from} ${arrow} ${to}`);
  };

  const written = new Set<string>();
  const writeEdges = new Set<string>();
  const readEdges: Array<[string, string]> = [];
  const touch = (from: string, read: string[], write: string[]) => {
    for (const table of write) {
      written.add(table);
      writeEdges.add(`${from} ${table}`);
      link(from, "==>", nodeId("tbl", table));
    }
    for (const table of read) readEdges.push([from, table]);
  };
  const dependOn = (from: string, file: string) => {
    if (SHARED_FILES.has(file)) return;
    const fileOwner = owner.file.get(file);
    if (!fileOwner) return;
    if (fileOwner === system.id) {
      const cluster = clusterOfFile.get(file)!;
      const id = nodeId("mod", cluster);
      groups.modules.set(id, `${id}[${quote(clusterTitle.get(cluster) ?? cluster)}]`);
      link(from, "-->", id);
    } else {
      const id = nodeId("sys", fileOwner);
      outside.set(id, `${id}[[${quote(`${systemTitle.get(fileOwner)} (system)`)}]]`);
      link(from, "-->", id);
    }
  };

  for (const page of pagesOf(graph)) {
    const pageOwner = owner.page.get(page.name);
    for (const call of page.calls) {
      if (!call.procedure || owner.procedure.get(`${call.router}.${call.procedure}`) !== system.id || !pageOwner) continue;
      const from = pageOwner === system.id ? nodeId("page", page.name) : nodeId("screens", pageOwner);
      const title = pageOwner === system.id ? screenTitle(graph, page.name) : `Screens of ${systemTitle.get(pageOwner)}`;
      groups.screens.set(from, `${from}[${quote(title)}]`);
      link(from, "-->", nodeId("router", call.router));
    }
  }
  for (const page of system.pages) {
    const id = nodeId("page", page);
    groups.screens.set(id, `${id}[${quote(screenTitle(graph, page))}]`);
  }

  const proceduresPerRouter = new Map<string, number>();
  for (const router of graph.api.routers) {
    for (const procedure of router.procedures) {
      if (owner.procedure.get(procedure.path) !== system.id) continue;
      proceduresPerRouter.set(router.key, (proceduresPerRouter.get(router.key) ?? 0) + 1);
      const from = nodeId("router", router.key);
      for (const file of procedure.uses) dependOn(from, file);
      touch(from, procedure.read, procedure.write);
    }
  }
  for (const [key, count] of proceduresPerRouter) {
    const id = nodeId("router", key);
    groups.api.set(id, `${id}[${quote(`${key} API · ${count} procedure${count === 1 ? "" : "s"}`)}]`);
  }

  const routeGroups = new Map<string, AtlasGraph["entrypoints"]["routes"]>();
  for (const route of graph.entrypoints.routes) {
    if (owner.route.get(routeKey(route)) !== system.id) continue;
    const prefix = route.path.split("/").slice(0, 3).join("/");
    routeGroups.set(prefix, [...(routeGroups.get(prefix) ?? []), route]);
  }
  for (const [prefix, routes] of routeGroups) {
    const id = nodeId("http", prefix);
    const title = routes.length === 1 ? routeKey(routes[0]) : `HTTP ${prefix}/… · ${routes.length} routes`;
    groups.api.set(id, `${id}[${quote(title)}]`);
    for (const route of routes) {
      for (const file of route.uses) dependOn(id, file);
      touch(id, route.read, route.write);
    }
  }

  for (const socket of graph.entrypoints.websockets) {
    if (owner.websocket.get(socket.pathPrefix) !== system.id) continue;
    const id = nodeId("ws", socket.pathPrefix);
    groups.api.set(id, `${id}[${quote(`WebSocket ${socket.pathPrefix}`)}]`);
    if (socket.handlerFile) dependOn(id, socket.handlerFile);
  }

  for (const job of graph.entrypoints.jobs) {
    if (owner.job.get(job.name) !== system.id) continue;
    const id = nodeId("job", job.name);
    groups.api.set(id, `${id}[${quote(`Job · ${job.name}`)}]`);
    for (const file of job.uses) dependOn(id, file);
    touch(id, job.read, job.write);
  }

  for (const module of graph.modules) {
    if (owner.file.get(module.file) !== system.id) continue;
    const id = nodeId("mod", module.cluster);
    groups.modules.set(id, `${id}[${quote(clusterTitle.get(module.cluster) ?? module.cluster)}]`);
    for (const file of module.imports) dependOn(id, file);
    touch(id, module.read, module.write);
    for (const external of module.externals) {
      const externalId = nodeId("ext", external);
      outside.set(externalId, `${externalId}{{${quote(externalTitle.get(external) ?? external)}}}`);
      link(id, "-->", externalId);
    }
  }

  for (const table of written) {
    const id = nodeId("tbl", table);
    groups.tables.set(id, `${id}[(${quote(table)})]`);
  }
  const readOnly = uniqSorted(readEdges.map(([, table]) => table).filter((table) => !written.has(table)));
  for (const [from, table] of readEdges) {
    if (writeEdges.has(`${from} ${table}`)) continue;
    if (written.has(table) || readOnly.length <= MAX_READ_TABLES_DRAWN) {
      const id = nodeId("tbl", table);
      groups.tables.set(id, `${id}[(${quote(table)})]`);
      link(from, "-.->", id);
    } else {
      groups.tables.set("tbl_more", `tbl_more[(${quote(`${readOnly.length} tables it only reads, listed under Data`)})]`);
      link(from, "-.->", "tbl_more");
    }
  }

  const group = (id: string, title: string, entries: Map<string, string>) =>
    entries.size === 0
      ? []
      : [`  subgraph ${id}[${quote(title)}]`, ...[...entries.values()].sort(compareStrings).map((line) => `    ${line}`), "  end"];
  return mermaid([
    "flowchart LR",
    ...group("g_screens", "Screens", groups.screens),
    ...group("g_api", "API, routes and jobs", groups.api),
    ...group("g_modules", "Code modules", groups.modules),
    ...group("g_tables", "MySQL tables", groups.tables),
    ...[...outside.values()].sort(compareStrings).map((line) => `  ${line}`),
    ...[...edges].sort(compareStrings),
  ]);
}

function renderSystem(
  graph: AtlasGraph,
  system: SystemFacts,
  flows: Flow[],
  labelOf: (name: string) => string,
  dependencies: Map<string, Set<string>>,
): string {
  const owner = graph.systems.owner;
  const systemTitle = new Map(graph.systems.systems.map((entry) => [entry.id, entry.title]));
  const clusterTitle = new Map(graph.clusters.map((cluster) => [cluster.id, cluster.title]));
  const systemLink = (id: string) => `[${systemTitle.get(id) ?? id}](${id}.md)`;

  const callers = new Map<string, string[]>();
  for (const page of pagesOf(graph)) {
    for (const call of page.calls) {
      if (!call.procedure) continue;
      const key = `${call.router}.${call.procedure}`;
      callers.set(key, uniqSorted([...(callers.get(key) ?? []), page.name]));
    }
  }
  const procedures = graph.api.routers
    .flatMap((router) => router.procedures)
    .filter((procedure) => owner.procedure.get(procedure.path) === system.id);
  const routes = graph.entrypoints.routes.filter((route) => owner.route.get(routeKey(route)) === system.id);
  const sockets = graph.entrypoints.websockets.filter((socket) => owner.websocket.get(socket.pathPrefix) === system.id);
  const jobs = graph.entrypoints.jobs.filter((job) => owner.job.get(job.name) === system.id);
  const members = graph.modules.filter((module) => owner.file.get(module.file) === system.id);

  const tableUse = new Map<string, { write: Set<string>; read: Set<string> }>();
  const note = (who: string, read: string[], write: string[]) => {
    for (const [tables, key] of [
      [write, "write"],
      [read, "read"],
    ] as const) {
      for (const table of tables) {
        const entry = tableUse.get(table) ?? { write: new Set<string>(), read: new Set<string>() };
        entry[key].add(who);
        tableUse.set(table, entry);
      }
    }
  };
  for (const procedure of procedures) note(procedure.path, procedure.read, procedure.write);
  for (const route of routes) note(routeKey(route), route.read, route.write);
  for (const job of jobs) note(job.name, job.read, job.write);
  for (const module of members) note(module.cluster, module.read, module.write);
  const tableClass = new Map(graph.database.tables.map((table) => [table.name, table.tableClass ?? "—"]));

  const usedBy = uniqSorted(
    [...dependencies].filter(([id, targets]) => id !== system.id && targets.has(system.id)).map(([id]) => id),
  );
  const externals = uniqSorted(members.flatMap((module) => module.externals));
  const externalInfo = new Map(graph.externals.systems.map((entry) => [entry.id, entry]));
  const files = new Set(system.files);
  const serverEnv = graph.env.server.filter((variable) => variable.usedBy.some((file) => files.has(file)));
  const frontendEnv = graph.env.frontend.filter((variable) => variable.usedBy.some((file) => files.has(file)));
  const ownFlows = flows.filter((flow) => system.flows.includes(flow.id));

  return `${[
    BANNER,
    `# ${system.title}`,
    system.summary,
    `How it works: [docs/systems/${system.id}.md](../../systems/${system.id}.md) · بالعربي: [docs/ar/systems/${system.id}.md](../../ar/systems/${system.id}.md) · [All systems](README.md)`,
    section(
      "What it is made of",
      "Solid arrows: calls and uses. Thick arrows: writes a table. Dotted arrows: reads a table. A double-bordered box is another system this one depends on.",
      systemDiagram(graph, system),
    ),
    ownFlows.length === 0
      ? ""
      : section(
          "Journeys",
          ...ownFlows.map((flow) =>
            [
              `### ${flow.title.replace(/^Flow · /, "")}`,
              flow.description,
              flowDiagram(flow, labelOf),
              `Drawn in ${code(flow.file)}; in the interactive map it is the view ${code(flow.id)}.`,
            ].join("\n\n"),
          ),
        ),
    section(
      "Code modules",
      mdTable(
        ["Module", "What it does", "Files"],
        system.clusters.map((id) => [
          `${code(id)} — ${clusterTitle.get(id) ?? id}`,
          graph.clusters.find((cluster) => cluster.id === id)?.description ?? "",
          String(members.filter((module) => module.cluster === id).length),
        ]),
      ),
    ),
    section(
      "API procedures",
      mdTable(
        ["Procedure", "Kind", "Builder", "Reads", "Writes", "Screens that call it"],
        procedures.map((procedure) => [
          code(procedure.path),
          procedure.kind,
          code(procedure.builder),
          codeList(procedure.read),
          codeList(procedure.write),
          codeList(callers.get(procedure.path) ?? []),
        ]),
      ),
    ),
    section(
      "HTTP routes, WebSockets and scheduled jobs",
      mdTable(
        ["Entry point", "Kind", "Declared in"],
        [
          ...routes.map((route) => [code(routeKey(route)), route.kind, code(route.file)]),
          ...uniqSorted(sockets.map((socket) => socket.pathPrefix)).map((prefix) => [
            code(prefix),
            "websocket",
            codeList(uniqSorted(sockets.filter((socket) => socket.pathPrefix === prefix).map((socket) => socket.file))),
          ]),
          ...jobs.map((job) => [code(job.name), job.schedule === "once at boot" ? "job, once at boot" : `job, ${code(job.schedule)}`, code(job.file)]),
        ],
      ),
    ),
    section(
      "Data",
      "Who in this system writes or reads each table: procedures, routes, jobs and code modules.",
      mdTable(
        ["Table", "Storage class", "Written by", "Read by"],
        [...tableUse.keys()].sort(compareStrings).map((table) => [
          code(table),
          tableClass.get(table) ?? "—",
          codeList(uniqSorted(tableUse.get(table)!.write)),
          codeList(uniqSorted(tableUse.get(table)!.read)),
        ]),
      ),
    ),
    section(
      "Outside systems",
      mdTable(
        ["System", "Kind", "Modules"],
        externals.map((id) => [
          externalInfo.get(id)?.title ?? id,
          externalInfo.get(id)?.kind ?? "",
          codeList(uniqSorted(members.filter((module) => module.externals.includes(id)).map((module) => module.cluster))),
        ]),
      ),
    ),
    section(
      "Other systems",
      `Depends on: ${[...(dependencies.get(system.id) ?? [])].sort(compareStrings).map(systemLink).join(", ") || "none"}.`,
      `Used by: ${usedBy.map(systemLink).join(", ") || "none"}.`,
    ),
    section(
      "Environment variables",
      mdTable(
        ["Variable", "Validated in api/lib/env.ts", "Read by"],
        [
          ...serverEnv.map((variable) => [
            code(variable.name),
            variable.declared ? "yes" : "no",
            codeList(variable.usedBy.filter((file) => files.has(file))),
          ]),
          ...frontendEnv.map((variable) => [code(variable.name), "frontend", codeList(variable.usedBy.filter((file) => files.has(file)))]),
        ],
      ),
    ),
    section(
      "Source its explanation describes",
      `When any of it changes, ${code("npm run agent:finish")} asks for a new check of ${code(`docs/systems/${system.id}.md`)}. A name after ${code("#")} is one procedure, route or job of a file that several systems share; ${code(REST_OF_FILE)} is the rest of such a file.`,
      `<details><summary>${system.coverage.length} files and declarations</summary>\n\n${system.coverage.map((unit) => `- ${code(unit.id)}`).join("\n")}\n\n</details>`,
    ),
  ]
    .map((part) => part.trim())
    .filter(Boolean)
    .join("\n\n")}\n`;
}

// ── Index ──────────────────────────────────────────────────────────────────────

function renderIndex(graph: AtlasGraph, dependencies: Map<string, Set<string>>): string {
  const systems = graph.systems.systems;
  const checked = lastChecked();
  const edges = uniqSorted(
    [...dependencies].flatMap(([from, targets]) =>
      FOUNDATION.has(from)
        ? []
        : [...targets].filter((to) => !FOUNDATION.has(to)).map((to) => `  ${nodeId("sys", from)} --> ${nodeId("sys", to)}`),
    ),
  );
  const diagram = mermaid([
    "flowchart LR",
    ...systems
      .filter((system) => !FOUNDATION.has(system.id))
      .map((system) => `  ${nodeId("sys", system.id)}[${quote(`${system.title}<br/>${system.titleAr}`)}]`),
    `  subgraph g_foundation[${quote("Everything runs on")}]`,
    ...systems
      .filter((system) => FOUNDATION.has(system.id))
      .map((system) => `    ${nodeId("sys", system.id)}[${quote(`${system.title}<br/>${system.titleAr}`)}]`),
    "  end",
    ...edges,
  ]);

  return `${[
    BANNER,
    "# Systems",
    [
      "SmartSpend split into the systems people talk about. Every code module, API procedure, screen, HTTP route, WebSocket and scheduled job belongs to exactly one of them, as set in `docs/architecture/systems.json`.",
      "Each system has three pages: how it works (`docs/systems/<id>.md`), the same story without code (`docs/ar/systems/<id>.md`), and the facts generated from the code (this folder).",
      "Before you change a file, look up its systems in [files.md](files.md) and read their explanations.",
    ].join("\n\n"),
    section(
      "How the systems depend on each other",
      "An arrow means the system on the left uses code, or calls the API, of the system on the right. The server platform and the app shell support every system, so their arrows are left out.",
      diagram,
    ),
    section(
      "The systems",
      mdTable(
        ["System", "What it does", "How it works", "بالعربي", "Facts", "Explanation last checked"],
        systems.map((system) => [
          `${system.title}<br/>${system.titleAr}`,
          system.summary,
          `[docs/systems/${system.id}.md](../../systems/${system.id}.md)`,
          `[docs/ar/systems/${system.id}.md](../../ar/systems/${system.id}.md)`,
          `[${system.id}.md](${system.id}.md)`,
          checked.get(system.id)?.english || "not recorded",
        ]),
      ),
    ),
  ]
    .map((part) => part.trim())
    .filter(Boolean)
    .join("\n\n")}\n`;
}

// ── Files ──────────────────────────────────────────────────────────────────────

/** Which system's explanation describes each source file: the reverse of every system's coverage. */
function renderFileIndex(graph: AtlasGraph): string {
  const rows = new Map<string, Map<string, string[]>>();
  for (const system of graph.systems.systems) {
    for (const unit of system.coverage) {
      const parts = rows.get(unit.file) ?? new Map<string, string[]>();
      parts.set(system.id, [...(parts.get(system.id) ?? []), unit.id === unit.file ? "" : unit.id.slice(unit.file.length + 1)]);
      rows.set(unit.file, parts);
    }
  }
  const link = (id: string) => `[${id}](${id}.md)`;
  const cell = (parts: Map<string, string[]>) => {
    const ids = [...parts.keys()].sort(compareStrings);
    const whole = ids.filter((id) => parts.get(id)!.includes(""));
    const declared = ids
      .map((id) => [id, parts.get(id)!.filter((part) => part && part !== REST_OF_FILE).sort(compareStrings)] as const)
      .filter(([, list]) => list.length > 0);
    const rest = ids.filter((id) => parts.get(id)!.includes(REST_OF_FILE));
    return [
      ...whole.map(link),
      ...declared.map(([id, list]) => `${link(id)}: ${list.map(code).join(", ")}`),
      ...(rest.length > 0 ? [`rest of the file: ${rest.map(link).join(", ")}`] : []),
    ].join(" · ");
  };

  return `${[
    BANNER,
    "# Systems by file",
    [
      "Which system's explanation describes each source file. Before you change a file, read `docs/systems/<id>.md` of its systems; after the change, `npm run agent:finish` asks for a new check of every explanation whose code changed.",
      "Most files belong to one system. A file whose procedures, routes or jobs belong to several systems is split: each declaration belongs to the system that owns it, and the rest of the file to all of them (to the server platform, for `api/boot.ts` and `api/server.ts`).",
    ].join("\n\n"),
    mdTable(
      ["File", "Systems"],
      [...rows.keys()].sort(compareStrings).map((file) => [code(file), cell(rows.get(file)!)]),
    ),
  ].join("\n\n")}\n`;
}

export function renderSystems(graph: AtlasGraph): Map<string, string> {
  const flows = readFlows();
  const labelOf = participantLabeler(graph);
  const dependencies = systemDependencies(graph);
  return new Map([
    [`${SYSTEMS_DIR}/README.md`, renderIndex(graph, dependencies)],
    [`${SYSTEMS_DIR}/files.md`, renderFileIndex(graph)],
    ...renderState(graph, SYSTEMS_DIR),
    ...graph.systems.systems.map(
      (system): [string, string] => [`${SYSTEMS_DIR}/${system.id}.md`, renderSystem(graph, system, flows, labelOf, dependencies)],
    ),
  ]);
}
