import { useState, useMemo, useEffect } from "react";
import { trpc } from "../../providers/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { motion, AnimatePresence } from "framer-motion";
import {
  Store,
  Plus,
  Trash2,
  Pencil,
  Sparkles,
  Check,
  ArrowRight,
  Loader2,
  X,
  Tag,
  TrendingUp,
  TrendingDown,
  Wallet,
  Users,
  AlertCircle,
} from "lucide-react";
import { useToast } from "@/components/ui/sonner";

const BUSINESS_TYPES = [
  { id: "restaurant", label: "مطاعم ومأكولات", icon: "🍤", desc: "مطعم، كافيه، وجبات سريعة، بقالة" },
  { id: "retail", label: "تجارة وتجزئة", icon: "🛍️", desc: "محل ملابس، سوبرماركت، مكتبة، موبايلات" },
  { id: "services", label: "خدمات وورش", icon: "🔧", desc: "نجارة، سباكة، صيانة، مغسلة" },
  { id: "freelance", label: "عمل حر", icon: "💻", desc: "برمجة، تسويق، تصميم، استشارات" },
  { id: "custom", label: "نوع آخر", icon: "✏️", desc: "اكتب نوع مشروعك بنفسك" },
];

const ICON_OPTIONS = ["🛍️", "🍤", "🔧", "💻", "📦", "💰", "🚚", "🏪", "💳", "📋", "⚙️", "🎯", "📚", "🧰", "🏭", "☕", "🍔", "🎨", "👷", "薪"];
const COLOR_OPTIONS = ["#3b82f6", "#f97316", "#ef4444", "#10b981", "#8b5cf6", "#ec4899", "#14b8a6", "#f59e0b", "#6366f1", "#84cc16"];

type WizardStep = "type" | "details" | "categories";

interface CategoryDraft {
  name: string;
  nameAr: string;
  type: string;
  icon: string;
  color: string;
  keywords: string[];
  matchExamples: string[];
  isAutoGenerated: boolean;
}

export function BusinessSettingsView({ onBack }: { onBack: () => void }) {
  const businessQuery = trpc.business.get.useQuery();
  const business = businessQuery.data?.business;
  const [showSetup, setShowSetup] = useState(false);

  if (!business && !showSetup) {
    return <BusinessWelcome onBack={onBack} onStart={() => setShowSetup(true)} />;
  }
  if (!business && showSetup) {
    return (
      <BusinessSetupWizard
        onBack={() => setShowSetup(false)}
        onSuccess={() => {
          businessQuery.refetch();
          setShowSetup(false);
        }}
      />
    );
  }
  return <BusinessDashboard business={business} categories={businessQuery.data?.categories || []} onBack={onBack} refetch={businessQuery.refetch} />;
}

// ─── Welcome ───
function BusinessWelcome({ onBack, onStart }: { onBack: () => void; onStart: () => void }) {
  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-6"
    >
      <div className="flex items-center gap-3">
        <button onClick={onBack} className="flex items-center justify-center w-10 h-10 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-900 dark:hover:bg-slate-800 transition-colors">
          <ArrowRight className="w-4.5 h-4.5 text-slate-600 dark:text-slate-400" />
        </button>
        <h1 className="text-xl font-bold text-slate-900 dark:text-white">مشروعك التجاري</h1>
      </div>

      <div className="text-center py-10">
        <motion.div
          initial={{ scale: 0.85, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ delay: 0.1, type: "spring", stiffness: 120 }}
          className="w-20 h-20 mx-auto rounded-3xl bg-gradient-to-br from-indigo-500/15 to-purple-500/15 flex items-center justify-center mb-5"
        >
          <Store className="w-9 h-9 text-indigo-600 dark:text-indigo-400" />
        </motion.div>
        <h2 className="text-xl font-bold text-slate-800 dark:text-slate-200 mb-2">عندك مشروع أو عمل خاص؟</h2>
        <p className="text-sm text-slate-500 dark:text-slate-400 max-w-sm mx-auto leading-relaxed">
          فعّل نمط المشروع وسي-tag النظام مصاريف مشروعك تلقائياً بفئات مخصصة،
          مع إحصائيات منفصلة كاملة ومرتبات للموظفين
        </p>

        <div className="mt-8 space-y-2 max-w-sm mx-auto text-right">
          {[
            { icon: "⚡", title: "تصنيف فوري", desc: "مصاريف المشروع بتتصنف بـ 0 tokens" },
            { icon: "📊", title: "Dashboard كامل", desc: "إيرادات ومصاريف وأرباح ورسوم بيانية" },
            { icon: "👷", title: "مرتبات الموظفين", desc: "اكتب \"دفعت مرتب فلان\" ويتسجل تلقائياً" },
            { icon: "👥", title: "موردين وعملاء", desc: "اربط الأشخاص بالمشروع وكل معاملة" },
            { icon: "🔀", title: "تبديل سهل", desc: "زرار واحد يبدل بين الشخصي والمشروع" },
          ].map((feat, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: 15 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.15 + i * 0.06 }}
              className="flex items-center gap-3 p-3 rounded-xl bg-white/60 dark:bg-slate-900/30 border border-slate-200/50 dark:border-slate-800/60"
            >
              <span className="text-xl shrink-0">{feat.icon}</span>
              <div className="flex-1 text-right">
                <h4 className="text-xs font-bold text-slate-700 dark:text-slate-300">{feat.title}</h4>
                <p className="text-[10px] text-slate-400 dark:text-slate-500">{feat.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>

        <Button onClick={onStart} className="mt-8 rounded-xl gap-2 px-8" size="lg">
          <Store className="w-5 h-5" />
          فلنبدأ الإعداد
        </Button>
      </div>
    </motion.div>
  );
}

// ─── Setup Wizard ───
function BusinessSetupWizard({ onBack, onSuccess }: { onBack: () => void; onSuccess: () => void }) {
  const { toast } = useToast();
  const utils = trpc.useUtils();
  const [step, setStep] = useState<WizardStep>("type");
  const [bizType, setBizType] = useState("");
  const [bizTypeLabel, setBizTypeLabel] = useState("");
  const [bizName, setBizName] = useState("");
  const [description, setDescription] = useState("");
  const [suggestedCategories, setSuggestedCategories] = useState<CategoryDraft[]>([]);
  const [isSuggesting, setIsSuggesting] = useState(false);

  const suggestMutation = trpc.business.suggestCategories.useMutation({
    onSuccess: (data) => {
      setSuggestedCategories(data.categories.map((c: any) => ({
        name: c.name, nameAr: c.nameAr, type: c.type, icon: c.icon,
        color: c.color, keywords: c.keywords, matchExamples: c.matchExamples,
        isAutoGenerated: true,
      })));
      setIsSuggesting(false);
      setStep("categories");
    },
    onError: () => {
      setIsSuggesting(false);
      // Fallback: create default categories based on business type
      const defaults = getFallbackCategories(bizType);
      setSuggestedCategories(defaults);
      setStep("categories");
      toast({ title: "استخدمنا فئات افتراضية. تقدر تعدلها." });
    },
  });

  const createMutation = trpc.business.create.useMutation({
    onSuccess: () => {
      utils.business.get.invalidate();
      toast({ title: "تم إنشاء المشروع! 🎉" });
      onSuccess();
    },
    onError: (err) => toast({ title: err.message, variant: "error" }),
  });

  const handleSuggest = () => {
    setIsSuggesting(true);
    suggestMutation.mutate({
      description, businessName: bizName, businessType: bizTypeLabel || bizType,
    });
  };

  const handleCreate = () => {
    createMutation.mutate({
      name: bizName, type: bizType, typeLabel: bizTypeLabel, description,
      categories: suggestedCategories.map(c => ({
        name: c.name, nameAr: c.nameAr,
        type: c.type as "expense" | "income" | "both",
        icon: c.icon, color: c.color,
        keywords: c.keywords, matchExamples: c.matchExamples,
        isAutoGenerated: c.isAutoGenerated,
      })),
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-5"
    >
      {/* Header + Progress */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => step === "type" ? onBack() : step === "details" ? setStep("type") : setStep("details")}
          className="flex items-center justify-center w-10 h-10 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-900 dark:hover:bg-slate-800 transition-colors"
        >
          <ArrowRight className="w-4.5 h-4.5 text-slate-600 dark:text-slate-400" />
        </button>
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white">إعداد المشروع</h1>
          <p className="text-[11px] text-slate-400 mt-0.5">
            {step === "type" && "خطوة 1/3: نوع المشروع"}
            {step === "details" && "خطوة 2/3: بيانات المشروع"}
            {step === "categories" && "خطوة 3/3: الفئات"}
          </p>
        </div>
      </div>

      <div className="flex gap-1.5">
        {["type", "details", "categories"].map((s, i) => (
          <div key={s} className={`h-1.5 flex-1 rounded-full transition-all ${
            step === s ? "bg-indigo-500" : ["type", "details", "categories"].indexOf(step) > i ? "bg-emerald-500" : "bg-slate-200 dark:bg-slate-800"
          }`} />
        ))}
      </div>

      <AnimatePresence mode="wait">
        {/* Step 1: Type */}
        {step === "type" && (
          <motion.div key="type" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="space-y-3">
            <div className="grid grid-cols-2 gap-2.5">
              {BUSINESS_TYPES.map((type) => (
                <button
                  key={type.id}
                  onClick={() => { setBizType(type.id); setBizTypeLabel(type.label); }}
                  className={`p-4 rounded-2xl border-2 text-center transition-all ${
                    bizType === type.id
                      ? "border-indigo-500 bg-indigo-50/50 dark:bg-indigo-950/20 shadow-md"
                      : "border-slate-200/60 dark:border-slate-800/80 bg-white/50 dark:bg-slate-900/30 hover:border-slate-300 dark:hover:border-slate-700"
                  }`}
                >
                  <div className="text-3xl mb-2">{type.icon}</div>
                  <h4 className="font-bold text-xs text-slate-800 dark:text-slate-200">{type.label}</h4>
                  <p className="text-[10px] text-slate-400 mt-1">{type.desc}</p>
                </button>
              ))}
            </div>
            {bizType === "custom" && (
              <Input
                placeholder="اكتب نوع مشروعك..."
                value={bizTypeLabel}
                onChange={(e) => setBizTypeLabel(e.target.value)}
                className="rounded-xl text-right"
              />
            )}
            <Button className="w-full rounded-xl" disabled={!bizType || (bizType === "custom" && !bizTypeLabel.trim())} onClick={() => setStep("details")}>
              التالي
            </Button>
          </motion.div>
        )}

        {/* Step 2: Details */}
        {step === "details" && (
          <motion.div key="details" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="space-y-3">
            <div>
              <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">اسم المشروع</label>
              <Input value={bizName} onChange={(e) => setBizName(e.target.value)} placeholder={bizType === "freelance" ? "مثال: شغل الجرافيك والتسويق" : "مثال: مطعم السمكة الذهبية"} className="rounded-xl text-right" />
            </div>
            <div>
              <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">
                وصف {bizType === "freelance" ? "العمل" : "المشروع"} <span className="text-slate-400">(هيستخدم لتوليد فئات مخصصة)</span>
              </label>
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder={bizType === "freelance" ? "اوصف شغلك... مثال: بشتغل مصمم جرافيك حر، بقبض بالدولار أو المصري، وبصرف على إعلانات فيسبوك واشتراكات برامج التصميم وكهرباء." : "اوصف مشروعك... مثال: مطعم سمك وبنشتري بضاعة يومياً من سوق العبور وبنصرف على ثلاجات وعمال وتوصيل"}
                className="rounded-xl text-right min-h-[100px] resize-none"
              />
              <p className="text-[10px] text-slate-400 mt-1 text-right">كل ما كان الوصف أدق، كل ما كانت الفئات أنسب</p>
            </div>
            <Button
              className="w-full rounded-xl gap-2"
              disabled={!bizName.trim() || description.trim().length < 10 || isSuggesting}
              onClick={handleSuggest}
            >
              {isSuggesting ? (
                <><Loader2 className="w-4 h-4 animate-spin" /> جاري توليد الفئات...</>
              ) : (
                <><Sparkles className="w-4 h-4" /> توليد الفئات المقترحة</>
              )}
            </Button>
          </motion.div>
        )}

        {/* Step 3: Categories */}
        {step === "categories" && (
          <motion.div key="categories" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="space-y-3">
            <p className="text-xs text-slate-500 text-right">راجع وعدّل الفئات. تقدر تغير الاسم، الكلمات المفتاحية، الأيقونة، واللون.</p>
            {suggestedCategories.map((cat, idx) => (
              <CategoryEditCard
                key={idx}
                category={cat}
                onChange={(updated) => {
                  const next = [...suggestedCategories];
                  next[idx] = updated;
                  setSuggestedCategories(next);
                }}
                onRemove={() => setSuggestedCategories(suggestedCategories.filter((_, i) => i !== idx))}
              />
            ))}
            <button
              onClick={() => setSuggestedCategories([...suggestedCategories, {
                name: "", nameAr: "", type: "expense", icon: "🛍️", color: "#3b82f6",
                keywords: [], matchExamples: [], isAutoGenerated: false,
              }])}
              className="w-full p-3 rounded-xl border-2 border-dashed border-slate-200 dark:border-slate-800 text-slate-400 hover:text-indigo-500 hover:border-indigo-300 dark:hover:border-indigo-700 transition-all text-xs font-semibold gap-1.5 flex items-center justify-center"
            >
              <Plus className="w-4 h-4" /> إضافة فئة مخصصة
            </button>
            <Button
              className="w-full rounded-xl gap-2"
              disabled={suggestedCategories.length === 0 || createMutation.isPending}
              onClick={handleCreate}
            >
              {createMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
              تأكيد وإنشاء المشروع
            </Button>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

// ─── Category Edit Card ───
function CategoryEditCard({ category, onChange, onRemove }: {
  category: CategoryDraft;
  onChange: (cat: CategoryDraft) => void;
  onRemove: () => void;
}) {
  const [showKeywords, setShowKeywords] = useState(false);
  const [newKeyword, setNewKeyword] = useState("");

  return (
    <div className="p-3.5 rounded-2xl border border-slate-200/50 dark:border-slate-800/60 bg-white/60 dark:bg-slate-900/30 space-y-2.5">
      <div className="flex items-center gap-2">
        <button
          onClick={() => {
            const idx = ICON_OPTIONS.indexOf(category.icon);
            onChange({ ...category, icon: ICON_OPTIONS[(idx + 1) % ICON_OPTIONS.length] });
          }}
          className="w-10 h-10 rounded-xl flex items-center justify-center text-xl shrink-0"
          style={{ backgroundColor: category.color + "20" }}
        >
          {category.icon}
        </button>
        <Input
          value={category.nameAr}
          onChange={(e) => onChange({ ...category, nameAr: e.target.value, name: e.target.value })}
          placeholder="اسم الفئة..."
          className="rounded-lg text-sm flex-1 text-right"
        />
        <button
          onClick={() => {
            const idx = COLOR_OPTIONS.indexOf(category.color);
            onChange({ ...category, color: COLOR_OPTIONS[(idx + 1) % COLOR_OPTIONS.length] });
          }}
          className="w-7 h-7 rounded-lg shrink-0 border-2 border-white dark:border-slate-900 shadow-sm"
          style={{ backgroundColor: category.color }}
        />
        <button
          onClick={onRemove}
          className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors shrink-0"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
      <div className="flex items-center gap-1.5">
        {["expense", "income", "both"].map((t) => (
          <button
            key={t}
            onClick={() => onChange({ ...category, type: t })}
            className={`px-2.5 py-1 rounded-lg text-[10px] font-bold transition-all ${
              category.type === t ? "bg-slate-900 dark:bg-white text-white dark:text-slate-900" : "bg-slate-100 dark:bg-slate-800 text-slate-500"
            }`}
          >
            {t === "expense" ? "مصروف" : t === "income" ? "إيراد" : "الاثنين"}
          </button>
        ))}
      </div>
      <button
        onClick={() => setShowKeywords(!showKeywords)}
        className="text-[11px] text-slate-400 hover:text-indigo-500 transition-colors flex items-center gap-1"
      >
        <Tag className="w-3 h-3" /> كلمات مفتاحية ({category.keywords.length})
      </button>
      {showKeywords && (
        <div className="space-y-1.5">
          <div className="flex flex-wrap gap-1">
            {category.keywords.map((kw, i) => (
              <span key={i} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-[10px] font-medium text-slate-600 dark:text-slate-400">
                {kw}
                <button onClick={() => onChange({ ...category, keywords: category.keywords.filter((_, j) => j !== i) })}>
                  <X className="w-2.5 h-2.5 text-slate-400" />
                </button>
              </span>
            ))}
          </div>
          <div className="flex gap-1.5">
            <Input
              value={newKeyword}
              onChange={(e) => setNewKeyword(e.target.value)}
              placeholder="أضف كلمة..."
              className="rounded-lg text-xs h-8 text-right"
              onKeyDown={(e) => {
                if (e.key === "Enter" && newKeyword.trim()) {
                  onChange({ ...category, keywords: [...category.keywords, newKeyword.trim()] });
                  setNewKeyword("");
                }
              }}
            />
            <Button
              size="sm"
              variant="outline"
              className="h-8 px-2 rounded-lg shrink-0"
              onClick={() => {
                if (newKeyword.trim()) {
                  onChange({ ...category, keywords: [...category.keywords, newKeyword.trim()] });
                  setNewKeyword("");
                }
              }}
            >
              <Plus className="w-3 h-3" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Business Dashboard (existing business) ───
function BusinessDashboard({ business, categories, onBack, refetch }: {
  business: any;
  categories: any[];
  onBack: () => void;
  refetch: () => void;
}) {
  const { toast } = useToast();
  const utils = trpc.useUtils();
  const [showAddCategory, setShowAddCategory] = useState(false);
  const [showEditBusiness, setShowEditBusiness] = useState(false);
  const [editName, setEditName] = useState(business.name);
  const [editDesc, setEditDesc] = useState(business.description || "");

  const deleteMutation = trpc.business.delete.useMutation({
    onSuccess: () => {
      utils.business.get.invalidate();
      toast({ title: "تم حذف المشروع" });
      refetch();
    },
  });

  const removeCategoryMutation = trpc.business.removeCategory.useMutation({
    onSuccess: () => {
      utils.business.get.invalidate();
      toast({ title: "تم حذف الفئة" });
      refetch();
    },
  });

  const toggleActiveMutation = trpc.business.update.useMutation({
    onSuccess: () => {
      utils.business.get.invalidate();
      refetch();
    },
  });

  const updateMutation = trpc.business.update.useMutation({
    onSuccess: () => {
      utils.business.get.invalidate();
      refetch();
      setShowEditBusiness(false);
      toast({ title: "تم التحديث بنجاح" });
    },
  });

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-5"
    >
      {/* Header */}
      <div className="flex items-center gap-3">
        <button onClick={onBack} className="flex items-center justify-center w-10 h-10 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-900 dark:hover:bg-slate-800 transition-colors">
          <ArrowRight className="w-4.5 h-4.5 text-slate-600 dark:text-slate-400" />
        </button>
        <h1 className="text-xl font-bold text-slate-900 dark:text-white">مشروعك التجاري</h1>
      </div>

      {/* Business Info Card */}
      <div className="p-4 rounded-2xl bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 relative">
        <button
          onClick={() => setShowEditBusiness(true)}
          className="absolute top-4 left-4 p-2 rounded-lg bg-white/50 dark:bg-slate-900/50 hover:bg-white dark:hover:bg-slate-800 text-indigo-600 dark:text-indigo-400 transition-colors"
        >
          <Pencil className="w-4 h-4" />
        </button>
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-indigo-500/20 flex items-center justify-center shrink-0">
            <Store className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
          </div>
          <div className="flex-1 text-end">
            <h3 className="font-bold text-base text-slate-800 dark:text-slate-200">{business.name}</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">{business.typeLabel}</p>
          </div>
        </div>
        <div className="flex items-center justify-between mt-4">
          <button
            onClick={() => toggleActiveMutation.mutate({ isActive: !business.isActive })}
            className={`px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all ${
              business.isActive
                ? "bg-emerald-500/15 text-emerald-600 border border-emerald-500/20"
                : "bg-slate-200 dark:bg-slate-800 text-slate-500"
            }`}
          >
            {business.isActive ? "نشط" : "متوقف"}
          </button>
        </div>
        {business.description && (
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-3 leading-relaxed text-end">{business.description}</p>
        )}
      </div>

      {/* Quick Stats */}
      <BusinessQuickStats businessId={business.id} />

      {/* Categories */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">الفئات ({categories.length})</h4>
          <Button size="sm" variant="outline" className="rounded-lg gap-1 h-7 text-xs" onClick={() => setShowAddCategory(true)}>
            <Plus className="w-3 h-3" /> فئة
          </Button>
        </div>
        <div className="space-y-2">
          {categories.map((cat) => (
            <div key={cat.id} className="group flex items-center gap-3 p-3 rounded-xl bg-white/60 dark:bg-slate-900/30 border border-slate-200/50 dark:border-slate-800/60">
              <div className="w-9 h-9 rounded-lg flex items-center justify-center text-lg shrink-0" style={{ backgroundColor: (cat.color || "#3b82f6") + "20" }}>
                {cat.icon}
              </div>
              <div className="flex-1 text-end">
                <h5 className="font-semibold text-sm text-slate-800 dark:text-slate-200">{cat.nameAr}</h5>
                <div className="flex items-center gap-1.5 justify-end mt-0.5">
                  <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${
                    cat.type === "income" ? "bg-emerald-500/10 text-emerald-600"
                    : cat.type === "both" ? "bg-amber-500/10 text-amber-600"
                    : "bg-red-500/10 text-red-600"
                  }`}>
                    {cat.type === "income" ? "إيراد" : cat.type === "both" ? "الاثنين" : "مصروف"}
                  </span>
                  {cat.keywords && cat.keywords.length > 0 && (
                    <span className="text-[9px] text-slate-400">{cat.keywords.length} كلمات</span>
                  )}
                </div>
              </div>
              <button
                onClick={() => { if (confirm(`حذف فئة "${cat.nameAr}"؟`)) removeCategoryMutation.mutate({ id: cat.id }); }}
                className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-300 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors sm:opacity-0 group-hover:opacity-100"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Danger Zone */}
      <div className="pt-4 border-t border-slate-200/60 dark:border-slate-800/80">
        <Button
          variant="outline"
          className="w-full rounded-xl gap-2 text-red-500 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20 border-red-200 dark:border-red-900/30"
          onClick={() => {
            if (confirm(`حذف "${business.name}" نهائياً؟ كل الفئات هتتمسح. المصاريف المسجلة مش هتتأثر.`)) {
              deleteMutation.mutate();
            }
          }}
        >
          <Trash2 className="w-4 h-4" /> حذف المشروع نهائياً
        </Button>
      </div>

      <AddCategoryDialog open={showAddCategory} onOpenChange={setShowAddCategory} onAdd={() => { refetch(); setShowAddCategory(false); }} />

      {/* Edit Business Dialog */}
      <Dialog open={showEditBusiness} onOpenChange={setShowEditBusiness}>
        <DialogContent className="sm:max-w-[425px]" dir="rtl">
          <DialogHeader>
            <DialogTitle className="text-right text-lg">تعديل بيانات المشروع</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700 dark:text-slate-300">اسم المشروع</label>
              <Input
                value={editName}
                onChange={(e) => setEditName(e.target.value)}
                placeholder="اسم المشروع"
                className="text-right"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700 dark:text-slate-300">وصف المشروع</label>
              <Textarea
                value={editDesc}
                onChange={(e) => setEditDesc(e.target.value)}
                placeholder="تفاصيل الشغل أو المشروع"
                className="text-right resize-none min-h-[100px]"
              />
            </div>
            <div className="flex justify-end gap-3 pt-4">
              <Button variant="outline" onClick={() => setShowEditBusiness(false)}>
                إلغاء
              </Button>
              <Button
                disabled={!editName.trim() || updateMutation.isPending}
                onClick={() => updateMutation.mutate({ name: editName, description: editDesc })}
              >
                {updateMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : "حفظ التعديلات"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </motion.div>
  );
}

// ─── Quick Stats (mini) ───
function BusinessQuickStats({ businessId }: { businessId: number }) {
  const now = new Date();
  const month = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const statsQuery = trpc.expense.getMonthlyStats.useQuery({ month, businessId });

  const stats = statsQuery.data;
  if (!stats) return null;

  const income = stats.totalIncome || 0;
  const expense = stats.totalExpense || 0;
  const net = income - expense;

  return (
    <div className="grid grid-cols-3 gap-2">
      <div className="p-3 rounded-xl bg-emerald-500/8 border border-emerald-500/15 text-center">
        <TrendingUp className="w-4 h-4 text-emerald-500 mx-auto mb-1" />
        <p className="text-[10px] text-slate-400 mb-0.5">إيرادات</p>
        <p className="text-sm font-bold text-emerald-600 dark:text-emerald-400">{income.toLocaleString()}</p>
      </div>
      <div className="p-3 rounded-xl bg-red-500/8 border border-red-500/15 text-center">
        <TrendingDown className="w-4 h-4 text-red-500 mx-auto mb-1" />
        <p className="text-[10px] text-slate-400 mb-0.5">مصاريف</p>
        <p className="text-sm font-bold text-red-600 dark:text-red-400">{expense.toLocaleString()}</p>
      </div>
      <div className={`p-3 rounded-xl border text-center ${net >= 0 ? "bg-indigo-500/8 border-indigo-500/15" : "bg-amber-500/8 border-amber-500/15"}`}>
        <Wallet className="w-4 h-4 text-indigo-500 mx-auto mb-1" />
        <p className="text-[10px] text-slate-400 mb-0.5">الصافي</p>
        <p className={`text-sm font-bold ${net >= 0 ? "text-indigo-600 dark:text-indigo-400" : "text-amber-600 dark:text-amber-400"}`}>
          {net.toLocaleString()}
        </p>
      </div>
    </div>
  );
}

// ─── Add Category Dialog ───
function AddCategoryDialog({ open, onOpenChange, onAdd }: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onAdd: () => void;
}) {
  const { toast } = useToast();
  const [name, setName] = useState("");
  const [type, setType] = useState("expense");
  const [icon, setIcon] = useState("🛍️");
  const [color, setColor] = useState("#3b82f6");
  const [keywords, setKeywords] = useState<string[]>([]);
  const [newKeyword, setNewKeyword] = useState("");

  const addMutation = trpc.business.addCategory.useMutation({
    onSuccess: () => {
      toast({ title: "تم إضافة الفئة" });
      onAdd();
      setName(""); setKeywords([]);
    },
    onError: (err) => toast({ title: err.message, variant: "error" }),
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-sm rounded-2xl">
        <DialogHeader><DialogTitle className="text-right text-lg">إضافة فئة</DialogTitle></DialogHeader>
        <div className="space-y-3 pt-2">
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">اسم الفئة</label>
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: مرتبات، بضاعة، تغليف" className="rounded-xl text-right" />
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">النوع</label>
            <div className="flex gap-1.5">
              {["expense", "income", "both"].map((t) => (
                <button key={t} onClick={() => setType(t)} className={`flex-1 py-2 rounded-lg text-xs font-bold transition-all ${
                  type === t ? "bg-slate-900 dark:bg-white text-white dark:text-slate-900" : "bg-slate-100 dark:bg-slate-800 text-slate-500"
                }`}>
                  {t === "expense" ? "مصروف" : t === "income" ? "إيراد" : "الاثنين"}
                </button>
              ))}
            </div>
          </div>
          <div className="flex gap-3">
            <div className="flex-1">
              <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">أيقونة</label>
              <div className="flex flex-wrap gap-1">
                {ICON_OPTIONS.slice(0, 9).map((ic) => (
                  <button key={ic} onClick={() => setIcon(ic)} className={`w-8 h-8 rounded-lg text-base flex items-center justify-center transition-all ${
                    icon === ic ? "bg-indigo-500/20 ring-2 ring-indigo-500" : "bg-slate-100 dark:bg-slate-800"
                  }`}>{ic}</button>
                ))}
              </div>
            </div>
            <div>
              <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">لون</label>
              <div className="flex flex-wrap gap-1 max-w-[100px]">
                {COLOR_OPTIONS.slice(0, 6).map((c) => (
                  <button key={c} onClick={() => setColor(c)} className={`w-7 h-7 rounded-lg transition-all ${color === c ? "ring-2 ring-offset-1 ring-slate-400" : ""}`} style={{ backgroundColor: c }} />
                ))}
              </div>
            </div>
          </div>
          <div>
            <label className="text-xs font-semibold text-slate-500 mb-1.5 block text-right">كلمات مفتاحية</label>
            <div className="flex flex-wrap gap-1 mb-1.5">
              {keywords.map((kw, i) => (
                <span key={i} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-[10px] font-medium">
                  {kw}
                  <button onClick={() => setKeywords(keywords.filter((_, j) => j !== i))}><X className="w-2.5 h-2.5 text-slate-400" /></button>
                </span>
              ))}
            </div>
            <Input value={newKeyword} onChange={(e) => setNewKeyword(e.target.value)} placeholder="اكتب كلمة واضغط Enter..." className="rounded-lg text-xs h-8 text-right"
              onKeyDown={(e) => { if (e.key === "Enter" && newKeyword.trim()) { setKeywords([...keywords, newKeyword.trim()]); setNewKeyword(""); } }}
            />
          </div>
          <Button
            className="w-full rounded-xl"
            disabled={!name.trim() || addMutation.isPending}
            onClick={() => addMutation.mutate({
              name: name.trim(), nameAr: name.trim(),
              type: type as "expense" | "income" | "both",
              icon, color, keywords, matchExamples: [],
            })}
          >
            <Plus className="w-4 h-4 mr-1.5" /> إضافة
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Fallback categories when AI fails ───
function getFallbackCategories(bizType: string): CategoryDraft[] {
  const templates: Record<string, CategoryDraft[]> = {
    restaurant: [
      { name: "بضاعة ومشتريات", nameAr: "بضاعة ومشتريات", type: "expense", icon: "🍤", color: "#f97316", keywords: ["بضاعة", "سمك", "لحمة", "خضار", "جمبري", "سبيط", "مكونات"], matchExamples: ["شتريت بضاعة سمك", "جبت لحمة"], isAutoGenerated: true },
      { name: "مرتبات", nameAr: "مرتبات وعمال", type: "expense", icon: "👷", color: "#3b82f6", keywords: ["مرتب", "راتب", "عامل", "موظف", "أجور"], matchExamples: ["دفعت مرتب", "صرفت عمال"], isAutoGenerated: true },
      { name: "صيانة ومعدات", nameAr: "صيانة ومعدات", type: "expense", icon: "⚙️", color: "#6b7280", keywords: ["صيانة", "ثلاجة", "معدات", "تصليح", "أدوات"], matchExamples: ["صرفت صيانة", "اشتريت معدات"], isAutoGenerated: true },
      { name: "مبيعات", nameAr: "مبيعات", type: "income", icon: "💰", color: "#10b981", keywords: ["مبيعات", "بيع", "دخل", "إيراد"], matchExamples: ["مبيعات اليوم", "بعت"], isAutoGenerated: true },
    ],
    retail: [
      { name: "بضاعة", nameAr: "مشتريات بضاعة", type: "expense", icon: "📦", color: "#f97316", keywords: ["بضاعة", "مشتريات", "توريد", "سلع"], matchExamples: ["شتريت بضاعة"], isAutoGenerated: true },
      { name: "مرتبات", nameAr: "مرتبات", type: "expense", icon: "👷", color: "#3b82f6", keywords: ["مرتب", "راتب", "موظف"], matchExamples: ["دفعت مرتب"], isAutoGenerated: true },
      { name: "إيجار المحل", nameAr: "إيجار المحل", type: "expense", icon: "🏪", color: "#ef4444", keywords: ["إيجار", "ايجار", "محل", "rent"], matchExamples: ["دفعت إيجار"], isAutoGenerated: true },
      { name: "مبيعات", nameAr: "مبيعات", type: "income", icon: "💰", color: "#10b981", keywords: ["مبيعات", "بيع", "دخل"], matchExamples: ["مبيعات"], isAutoGenerated: true },
    ],
    services: [
      { name: "مواد وخامات", nameAr: "مواد وخامات", type: "expense", icon: "🧰", color: "#f97316", keywords: ["مواد", "خامات", "مكونات", "قطع غيار"], matchExamples: ["شتريت مواد"], isAutoGenerated: true },
      { name: "مرتبات", nameAr: "مرتبات", type: "expense", icon: "👷", color: "#3b82f6", keywords: ["مرتب", "راتب", "عامل"], matchExamples: ["دفعت مرتب"], isAutoGenerated: true },
      { name: "معدات", nameAr: "معدات وأدوات", type: "expense", icon: "⚙️", color: "#6b7280", keywords: ["معدات", "أدوات", "تصليح"], matchExamples: ["اشتريت أدوات"], isAutoGenerated: true },
      { name: "إيرادات", nameAr: "إيرادات الخدمات", type: "income", icon: "💰", color: "#10b981", keywords: ["إيراد", "دخل", "عميل", "خدمة"], matchExamples: ["جالي إيراد"], isAutoGenerated: true },
    ],
    freelance: [
      { name: "مصاريف عمل", nameAr: "مصاريف العمل", type: "expense", icon: "💻", color: "#f97316", keywords: ["hosting", "سيرفر", "اشتراك", "api", "software"], matchExamples: ["دفعت hosting"], isAutoGenerated: true },
      { name: "إيرادات", nameAr: "إيرادات", type: "income", icon: "💰", color: "#10b981", keywords: ["مشروع", "عميل", "فاتورة", "دخل"], matchExamples: ["قبضت مشروع"], isAutoGenerated: true },
    ],
  };
  return templates[bizType] || templates.freelance;
}
