import { z } from "zod";
import { router, proProcedure, proAiProcedure } from "./middleware";
import { TRPCError } from "@trpc/server";
import { db } from "./queries/connection";
import {
  userBusinesses,
  businessCategories,
  userContacts,
  expenses,
} from "../db/schema";
import { eq, and, sql } from "drizzle-orm";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { invalidateUserClassificationCache } from "./lib/smart-pipeline";
import { invalidateUserMemory } from "./lib/muscle-memory";
import { getSystemSettings } from "./lib/settings-cache";
import { env } from "./lib/env";

const BUSINESS_TYPES = [
  { id: "restaurant", label: "مطاعم ومأكولات", icon: "🍤" },
  { id: "retail", label: "تجارة وتجزئة", icon: "🛍️" },
  { id: "services", label: "خدمات وورش", icon: "🔧" },
  { id: "freelance", label: "عمل حر وشركات", icon: "💻" },
  { id: "custom", label: "نوع آخر", icon: "✏️" },
] as const;

const SUGGESTION_PROMPT = `أنت مساعد ذكي لتصنيف مصاريف الأعمال المصرية.
بناءً على وصف المشروع، اقترح 4-8 فئات مناسبة (مصاريف + إيرادات).

قواعد:
1. keywords: كلمات مفتاحية بالعامية المصرية اللي المستخدم ممكن يكتبها فعلياً (5-12 كلمة)
2. matchExamples: 2-3 جمل أمثلة بالمصري للمعاملات اللي هتنتمي للفئة دي
3. icon: إيموجي مناسب من الإيموجيز المتاحة
4. color: كود لون HEX
5. type: "expense" أو "income" أو "both"

رد بـ JSON فقط:
{"categories":[{"name":"...","type":"expense","keywords":["...","..."],"matchExamples":["...","..."],"icon":"...","color":"#..."}]}`;

async function getApiKey(): Promise<string> {
  const settings = await getSystemSettings();
  return settings.gemini_api_key || env.GEMINI_API_KEY || "";
}

export const businessRouter = router({
  get: proProcedure
    .input(z.object({}).optional())
    .query(async ({ ctx }) => {
      const businesses = await db
        .select()
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
        ));

      if (businesses.length === 0) {
        return { business: null, categories: [] };
      }

      const business = businesses[0];
      const categories = await db
        .select()
        .from(businessCategories)
        .where(and(
          eq(businessCategories.businessId, business.id),
          eq(businessCategories.isActive, true),
        ));

      const contactCount = await db
        .select({ count: sql<number>`count(*)` })
        .from(userContacts)
        .where(and(
          eq(userContacts.businessId, business.id),
          eq(userContacts.contactType, "business_supplier"),
        ));

      return {
        business: {
          id: business.id,
          name: business.name,
          type: business.type,
          typeLabel: business.typeLabel,
          description: business.description,
          keywords: business.keywords,
          isActive: business.isActive,
        },
        categories: categories.map((c) => ({
          id: c.id,
          name: c.name,
          nameAr: c.nameAr,
          icon: c.icon,
          color: c.color,
          type: c.type,
          keywords: c.keywords,
          matchExamples: c.matchExamples,
          isAutoGenerated: c.isAutoGenerated,
        })),
        contactCount: Number(contactCount[0]?.count || 0),
      };
    }),

  types: proProcedure
    .query(() => BUSINESS_TYPES),

  suggestCategories: proAiProcedure
    .input(z.object({
      description: z.string().min(10).max(2000),
      businessName: z.string().min(1).max(255),
      businessType: z.string().min(1).max(100),
    }))
    .mutation(async ({ ctx, input }) => {
      const apiKey = await getApiKey();
      if (!apiKey) {
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "مفتاح AI غير متاح" });
      }

      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-3.1-flash-lite",
        systemInstruction: SUGGESTION_PROMPT,
        generationConfig: {
          temperature: 0.3,
          maxOutputTokens: 2048,
          responseMimeType: "application/json",
        },
      });

      const sanitizeForPrompt = (input: string): string => {
        return input
          .replace(/[\n\r]/g, ' ')          // Remove newlines
          .replace(/```/g, '')               // Remove code blocks  
          .replace(/system:|assistant:|user:/gi, '') // Remove role markers
          .slice(0, 500);                    // Hard limit length
      };

      const userPrompt = `اسم المشروع: ${sanitizeForPrompt(input.businessName)}\nنوع المشروع: ${sanitizeForPrompt(input.businessType)}\nوصف المشروع: ${sanitizeForPrompt(input.description)}\n\nاقترح الفئات المناسبة:`;

      try {
        const result = await model.generateContent(userPrompt);
        const text = result.response.text();
        const parsed = JSON.parse(text);

        if (!parsed.categories || !Array.isArray(parsed.categories)) {
          throw new Error("Invalid response format");
        }

        return {
          categories: parsed.categories.map((c: any) => ({
            name: String(c.name || ""),
            nameAr: String(c.name || ""),
            type: ["expense", "income", "both"].includes(c.type) ? c.type : "expense",
            keywords: Array.isArray(c.keywords) ? c.keywords.map(String) : [],
            matchExamples: Array.isArray(c.matchExamples) ? c.matchExamples.map(String) : [],
            icon: String(c.icon || "🛍️"),
            color: String(c.color || "#3b82f6"),
            isAutoGenerated: true,
          })),
        };
      } catch (err) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "فشل في توليد الفئات. حاول مرة أخرى.",
        });
      }
    }),

  create: proProcedure
    .input(z.object({
      name: z.string().min(1).max(255),
      type: z.string().min(1).max(100),
      typeLabel: z.string().max(255).optional(),
      description: z.string().max(2000).optional(),
      keywords: z.array(z.string()).optional(),
      categories: z.array(z.object({
        name: z.string().min(1).max(100),
        nameAr: z.string().min(1).max(100),
        type: z.enum(["expense", "income", "both"]).default("expense"),
        icon: z.string().max(50).default("🛍️"),
        color: z.string().max(50).default("#3b82f6"),
        keywords: z.array(z.string()).default([]),
        matchExamples: z.array(z.string()).default([]),
        isAutoGenerated: z.boolean().default(true),
      })).default([]),
    }))
    .mutation(async ({ ctx, input }) => {
      const existing = await db
        .select({ id: userBusinesses.id })
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
          eq(userBusinesses.isActive, true),
        ))
        .limit(1);

      if (existing.length > 0) {
        throw new TRPCError({ code: "CONFLICT", message: "لديك مشروع نشط بالفعل" });
      }

      const [business] = await db
        .insert(userBusinesses)
        .values({
          userId: ctx.user.id,
          userType: ctx.user.type,
          name: input.name,
          type: input.type,
          typeLabel: input.typeLabel || input.type,
          description: input.description || "",
          keywords: input.keywords || [],
          isActive: true,
        });

      if (input.categories.length > 0) {
        await db.insert(businessCategories).values(
          input.categories.map((c) => ({
            businessId: business.insertId,
            name: c.name,
            nameAr: c.nameAr,
            type: c.type,
            icon: c.icon,
            color: c.color,
            keywords: c.keywords,
            matchExamples: c.matchExamples,
            isAutoGenerated: c.isAutoGenerated,
            isActive: true,
          })),
        );
      }

      invalidateUserClassificationCache(ctx.user.id);
      invalidateUserMemory(ctx.user.id, ctx.user.type);

      return { id: business.insertId, success: true };
    }),

  update: proProcedure
    .input(z.object({
      name: z.string().min(1).max(255).optional(),
      description: z.string().max(2000).optional(),
      keywords: z.array(z.string()).optional(),
      isActive: z.boolean().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const existing = await db
        .select()
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
        ))
        .limit(1);

      if (existing.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع" });
      }

      const updates: Record<string, unknown> = {};
      if (input.name !== undefined) updates.name = input.name;
      if (input.description !== undefined) updates.description = input.description;
      if (input.keywords !== undefined) updates.keywords = input.keywords;
      if (input.isActive !== undefined) updates.isActive = input.isActive;

      if (Object.keys(updates).length > 0) {
        await db
          .update(userBusinesses)
          .set(updates)
          .where(eq(userBusinesses.id, existing[0].id));
      }

      invalidateUserClassificationCache(ctx.user.id);
      return { success: true };
    }),

  delete: proProcedure
    .mutation(async ({ ctx }) => {
      const existing = await db
        .select()
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
        ))
        .limit(1);

      if (existing.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع" });
      }

      const businessId = existing[0].id;
      const { transferBusinessRollupsToPersonal } = await import("./services/expense-rollups");

      await db.transaction(async (tx) => {
        await tx.delete(businessCategories).where(eq(businessCategories.businessId, businessId));
        await tx
          .update(userContacts)
          .set({ businessId: null, contactType: "personal" })
          .where(and(eq(userContacts.businessId, businessId), eq(userContacts.userId, ctx.user.id), eq(userContacts.userType, ctx.user.type)));
        await transferBusinessRollupsToPersonal(tx, ctx.user.id, ctx.user.type, businessId);
        await tx
          .update(expenses)
          .set({ businessId: null })
          .where(and(eq(expenses.businessId, businessId), eq(expenses.userId, ctx.user.id), eq(expenses.userType, ctx.user.type)));
        await tx
          .delete(userBusinesses)
          .where(and(eq(userBusinesses.id, businessId), eq(userBusinesses.userId, ctx.user.id), eq(userBusinesses.userType, ctx.user.type)));
      });

      invalidateUserClassificationCache(ctx.user.id);
      invalidateUserMemory(ctx.user.id, ctx.user.type);
      try {
        const { cacheIncr } = await import("./lib/redis-client");
        const { CacheKeys } = await import("./lib/cache-keys");
        const { invalidateFinanceUserCache } = await import("./services/finance-semantic-layer");
        await cacheIncr(CacheKeys.cacheGen(ctx.user.type, ctx.user.id));
        await invalidateFinanceUserCache(ctx.user.id, ctx.user.type);
      } catch (err) {
        console.warn("Failed to invalidate expense cache on business delete", err);
      }
      return { success: true };
    }),

  addCategory: proProcedure
    .input(z.object({
      name: z.string().min(1).max(100),
      nameAr: z.string().min(1).max(100),
      type: z.enum(["expense", "income", "both"]).default("expense"),
      icon: z.string().max(50).default("🛍️"),
      color: z.string().max(50).default("#3b82f6"),
      keywords: z.array(z.string()).default([]),
      matchExamples: z.array(z.string()).default([]),
    }))
    .mutation(async ({ ctx, input }) => {
      const business = await db
        .select({ id: userBusinesses.id })
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
          eq(userBusinesses.isActive, true),
        ))
        .limit(1);

      if (business.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع نشط" });
      }

      const [cat] = await db.insert(businessCategories).values({
        businessId: business[0].id,
        name: input.name,
        nameAr: input.nameAr,
        type: input.type,
        icon: input.icon,
        color: input.color,
        keywords: input.keywords,
        matchExamples: input.matchExamples,
        isAutoGenerated: false,
        isActive: true,
      });

      invalidateUserClassificationCache(ctx.user.id);
      return { id: cat.insertId, success: true };
    }),

  updateCategory: proProcedure
    .input(z.object({
      id: z.number(),
      name: z.string().min(1).max(100).optional(),
      nameAr: z.string().min(1).max(100).optional(),
      type: z.enum(["expense", "income", "both"]).optional(),
      icon: z.string().max(50).optional(),
      color: z.string().max(50).optional(),
      keywords: z.array(z.string()).optional(),
      matchExamples: z.array(z.string()).optional(),
      isActive: z.boolean().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const { id, ...updates } = input;
      const cleanUpdates = Object.fromEntries(
        Object.entries(updates).filter(([, v]) => v !== undefined),
      );

      const business = await db
        .select({ id: userBusinesses.id })
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
          eq(userBusinesses.isActive, true),
        ))
        .limit(1);

      if (business.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع نشط" });
      }

      const existingCat = await db
        .select({ id: businessCategories.id })
        .from(businessCategories)
        .where(and(
          eq(businessCategories.id, id),
          eq(businessCategories.businessId, business[0].id),
        ))
        .limit(1);

      if (existingCat.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "الفئة غير موجودة" });
      }

      if (Object.keys(cleanUpdates).length > 0) {
        await db
          .update(businessCategories)
          .set(cleanUpdates)
          .where(and(
            eq(businessCategories.id, id),
            eq(businessCategories.businessId, business[0].id),
          ));
      }

      invalidateUserClassificationCache(ctx.user.id);
      return { success: true };
    }),

  removeCategory: proProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const business = await db
        .select({ id: userBusinesses.id })
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
          eq(userBusinesses.isActive, true),
        ))
        .limit(1);

      if (business.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع نشط" });
      }

      const existingCat = await db
        .select({ id: businessCategories.id })
        .from(businessCategories)
        .where(and(
          eq(businessCategories.id, input.id),
          eq(businessCategories.businessId, business[0].id),
        ))
        .limit(1);

      if (existingCat.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "الفئة غير موجودة" });
      }

      await db
        .update(businessCategories)
        .set({ isActive: false })
        .where(and(
          eq(businessCategories.id, input.id),
          eq(businessCategories.businessId, business[0].id),
        ));

      invalidateUserClassificationCache(ctx.user.id);
      return { success: true };
    }),

  linkContact: proProcedure
    .input(z.object({
      contactId: z.number(),
      contactType: z.enum(["business_supplier", "business_customer", "business_employee"]),
    }))
    .mutation(async ({ ctx, input }) => {
      const business = await db
        .select({ id: userBusinesses.id })
        .from(userBusinesses)
        .where(and(
          eq(userBusinesses.userId, ctx.user.id),
          eq(userBusinesses.userType, ctx.user.type),
          eq(userBusinesses.isActive, true),
        ))
        .limit(1);

      if (business.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "لا يوجد مشروع نشط" });
      }

      const existingContact = await db
        .select({ id: userContacts.id })
        .from(userContacts)
        .where(and(
          eq(userContacts.id, input.contactId),
          eq(userContacts.userId, ctx.user.id),
          eq(userContacts.userType, ctx.user.type),
        ))
        .limit(1);

      if (existingContact.length === 0) {
        throw new TRPCError({ code: "NOT_FOUND", message: "جهة الاتصال غير موجودة" });
      }

      await db
        .update(userContacts)
        .set({ businessId: business[0].id, contactType: input.contactType })
        .where(and(
          eq(userContacts.id, input.contactId),
          eq(userContacts.userId, ctx.user.id),
          eq(userContacts.userType, ctx.user.type),
        ));

      invalidateUserClassificationCache(ctx.user.id);
      return { success: true };
    }),
});
